### ISSUE TITLE
Feature Request: Example parameter values

### ISSUE THREAD

**Issue by gmr** [Rebilly/ReDoc#100]
I know this is somewhat bleeding into the open-api spec itself, so I understand if this is too much scope creep, but I'd love to be able to provide example values for parameter values. The examples are great for responses, but for requests, the auto-built examples built off of type are good, but utilitarian.

So for example, I could set a `x-example` attribute for a parameter in a schema I could turn this:

![screen shot 2016-09-02 at 9 45 49 am](https://cloud.githubusercontent.com/assets/49469/18205826/1c9b5be2-70f2-11e6-85bd-e796336d380d.png)

to 

![screen shot 2016-09-02 at 9 47 40 am](https://cloud.githubusercontent.com/assets/49469/18205888/57472906-70f2-11e6-8145-afe690b26f83.png)

Does that seem reasonable? I tried to go down the `x-code-snippets` route but it wasn't quite the same as what I was trying to achieve.

**Comment by RomanGotsiy** [comment]
This is actually supported by both OpenAPI spec and ReDoc :)

You can use `example` field on [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object).

So you can specify `example` on property level (see example in our [demo spec](https://github.com/Rebilly/ReDoc/blob/master/demo/swagger.yaml#L794) or even on schema level:

```js
{
  "type": "object",
  "properties": {
    // ...
  },
  "example": {
     "user": "gmr",
     "notes": " this is a example note",
     "bin": "9656534-32429432-34329432-bbc3234"
  }
}
```

Does it solve your problem?

**Comment by gmr** [comment]
Ah my bad, I missed the example attribute, or conflated it with examples for responses.

**Comment by cbautista1002** [comment]
Thanks guys!

But for anyone who stumbles across this post and is hoping to add the example to each individual property - you can do that with `example`:
```
{
  "type": "object",
  "properties": {
    "user": {
      "type": "string",
      "description": "the user name",
      "example": "gmr"
    }
  }
}
```

I prefer this approach because it keeps the example right next to the definition and it avoids duplicating the field names.
