### ISSUE TITLE
Can't add json request sample by using x-code-samples

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#101]
Currently i can only add JSON request sample by specifying "example" value for each parameter in definitions. It's kind of troublesome. While I can add other language request samples like PHP, C#, etc by using "x-code samples". If I add JSON request sample by using "x-code samples", two JSON tabs are generated.

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 according, to OpenAPI spec you can use `example` field on [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object).

So just add `example` to the definition itself, not for each parameter, e.g.:

```js
{
  "type": "object",
  "properties": {
    // ...
  },
  "example": {
     "user": "gmr",
     "notes": " this is a example note",
     "bin": "9656534-32429432-34329432-bbc3234"
  }
}
```

Does it solve your problem?

**Comment by jenniferwang2000** [comment]
Yes, it is exactly what i need. Thanks a lot! Thank you~~
