### ISSUE TITLE
Feature Request: Render contents of externalDocs item

### ISSUE THREAD

**Issue by ChrisPearce** [Rebilly/ReDoc#103]
It would be very useful if the description and url properties of the externalDocs items were rendered as part of the documentation output

**Comment by RomanGotsiy** [comment]
@ChrisPearce thanks for the suggestion.
Will definitely implement this. Hopefully, I will do it in the next minor release but most likely in the next next :)

**Comment by RomanGotsiy** [comment]
@ChrisPearce Adding this to my to-do for the next release

**Comment by runes83** [comment]
Is this feature far away? We need this to send the users to the SDK download page

**Comment by RomanGotsiy** [comment]
oops, missed that...
Hopefully will be ready in the next release planned for the beginning of the next week

**Comment by runes83** [comment]
Thanks

**Comment by runes83** [comment]
Is this released in a new version?

**Comment by RomanGotsiy** [comment]
New version has been delayed... I will let you know once it's ready

**Comment by RomanGotsiy** [comment]
@runes83 new version has just been released 🎉
