### ISSUE TITLE
host value is not automatically propagated if not specified in spec (relative path to spec case)

### ISSUE THREAD

**Issue by sinha-bharat** [Rebilly/ReDoc#108]
The definition of my rest service path/to/my/service/url which works fine when I specify base path for swagger; But when I use ReDoc the rightmost panel shows the path as 
POST http://null/path/to/my/service/url 

the swagger.json representation has basePath specified, how can ReDoc read the element and fix the post URL.

I am using relative path for redoc spec-url.
  <redoc spec-url='path/to/my/service/url'></redoc>

**Comment by RomanGotsiy** [comment]
I have checked and confirm this is a bug. I will fix it for the next release.
Temporary as a workaround you can either specify full URL to your spec in ReDoc options or specify `host` in the swagger (see example in our [demo spec](https://github.com/Rebilly/ReDoc/blob/master/demo/swagger.yaml))

**Comment by sinha-bharat** [comment]
I wasn't sure that I had enough there for you to explain the problem but it seems that was okay. 

Thank you for adding the label and fixing it in the next release.

**Comment by RomanGotsiy** [comment]
fixed and released

**Comment by sinha-bharat** [comment]
Thank you Roman; I verified and it works as intended. Thank you!
