### ISSUE TITLE
Token "QueryParam" does not exist. 

### ISSUE THREAD

**Issue by crystalfp** [Rebilly/ReDoc#110]
I'm in the middle of splitting parameters and definitions from my swagger.yaml file into distinct yaml files. Now ReDoc refuses to load my file pretending that:

**Oops... ReDoc failed to render this spec**

**Error resolving $ref pointer "http://localhost:8080/parameters.yaml#/QueryParam". Token "QueryParam" does not exist.**

When in fact it is here in parameters.yaml file.

But if I put the yaml files in a subdirectory (changing redoc.html to point to bug/swagger.yaml) or on a [real website](http://mariovalle.name/a/redoc.html) then the error disappears.

Previously I resolved the problem for another parameter simply moving its definition to another place in the same parameters.yaml file.

To reproduce locally, download the [api.zip](http://mariovalle.name/a/api.zip) file, unpack it and run mongoose from the same directory to serve the files.

Please let me know what I need to do to help diagnose the problem.
Thanks for your help!
mario

**Comment by crystalfp** [comment]
Seems a mongoose caching issue. Sorry for the noise.

**Comment by RomanGotsiy** [comment]
Hey @crystalfp.

I suspect something is wrong your server. I've just downloaded your file, unpacked and started simple http server ([http-server](https://www.npmjs.com/package/http-server)) and it worked fine for me.

**Comment by RomanGotsiy** [comment]
@crystalfp NP :)
