### ISSUE TITLE
specify swagger.json as input to ReDoc page

### ISSUE THREAD

**Issue by sinha-bharat** [Rebilly/ReDoc#112]
Can ReDoc also take swagger.json path/url as input text like swagger? This would help us deploy the page and handle swagger.json path of various applications using a single app. This will be an enhancement.

Thanks.

**Comment by RomanGotsiy** [comment]
@sinha-bharat I'm not sure If I understood you correctly. Do you need to specify which file to use as an input in runtime?

Check out [Advanced usage](https://github.com/Rebilly/ReDoc#advanced-usage) section in README.

**Comment by adamaltman** [comment]
https://rebilly.github.io/ReDoc/  <-- look at the top of that page.  

![image](https://cloud.githubusercontent.com/assets/1161871/19085884/96e0d956-8a31-11e6-9497-e5f783183c85.png)

Is that what you're looking for?

**Comment by IvanGoncharov** [comment]
@sinha-bharat you can also specify URL to Swagger spec as query parameter see example:



<img width="747" alt="screen shot 2016-10-04 at 21 44 42" src="https://cloud.githubusercontent.com/assets/8336157/19121789/6a747990-8b30-11e6-81fe-e9f851b90935.png">

**Comment by RomanGotsiy** [comment]
@sinha-bharat is it issue still relevant?

**Comment by RomanGotsiy** [comment]
Closing, feel free to reopen
