### ISSUE TITLE
Error when I want to start the development server 

### ISSUE THREAD

**Issue by amanganiello90** [Rebilly/ReDoc#116]
I have followed every step of your development section on Windows machine, with your Demo configuration that is a yaml file and not a json (please correct your doc).
So I haven't replace your  **demo/swagger.yaml** but node runs this exception with the **npm start**:

---------------------------------------------
Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Emilio\git\ReDoc>npm start

> redoc@1.3.2 start C:\Users\Emilio\git\ReDoc
> webpack-dev-server --config build/webpack.dev.js --content-base demo

C:\Users\Emilio\git\ReDoc\node_modules\webpack\lib\webpack.js:16
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a co
nfiguration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, l
oader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, r
ecordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the load
er:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         options: {
           debug: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, lo
aders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?,
unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node['fs'] should be one of these:
   false | true | "mock"
 - configuration.node['crypto'] should be one of these:
   false | true | "mock"
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModu
leExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugin
s?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (C:\Users\Emilio\git\ReDoc\node_modules\webpack\lib\webpack.js:16:9)
    at processOptions (C:\Users\Emilio\git\ReDoc\node_modules\webpack-dev-server\bin\webpack-dev-ser
ver.js:263:13)
    at Object.<anonymous> (C:\Users\Emilio\git\ReDoc\node_modules\webpack-dev-server\bin\webpack-dev
-server.js:283:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! redoc@1.3.2 start: `webpack-dev-server --config build/webpack.dev.js --content-base demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redoc@1.3.2 start script 'webpack-dev-server --config build/webpack.dev.js --
content-base demo'.
npm ERR! This is most likely a problem with the redoc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config build/webpack.dev.js --content-base demo
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redoc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls redoc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Emilio\git\ReDoc\npm-debug.log
---------------------------------------------

**Comment by jroweboy** [comment]
I ran into this same issue. This can be fixed by installing a particular version of webpack as explained in this angular issue https://github.com/angular/angular-cli/issues/2234#issuecomment-248174857

**Comment by amanganiello90** [comment]
thanks all, I will fix this problem in this repo.

**Comment by amanganiello90** [comment]
I haven't permissions to push the fix. So I have forked the project and push the commit on my repo.
If you want this update, you can grant me as contributor member for your project.
Thanks

**Comment by jroweboy** [comment]
@amanganiello90 you can open a pull request to this repository with your fixes and the owner can review the changes and merge them if they meet the owner's expectations. (Usually projects don't just give out write permission for small changes like this. Pull requests are the standard way to submit code)

**Comment by amanganiello90** [comment]
I know that I can open a pull request to merge my fix branch with the master, but I hadn't also permission to push a my branch. For this I have forked the repo so that I was able to open a pull request.
Thanks all.
