### ISSUE TITLE
The development server doesn't render on Windows 

### ISSUE THREAD

**Issue by amanganiello90** [Rebilly/ReDoc#119]
The #116 fix issue has resolved the run of the server **(npm start)**. It runs on windows and linux even if the console shows the following error:

----------------------------- 
_[default] C:\Users\amanganiello\Desktop\ReDoc-master\lib\bootstrap.ts:2:38
    Cannot find module './redoc.module.ngfactory'.
[default] Checking finished with 1 errors_

----------------------------- 

However on Linux machine it runs and the browser renders the web pages, but in Windows (whichever node version, 4.5.0 or 6.6.0) Chrome and Firefox show this error page:

![server error](https://cloud.githubusercontent.com/assets/20536757/18741485/cc0fa05c-80af-11e6-872c-f5c2d85f9867.PNG)

**Comment by jroweboy** [comment]
I had the same error and opened a ticket yesterday as well. https://github.com/Rebilly/ReDoc/issues/118 Looks like you showed that its not just me with this problem on windows 👍 Also, ubuntu bash subsystem for windows doesn't work either so I can't just use that instead.

**Comment by amanganiello90** [comment]
Ok Thanks
