### ISSUE TITLE
Can we add link to section heading in description from field description? 

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#121]

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 can you clarify what you mean? I'm not sure if understood you correctly.

**Comment by jenniferwang2000** [comment]
Sorry for the confusion. 
In swagger editor, we can add multiple sections in the object "description" part. For example, if one section is called "Notes" in the object "description" part. And in field description in "definitions", i want to reference the "Notes" section above. I mean how to make such link? Do we support this?

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 sorry for late response.

Unfortunately this is not supported yet. Currently it is possible only to link tags operations or top-level headings from spec `description` field.
It is planned to add support of linking to all parts of doc but not sure when I get to this

**Comment by RomanGotsiy** [comment]
closing this issue
will be tracked in #63
