### ISSUE TITLE
Minimum of zero is not rendered properly

### ISSUE THREAD

**Issue by nakedible-p** [Rebilly/ReDoc#123]
Currently it seems that specifying `minimum: 0` is not visible in any way in the generated documentation, and also specifying `minimum: 0` and `maximum: 999` shows `<= 999` in the generated documentation which is obviously untrue as negative values are not accepted.

I am assuming this is probably caused by the same things that caused `false` defaults not to be displayed.

**Comment by RomanGotsiy** [comment]
@nakedible-p, thanks for reporting.
Will be fixed in the next minor release
