### ISSUE TITLE
npm install errors on Windows

### ISSUE THREAD

**Issue by juleux** [Rebilly/ReDoc#127]
NPM install errors using Windows 10.  Updated node to latest version.  In GitBash, running npm install redoc --save.
NPM debug log attached. 

![gitbash redoc install](https://cloud.githubusercontent.com/assets/18660620/19478939/6c9564be-9512-11e6-9c5c-b5cfb1fac3e6.PNG)

I understand different versions of npm handle peer dependencies differently.  Wonder if that is perhaps contributing to this issue.  
https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/

[npm-debug-log.txt](https://github.com/Rebilly/ReDoc/files/536240/npm-debug-log.txt)

**Comment by RomanGotsiy** [comment]
@juleux I have fixed the issue
Once I publish new npm release you should be able to install it without issues.

I will let you know here.

BTW: updating to npm3 will resolve the issue too.

**Comment by juleux** [comment]
Thank you for letting me know.  I will hold off on updating npm so I can test your fix when ready.  I am currently using CDN to complete my project – and it is working very well.  

Regards, Julie

**Comment by RomanGotsiy** [comment]
@juleux should work fine now.
Confirm it works for you plz

**Comment by RomanGotsiy** [comment]
Closing this for now.
Feel free to reopen if it doesn't work

**Comment by juleux** [comment]
It’s working for me now.  Thanks for your hard work.
