### ISSUE TITLE
discriminator usage

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#128]
I have successfully added discriminator for the "success" field in a rest api call response. It's wonderful. When the "success" field is "true", a bunch of fields are listed. When the "success" field is "false", the "reasons" field is listed. 
Now I want to add discriminator for other call responses within the same yaml file. For "false" i listed as below, which works well since the fields within "false" field are exactly the same. 

![image](https://cloud.githubusercontent.com/assets/20762285/19682743/9a90688a-9ae1-11e6-8d96-7701f0a9b182.png)

But for "true", i hope to show different fields for different calls. but i find all the fields defined within "true" are listed for different calls. I hope field 1 is only showed for CallA response, field 2 is only showed for CallB response. Is there a way to do that?  Thanks a lot in advance~

My example "true" field is like: 

![image](https://cloud.githubusercontent.com/assets/20762285/19682776/ca041fd0-9ae1-11e6-87f6-84ecd5109a58.png)

**Comment by IvanGoncharov** [comment]
@jenniferwang2000 Bad news you can't implement this behavior in pure Swagger/OpenAPI.

Good news we have a workaround in ReDoc, it vendor extension named `x-extendedDiscriminator`.
It's a hybrid of `discriminator` and `oneOf` keyword from JSON Schema.
Here is Gist with simple example: https://gist.github.com/IvanGoncharov/a62b1dc9324b99a689c31c8411844d09
And [link](http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/IvanGoncharov/a62b1dc9324b99a689c31c8411844d09/raw/16dd94d79f25fc8d597664907d55968d4d3aaf22/extendedDiscriminator.yaml) to ReDoc.

**Important**:  `x-extendedDiscriminator` supported only in ReDoc so any other tolling will simply ignore it. That said absolute majority of tooling doesn't support official `discriminator` in the first place.

**Comment by jenniferwang2000** [comment]
That's really great! I got it working. Thank you so much!
