### ISSUE TITLE
Navigate between code examples - the menu and middle panes scroll to random content

### ISSUE THREAD

**Issue by TracyZuora** [Rebilly/ReDoc#130]
We have code samples in 6 languages, when you navigate between the examples the menu and middle panes scroll to random  content. There seems to be an issue with ReDoc displaying the code samples. When you click on the different language tabs, the screen sometimes jumps around - potentially even to a completely different part of the API Reference. This makes for a pretty bad user experience.

We were able to reproduce the bug by using an example from ReDoc, so we're fairly sure that this issue is caused by ReDoc and is not caused by our yaml file. It might be caused by the length of the code samples, or maybe the number of languages - we are not sure yet. 
Any help is appreciated

**Comment by RomanGotsiy** [comment]
@TracyZuora thanks for reporting.
I can confirm the issue. Will let you know once I manage to fix it

**Comment by RomanGotsiy** [comment]
This issue is fixed in the latest `v1.5.1` release
