### ISSUE TITLE
linking to 

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#138]
Hi ! Love ReDoc - thanks so much!

Not sure if this is the correct place to post.

I'm having trouble using GFM link syntax to link to the heading tag anchors from redoc.  They work the first time clicked but then after the url bar stays sticky to the tag anchor and the link isn't followed the second time you try to click on it.  Perhaps I am just implementing links to redoc header tags the wrong way?

https://andrewjtech123.github.io/rebilly-validschema/#tag/Create

Cheers !

**Comment by RomanGotsiy** [comment]
Unfortunately, this is how url hash works in browsers. If it is not updated during following link - no event is fired :(

I will check if I can do something with this. Will keep this issue open until I manage to investigate this.

------------
btw, If you change [this heading](https://github.com/andrewjtech123/rebilly-validschema/blob/master/spec/swagger.yaml#L6) to the first-level `# Draft Orders API` it will be added to the side menu.

**Comment by andrewjtech123** [comment]
Thanks so much for your response and tip about # Draft Orders API :)

**Comment by andrewjtech123** [comment]
I noticed with readme.io that as you scroll the page the url bar updates automatically as you pass the different headings.  Maybe this approach would be helpful ?

http://docs.nurego.com/v1.0.1/reference#api-introduction

**Comment by RomanGotsiy** [comment]
@andrewjtech123, yes. Thanks for advice. This would be useful feature

**Comment by RomanGotsiy** [comment]
Automatic url bar updates are shipped with the latest version `v1.10.0`

**Comment by jinkrish** [comment]
Is there any option to disable the mentioned above temporarily.
