### ISSUE TITLE
our server does not load spec file 

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#139]
Hello!

I am trying to view our redoc spec with the index.html hosted on our site but it is not rendering.  seems like it can't pull in the swagger.yml file.  any ideas?

<!DOCTYPE html>
<html>
  <head>
    <title>Draft Orders API Specification</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url="https://andrewjtech123.github.io/imagehost/swagger.yml">
    </redoc>
    <script src="//rebilly.github.io/ReDoc/releases/latest/redoc.min.js"> </script>
  </body>
</html>

![draft orders api specification 2016-11-18 15-53-37](https://cloud.githubusercontent.com/assets/6719991/20446392/514745bc-ada7-11e6-9168-cfc58b660cca.png)

**Comment by andrewjtech123** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <title>Draft Orders API Specification</title>
    <!-- needed for adaptive design -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--
    ReDoc uses font options from the parent element
    So override default browser styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url="https://andrewjtech123.github.io/imagehost/swagger.yml">
    </redoc>
    <script src="//rebilly.github.io/ReDoc/releases/latest/redoc.min.js"> </script>
  </body>
</html>
```

**Comment by RomanGotsiy** [comment]
@andrewjtech123  What is printed to browser console?

**Comment by andrewjtech123** [comment]
Hi.  I think we fixed the issue.  Our local jekyll server runs without https.  When I run it locally I have to append https to the url, in order to view the Redoc output correctly.

One other related question - is it possible to tun off the swagger warnings from outputting to redoc?

**Comment by RomanGotsiy** [comment]
Yes - use `suppress-warnings`: [docs](https://github.com/Rebilly/ReDoc#redoc-tag-attributes)

Example:

`<redoc spec-url="..." suppress-warnings></redoc>`

**Comment by RomanGotsiy** [comment]
@andrewjtech123 can this issue be closed?

**Comment by RomanGotsiy** [comment]
@andrewjtech123 closing this issue for now but feel free to reopen in case it is not solved
