### ISSUE TITLE
Use operationId (if specified) field in links for methods

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#14]

**Comment by IvanGoncharov** [comment]
`operationId` is optional field and could be add/removed during spec lifetime.
And people will live links on different 3rd-party sites or as bookmarks in browser.
So if possible it would be great to support both link formats.
To resolve confusion JSON Pointers would be prefixed with `jp/...`.
And methods with `operationId` with `method/...`.

By the way, links to tags also can use similar format: `tag/...`.
