### ISSUE TITLE
help ! pushing to master no longer rebuilds site

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#140]
Hi I think there is an issue with how my site is building.  Normally when I push to master it rebuilds the site but this is no longer happening. 

![gh pages settings](https://cloud.githubusercontent.com/assets/6719991/20495086/ac1bf242-afed-11e6-8137-eca215d0af1b.png)

If I set the above to master then I get a 404 here 

https://andrewjtech123.github.io/rebilly-validschema/

**Comment by RomanGotsiy** [comment]
I've just checked the link and it works for me.
Anyways, it is not related to ReDoc.

**Comment by andrewjtech123** [comment]
sorry for posting this here.  It probably would have made more sense to post in generator-openapi-repo
https://github.com/Rebilly/generator-openapi-repo

**Comment by andrewjtech123** [comment]
but just fyi - I am noticing that pushing to master branch is not triggering a new travis build.  I can manually restart build in travis and it will work

**Comment by RomanGotsiy** [comment]
give me a link to your repo

**Comment by andrewjtech123** [comment]
its working fine now.  Seems like I had to re-install npm at some point
