### ISSUE TITLE
Feature request: Use tags or vendor extension to mark operations with labels as per swagger editor/UI

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#141]
Hi,

We have a need to label our operations with tags to call out certain information.  See image.

Perhaps you can use a vendor extension for this ?  Given the description of `x-traitTag` I was hoping it would work for this

"In Swagger two operations can have multiply tags. This property distinguish between tags that are used to group operations (default) from tags that are used to mark operation with certain trait (true value)"

![not alpha ready](https://cloud.githubusercontent.com/assets/6719991/20524267/b21b7a9c-b087-11e6-911b-dd3527ce1fa6.png)

**Comment by RomanGotsiy** [comment]
@andrewjtech123 ,
`x-traitTag` should actually work for this but the label is very unnoticeable. It is displayed under method name:
![image](https://cloud.githubusercontent.com/assets/3975738/20546447/c96e0200-b11d-11e6-87c8-5926de82a335.png)

Do you have ideas where to move this? Or just make it of some other more contrast color?

**Comment by andrewjtech123** [comment]
for now we used an image embedded in markdown.  You can see it on the calls
marked "To be implemented".  We modeled our design off the way labels look
in the swagger editor output on right panel.

https://andrewjtech123.github.io/rebilly-validschema/

**Comment by andrewjtech123** [comment]
I noticed that it says in your docs that x-traitTag is deprecated ? Does that mean you are removing support for the vendor extension?  We need it for pushing documentation into left navigation such as response codes.

https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-traitTag

**Comment by dolmen** [comment]
In ReDoc the [OpenAPI/Swagger standard `tags`](http://swagger.io/specification/#tagObject) are used for grouping routes in the left panel. This is similar to how tags are used for rendering in swagger-UI, but this is different that in swagger-editor (is that where your screenshot comes from?).

**Comment by RomanGotsiy** [comment]
Closing as out of scope
Feel free to open a new issue!
