### ISSUE TITLE
read only fields appear in JSON request samples for POST request

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#142]
Hi,

For our POST request that creates an object we are passing the object as part of the Body of the request.  The fields for the request body correctly appear in list of body parameters.  However, JSON request example includes read only fields which should not be sent as part of POST request.

![read only fields show up](https://cloud.githubusercontent.com/assets/6719991/20524644/62eb918a-b089-11e6-8c60-7c117d4b1e32.png)

![read only dont show up](https://cloud.githubusercontent.com/assets/6719991/20524649/6963ea1c-b089-11e6-9077-6cd051558096.png)

**Comment by RomanGotsiy** [comment]
Which version of ReDoc you use? This issue should to be fixed since version `v1.5.1`

**Comment by RomanGotsiy** [comment]
@andrewjtech123

**Comment by andrewjtech123** [comment]
I am using https://github.com/Rebilly/generator-openapi-repo for my project here

https://github.com/andrewjtech123/rebilly-validschema

How can i check my version ? Is there a procedure documented somewhere for upgrades?

**Comment by andrewjtech123** [comment]
my script is pointing to latest so it should be working ?

    <script src="//rebilly.github.io/ReDoc/releases/latest/redoc.min.js"> </script>

**Comment by RomanGotsiy** [comment]
@andrewjtech123, I've just checked your docs and can confirm the issue.
Will look into this tomorrow

**Comment by andrewjtech123** [comment]
thank you ! Also root of the object is not displayed.  If user were to copy/paste this into body of a api client request it would fail without the root object of the JSON.

**Comment by RomanGotsiy** [comment]
Fixed now. Will be available with the next release.

**Comment by RomanGotsiy** [comment]
New version `1.6.0` has been released

**Comment by andrewjtech123** [comment]
does this also fix the issue with the root of the object not being displayed?

"Also root of the object is not displayed. If user were to copy/paste this into body of a api client request it would fail without the root object of the JSON."

**Comment by RomanGotsiy** [comment]
no
