### ISSUE TITLE
Feature Request: Theming

### ISSUE THREAD

**Issue by SebastianStehle** [Rebilly/ReDoc#144]
First a big thank you: You solved all my problems I had with Swagger: Swagger UI. Your project is really awesome and I enjoyed to read the source code of such a high quality with a very good code coverage. It just works for me.

I just have one small feature request: I would like to setup some theming properties in the redoc element: The logo and the accent colors would be fine. I can easily fix the colors with css but the logo is a "small" problem, because not all swagger tools support vendor extensions.

**Comment by RomanGotsiy** [comment]
@SebastianStehle thanks for the request.
It will definitely be implemented soon

**Comment by RomanGotsiy** [comment]
The 2.0.0-alpha.x version of ReDoc has theme configuration option which allows configuration of basic theme values.

Closing the issue.
If the new theming is not as good, open separate issues.
Thanks!
