### ISSUE TITLE
filter version number 

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#145]
Can we filter version number from title?  I tried to remove from spec but it is required field.

![version number](https://cloud.githubusercontent.com/assets/6719991/20610653/8e1a63a8-b26a-11e6-939b-4e5f891d34a8.png)

**Comment by RomanGotsiy** [comment]
I will wrap it in a special selector in the next version so you can remove this with css

**Comment by RomanGotsiy** [comment]
Will release a new version in a couple hours in which you will be able to hide version number via css

**Comment by RomanGotsiy** [comment]
@andrewjtech123 Latest version `1.5.2` has been released.

To filter version, just add the following rules to the site style.

```css
redoc .api-info-version {
    display: none;
}
```

You can add this after [this line](https://github.com/andrewjtech123/rebilly-validschema/blob/master/web/index.html#L16)

**Comment by ben-foster-cko** [comment]
How is this achieved in the latest version?

**Comment by katrpilar** [comment]
Using <RedocStandalone> from Redoc version 2.0.0-rc.48 I added this to my main css file which hides it for me.

`.api-content div h1 span {
  display: none !important;
}`
