### ISSUE TITLE
Response get find by id became array

### ISSUE THREAD

**Issue by DaftTrick** [Rebilly/ReDoc#146]
First expand response "200" https://rebilly.github.io/ReDoc/#operation/findPetsByStatus where it must be array.
After expand list https://rebilly.github.io/ReDoc/#operation/getPetById. Response became array to.
![image](https://cloud.githubusercontent.com/assets/6764185/20619959/331544a2-b308-11e6-9e31-a6c4292de4f1.png)

**Comment by RomanGotsiy** [comment]
@DaftTrick, thanks for finding! Will look into this ASAP

**Comment by RomanGotsiy** [comment]
Should be fixed with the latest  `v1.5.2` release.
