### ISSUE TITLE
Graphical glitch in response sample panel

### ISSUE THREAD

**Issue by it-subscriptions** [Rebilly/ReDoc#160]
As seen in the image there is an offset glitch on the right panel, this is present between every endpoint. On version 1.6.1

![redoc display glitch_](https://cloud.githubusercontent.com/assets/20000827/21029680/e59a83ac-bd68-11e6-967b-4a095442362d.jpg)

**Comment by RomanGotsiy** [comment]
@it-subscriptions thanks you. Will look into this ASAP

**Comment by RomanGotsiy** [comment]
@it-subscriptions unfortunately I can't see this on the [demo page](http://rebilly.github.io/ReDoc/)

can you specify more details? Browser version, OS, do you see it on demo too or only on your own setup? If only on yours then provide plz a link.

thank you

**Comment by it-subscriptions** [comment]
I'm on Window 10 x64 Build 14393 on Chrome Version 55.0.2883.75 m.

The demo looks fine on my end, so it seems to really be something with my swagger.
I've attached swagger json as I don't have it hosted anywhere public yet.  My html only has this in the body with no other css.

```
<redoc spec-url="http://localhost:6921/swagger/docs/v1"></redoc>
<script src="https://rebilly.github.io/ReDoc/releases/v1.6.1/redoc.min.js"></script>
```

Looking at the css, if I remove the background attribute, it seems to fix it.

```
.method-samples[_ngcontent-fdb-29] {
    color: #fafbfc;
    width: 40%;
    padding: 40px;
    background: #263238;
}
```

Thanks for looking into it!

[graphical_glitch_swagger.txt](https://github.com/Rebilly/ReDoc/files/642362/graphical_glitch_swagger.txt)

**Comment by RomanGotsiy** [comment]
add please the following CSS to your html:

```
<style>
  body {
    margin: 0;
  }
</style>
```

There is the minimal setup required to not have this glitch issue.
I suggest to use minimal setup `HTML` from README: https://github.com/Rebilly/ReDoc#tldr
