### ISSUE TITLE
Multiple instances of ReDoc on one server

### ISSUE THREAD

**Issue by arodoni** [Rebilly/ReDoc#163]
We are considering a deploying a private API reference for Beta customers and keep that API separate from our public REST API. 

Is it possible to run 2 or more instances of ReDoc on one server? 

Thanks!

**Comment by RomanGotsiy** [comment]
@arodoni yes this is possible.
First of all ReDoc is pure client-side application so it is not run on the server.

The simplest and recommended solution is just to setup 2 different pages each with ReDoc instance pointing to another swagger spec.

Alternatively, ReDoc supports dynamic spec urls as on our [demo page](http://rebilly.github.io/ReDoc/) so you can end up using only one page.

Let me know if I answered your question

**Comment by arodoni** [comment]
Thank you for the quick response! I got it to work with 2 HTML and 2 swagger specs.
