### ISSUE TITLE
ReDoc crashes when linking to a tag that contains spaces

### ISSUE THREAD

**Issue by PJolz** [Rebilly/ReDoc#164]
If you get the link to a tag that contains a space, the link looks like this:
[...]/#tag/Accounting%20Codes

Following the link causes the page to crash with the error:
![2016-12-14_16-25-58](https://cloud.githubusercontent.com/assets/9894341/21174811/4aa76638-c21a-11e6-80a4-006d09ccd588.png)

When linking to a section that contains a space, the space is replaced by a hyphen, so the issue doesn't occur. E.g. [...]/#section/API-Versions

**Comment by RomanGotsiy** [comment]
@PJolz which version of ReDoc you use?
In the latest version `v1.6.2`, spaces in link to tags are replaced with hyphen too.

Let me know if upgrading to the latest version resolves the issue for you.
I will close the issue but feel free to reopen in case it doesn't work
