### ISSUE TITLE
ReDoc doesn't work on Edge

### ISSUE THREAD

**Issue by dvh** [Rebilly/ReDoc#166]
When I try to open a redoc page (e.g. http://rebilly.github.io/ReDoc/) in Microsoft Edge , it won't render: `Object doesn't support property or method 'ToString'`. The version I've tested it on is:

```
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
```

**Comment by RomanGotsiy** [comment]
was caused by https://github.com/jhiesey/stream-http/issues/48
I've updated stream-http to the latest version.

The issue is fixed. It will be available in the upcoming release

**Comment by dvh** [comment]
:+1:
