### ISSUE TITLE
What's the "proper" way to re-initialise redoc element?

### ISSUE THREAD

**Issue by rbywater** [Rebilly/ReDoc#167]
I've been working on a spec viewer which uses ReDoc to render the spec documentation. Basically the page has a list of files and as you select a file from the list, the page dynamically updates to have the documentation of that page without having to refresh the page.

I've found that once you have done a `Redoc.init()`, further attempts fail. So what I've been doing in the meantime is, when I want to refresh the spec being displayed, I replace the Redoc DOM node with a fresh `<redoc/>` tag and that allows `Redoc.init()` to work. This seems to work but there is also a bunch of errors about "Attempt to use a destroyed view" that get spat out into the console. Its not stopping the rendering from actually happening but its always good to keep the console logs clean if posssible.

Therefore is there a more "proper" way of doing a second `Redoc.init()` on a page? Could `Redoc.init()` be changed on subsequent calls to destroy everything and start again?

**Comment by RomanGotsiy** [comment]
@rbywater actually this is a bug. I will fix it for the next release.
It is planned for today

**Comment by RomanGotsiy** [comment]
I will release a new package with the issue fixed in 4-5hours
I will let you know

**Comment by RomanGotsiy** [comment]
@rbywater new version `1.6.3` is available

**Comment by rbywater** [comment]
:+1: Just tried it and no more console errors being thrown as far as I can tell. 

Thanks for the prompt response!
