### ISSUE TITLE
Redoc never compiles locally

### ISSUE THREAD

**Issue by BafFlynN** [Rebilly/ReDoc#168]
I have tried everything, switching node versions altering code. I can not get this to compile locally at all. I always get failed dependencies and if I edit either dist/redoc.js or dist/redoc.min.js the entire thing breaks. (All I am doing is removing the download button and trying to add some more functionality that is needed for my company internally. (I have tried every major version of node and npm from 4.0 & 3.0 upwards). 

I am lost so any direction would be helpful.

**Comment by RomanGotsiy** [comment]
@BafFlynN can you specify more details? Which error do you get? What is printed to console?

What OS you work on?

**Comment by RomanGotsiy** [comment]
@BafFlynN check https://github.com/Rebilly/ReDoc/issues/168. Maybe you had the same issue

**Comment by BafFlynN** [comment]
I was just gonna say, you fixed it :)
