### ISSUE TITLE
Any plans for support xml samples for request/response ?

### ISSUE THREAD

**Issue by it-subscriptions** [Rebilly/ReDoc#171]
If an operation has consumes and/or produces value of application/xml it would be nice to have the samples show accordingly. 

For request I can make a code sample, but ideally it would be auto generated like the JSON. 

As for responses I can't really think of any workaround.

**Comment by RomanGotsiy** [comment]
@it-subscriptions there are no plans to bring auto-generated XML examples in the near future (if nobody would contribute)

But OpenAPI(Swagger) has an [`Example Object`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#example-object) using which you can provide response samples for different mime-types.
Right now only `application/json` is displayed in ReDoc but I can implement displaying `xml` sample if it's present. This should be much cheaper than implementing XML sample generation.

So in the end you will be able to provide request samples using code samples and responses using native swagger response samples .
Would it work for you?

**Comment by it-subscriptions** [comment]
That would be great. Code samples for request is fine with me, so adding support for `application/xml` mime type in responses would work well as a quick solution.

Thanks!

**Comment by RomanGotsiy** [comment]
Closing in favour of #492
