### ISSUE TITLE
Display produces/consumes

### ISSUE THREAD

**Issue by conzett** [Rebilly/ReDoc#172]
It looks like there are no immediate plans to automatically generate different media type representations, but would it would be nice to at least display the available values of produces and consumes if they are set.

**Comment by RomanGotsiy** [comment]
@conzett there is an idea to show only produces/consumes different from `application/json`. What do you think? Would it work for you?

**Comment by conzett** [comment]
@RomanGotsiy I'm looking to show produces/consumes for custom media types and XML so that would work fine for my use case. Is there an issue for that feature request that I can follow? Thanks!

**Comment by jakubneubauer** [comment]
+1, I think this enhancement is quite important. There is no way how to recognize what the result of a call is, if it is not a json - nothing is shown under the response, nor in the example. "produces" can shed light on it.

**Comment by bartfeenstra** [comment]
:+1: for this feature request, as my projects make heavy use of content negotiation. I'd be consistent, though, and simply show all defined content types. There are plenty of different types of endpoints that can be described using Swagger/OpenAPI and that do not consume or produce JSON. Treating one content type different from the others will also cause confusion with users of the ReDoc UI, who will mostly not be familiar with such special-casing.

**Comment by RomanGotsiy** [comment]
consumes/produces are displayed in redoc@2.0.0-alpha.x
