### ISSUE TITLE
Separator/heading between info documentation and endpoint documentation.

### ISSUE THREAD

**Issue by jaingaurav** [Rebilly/ReDoc#174]
Hi, is there any chance that a separator or heading could be created in the side-menu when starting the endpoint documentation? Something like "Appendix"? This will help show when the info documentation sections have ended and the endpoint documentation sections have started.

**Comment by RomanGotsiy** [comment]
Hello @jaingaurav,
I'm currently working on menu-grouping mechanism using which you'll be able to do so.
I will let you know when it is ready

**Comment by jaingaurav** [comment]
Thanks a lot. That'd be great!

**Comment by RomanGotsiy** [comment]
@jaingaurav To achieve what you need you can use [`x-tagGroups`](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-taggroups) root vendor extension which is supported by the latest (`1.7.0`) version of ReDoc.
You can create one group with name `Appendix` and add all tags to this group.

Let me know if this works for you.

**Comment by jaingaurav** [comment]
@RomanGotsiy: That definitely works, thanks for the work.
