### ISSUE TITLE
got error "trackBy must be a function, but received undefined" on SideMenu

### ISSUE THREAD

**Issue by Joe-noh** [Rebilly/ReDoc#176]
Hi, big thank you for great product.

Following this procedure gave me an js error "trackBy must be a function, but received undefined" .

1. fork and clone this repository.
2. then run `npm install`, `npm start`.
3. open `localhost:9000`

This error occurs on `SideMenu` component due to ngForTrackBy only accepts function but [`summary`; one of `method`'s properties is given](https://github.com/Rebilly/ReDoc/blob/77877381a872c21ad1bf39feb4399b8fe989ba9b/lib/components/SideMenu/side-menu.html#L15).

I made [this commit](https://github.com/Joe-noh/ReDoc/commit/c55563cd11ccdc56d085e8c0757d333353a9e7ae) to fix this, but I'm not sure whether this is correct way to fix this. Would you give me an advice if I'm missing something, or should I send a P/R?

**Comment by RomanGotsiy** [comment]
@Joe-noh thanks for reporting. Frankly speaking I'm shocked how it used to work all the time.. According to git history this line was added on Jul 21 O_O....

Thank you for trying to fix that. Your fix is absolutely correct 👍 
But I've been working on menu refactoring last few days on branch `menu-refactor` and as a result of refactor this line with `trackBy` is no longer there. I'm going to merge this branch into master soon so the issue will be resolved.

I'll keep this issue opened until I merge this branch.

Thank you again

**Comment by RomanGotsiy** [comment]
merged
