### ISSUE TITLE
Responses List bugs for duplicate schemas with different codes

### ISSUE THREAD

**Issue by theindexer** [Rebilly/ReDoc#177]
If you reference the same schema but have different status codes (we have a 200 and a 201 that share a response body), weird things happen.  Clicking on the zippy for whichever status code wasn't last in the spec causes it to change to the other code, then expand on the next click.

Problem code appears to be https://github.com/Rebilly/ReDoc/blob/master/lib/components/ResponsesList/responses-list.ts#L45

The returned resp is shared by all the responses and so the last one out will do the final write to status code and boom :(

It seems like a simple clone with 

`Object.assign({}, this.specMgr.byPointer(resp.$ref));`

was enough to fix my issue but haven't really tested or dug around in the code to see if there's a better way.

**Comment by RomanGotsiy** [comment]
@theindexer thanks! simple clone was good solution.
I've already fixed it and added a testcase.
New version release is planned for tomorrow.

**Comment by RomanGotsiy** [comment]
New version `1.7.0` has been released

**Comment by theindexer** [comment]
Sweet, thanks!
