### ISSUE TITLE
Strange request to `example.com` causing CSP error (v1.6 and up)

### ISSUE THREAD

**Issue by omaralqady** [Rebilly/ReDoc#178]
This doesn't occur in v1.5.x, and occurs in v.1.6.x and v.1.7.x.

When using `ReDoc` with content security policy enabled, and the connect sources set to accept certain sources, an error occurs because of a request by `ReDoc` to `example.com`

Error:
> Refused to connect to 'https://example.com/' because it violates the following Content Security Policy directive: "connect-src 'self' ws: wss:".

This doesn't seem to be something that is required for the functionality of `ReDoc`, but the prevention of loading this by CSP triggers an exception and results in a blank page

Error screenshot:
![redoc-err](https://cloud.githubusercontent.com/assets/4840247/21723382/d7ccfa98-d438-11e6-8290-5b65b5de1b5d.png)

**Comment by RomanGotsiy** [comment]
This is an issue of `stream-http`. I've opened corresponding issue there: https://github.com/jhiesey/stream-http/issues/64

**Comment by RomanGotsiy** [comment]
@omaralqady should be fixed on the latest 1.8.0 version
Verify please if this is fixed and reopen the issue if it's not
