### ISSUE TITLE
Code samples in documentation

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#18]
`x-code-samples`

**Comment by adamaltman** [comment]
:yum:

**Comment by RomanGotsiy** [comment]
Implemented

Docs are [here](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-code-samples)
Example of usage is [here](https://github.com/Rebilly/ReDoc/blob/master/demo/swagger.yml#L112)
Live demo is [here](http://rebilly.github.io/ReDoc/#pet/paths/~1pet/post)

**Comment by adamaltman** [comment]
:+1:
