### ISSUE TITLE
Boolean type default value shows as true even when set default=false

### ISSUE THREAD

**Issue by ezcoding4all** [Rebilly/ReDoc#183]
For type boolean, default value is not shows instead values always showed as true in REQUEST/RESPONSE Example section

```javascript
"isTest": {
    "type": "boolean",
    "default": false
 }
```

**Comment by RomanGotsiy** [comment]
@ezcoding4all which version of ReDoc you use?
This issues is fixed in the latest ReDoc version.

Check out on our demo page: http://rebilly.github.io/ReDoc/#operation/placeOrder

**Comment by ezcoding4all** [comment]
@RomanGotsiy,

I am using 1.2.0
