### ISSUE TITLE
LOW: CSS: request body model-tree wrapping problem

### ISSUE THREAD

**Issue by hlubovac** [Rebilly/ReDoc#185]
![image](https://cloud.githubusercontent.com/assets/3127736/22258079/6e55c82c-e21d-11e6-8f92-6af4594854fa.png)

This fixed the problem for me:
```
.param-type[_ngcontent-redoc-11] {
    word-break: break-all;
}
```
![image](https://cloud.githubusercontent.com/assets/3127736/22258068/6034a6fa-e21d-11e6-9220-d680f0286e9b.png)

**Comment by RomanGotsiy** [comment]
@hlubovac thanks for reporting.
Will fix in the next release
