### ISSUE TITLE
use of discriminator field is broken

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#195]
we have been using discriminator field to indicate custom vs. regular object (with different attributes and required fields depending on how discriminator is set (true or false).  This functionality is now broken.

![descriminator](https://cloud.githubusercontent.com/assets/6719991/22531046/b46c86c6-e8ac-11e6-9986-a91872e135ac.png)

not possible to select true or false any longer from the dropdown.

**Comment by RomanGotsiy** [comment]
@andrewjtech123 discriminator is not broken in ReDoc. Your spec is invalid.

You use `discriminator` incorrectly:
> The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. The property name used MUST be defined at this schema and it MUST be in the required property list. When used, the value MUST be the name of this schema or any schema that inherits it.

If you want to have `true` and `false` in `discriminator` you have to have definitions with the same name. I can't see such definitions in your spec.
Also discriminator field technically must be `string` as it `MUST be the NAME of this schema or any schema that inherits it.`

Having top-level definition with name `true` is an ugly idea but It's just how OpenAPI/Swagger `discriminator` works.
To fix this issue, I have implemented special vendor extension BUT you should understand that only ReDoc will use it.
It is not documented yet. Let me know if you are interested in this so I can document.
I am closing this issue. But you are welcome to post your questions here

**Comment by andrewjtech123** [comment]
Hi @RomanGotsiy yes I would be very interested in the vendor extension.  I was never happy with the way i "hacked" the spec to do this, so I'm not surprised that it stopped working.

**Comment by andrewjtech123** [comment]
hay @RomanGotsiy is there a link or some info you can send me on this ? we have a public beta starting soon and I need to get the fix in

**Comment by RomanGotsiy** [comment]
Here is example spec using this vendor extension: this: https://apis-guru.slack.com/files/ivan/F2TS1N32P/extendedDiscriminator_yaml.yaml

Would be great If you manage to get guts out of it yourself. I don't have time today to document this detailed.
I'm going to document till the end of the week though

**Comment by RomanGotsiy** [comment]
@andrewjtech123 updated previous post with a correct link

**Comment by RomanGotsiy** [comment]
hey @andrewjtech123, did you manage to hack the spec as you needed using that vendor-extension ?

**Comment by andrewjtech123** [comment]
hi @RomanGotsiy . I was able to play around with discriminator to get it to do something that works for now. latest version in the repo should have it.  Thanks for checking in ! https://andrewjtech123.github.io/rebilly-validschema/

**Comment by RomanGotsiy** [comment]
Great. I'm glad you managed to get that working. I've seen you published it as a public beta on Shopify docs 🎉 

I will let you know once I'm done with documenting `x-extendedDiscriminator`

**Comment by RomanGotsiy** [comment]
Hey @andrewjtech123,
I'm just done with documenting `x-extendedDiscriminator`.

Hope it will be helpful:
https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-extendeddiscriminator
