### ISSUE TITLE
hide-hostname option adds a slash

### ISSUE THREAD

**Issue by dolmen** [Rebilly/ReDoc#201]
When the `hide-hostname` option is used I expect that `http://host/path` is shown as `/path`. But currently the there is an additional `/` in front in a different color: `//path`.

Note : my spec has `host` and `schemes` set, but not `basePath` (because all API path are relative to root). I suspect that an incorrect basePath (`"/"` instead of `""`) is injected.

**Comment by RomanGotsiy** [comment]
Fixed in v1.8.1
