### ISSUE TITLE
JSON response samples are quoted

### ISSUE THREAD

**Issue by davidkuridza** [Rebilly/ReDoc#205]
We have a spec with custom JSON response examples defined for every path, something like this:

```yaml
swagger: '2.0'

info:
  version: 1.2.3
  title: API Title
  description: API description

host: api.example.com

paths:
  /:
    get:
      summary: Awesome endpoint.
      responses:
          200:
            description: Returns something.
            schema:
              properties:
                version:
                  type: object
            examples:
              application/json: |-
                {
                  "foo": "bar"
                }
```

When rendered, all of the examples are quoted:

![screen shot 2017-02-14 at 08 27 31](https://cloud.githubusercontent.com/assets/953796/22919317/77241472-f28f-11e6-9aaf-a0960e072d43.png)

Is there a way to remove the quotes?

**Comment by RomanGotsiy** [comment]
@davidkuridza `|-` in yaml [means string](http://stackoverflow.com/questions/15540635/what-is-the-use-of-pipe-symbol-in-yaml). That's why they are quoted.

To remove quotation just specify object instead of string:

```yaml
examples:
    application/json:
        foo: bar
```

**Comment by meloning** [comment]
Hello, I also encountered the same issue.

[Version]
- SpringBoot: `2.7.14`
- ePagesRestDocs: `0.16.4`

I configured it as shown below in Gradle's Task to remove the Literal Block Scalar, and it resolved the problem.

```kotlin
tasks.register("removeBlockScalarsFromYaml") {
        doLast {
            val inputFile = File("${project.buildDir}/api-spec/incomplete_openapi3.yaml")
            val outputFile = File("${project.buildDir}/api-spec/openapi3.yaml")

            val yamlData = inputFile.readText()

            val cleanedYamlData = yamlData.replace(Regex("\\|-"), "")

            outputFile.writeText(cleanedYamlData)
        }
    }
```

I hope this can be helpful for people facing the same issue as mine.
