### ISSUE TITLE
Ellipsis class content is garbled

### ISSUE THREAD

**Issue by sarus** [Rebilly/ReDoc#213]
I'm seeing garbled content for the `.ellipsis` class when the tree is collapsed.

![image](https://cloud.githubusercontent.com/assets/306319/23368214/198c3a3c-fcdb-11e6-9d59-325d16f8c1c9.png)

Inspector Content:

![image](https://cloud.githubusercontent.com/assets/306319/23368262/4070f386-fcdb-11e6-8a69-efbecb57d060.png)

Has anyone run into this issue?

Thanks!

**Comment by sarus** [comment]
Just needed to add `UTF-8` charset as a `meta` tag in `head`

```
<meta charset="utf-8"/>
```

I would consider adding this to the sample `index.html` file in the README.

Thanks!

**Comment by RomanGotsiy** [comment]
@sarus dup of https://github.com/Rebilly/ReDoc/issues/29

**Comment by RomanGotsiy** [comment]
@sarus nice catch with `<meta charset="utf-8">`.
Adding to sample `index.html`
Thanks

**Comment by raubel** [comment]
For information, it may not be enough to add `<meta charset="utf-8">` in the page. The response header can override this setting.
In my case, the `index.html` page is served by a Java servlet, and I need to set the response encoding explicitly (`response.setCharacterEncoding("UTF-8")`).
