### ISSUE TITLE
Markdown in description

### ISSUE THREAD

**Issue by runes83** [Rebilly/ReDoc#214]
In your demo: http://rebilly.github.io/ReDoc/ you have markdown in the description field and manage to create additional menu items by markdown headlines. I try to recreate that but are not able to get the same result. Is there any special thing that have to be set? 

Are using json not yaml

**Comment by RomanGotsiy** [comment]
@runes83 probably you're missing some `\n` or spaces according to markdown spec.

Send me a sample of your swagger and I will try to help

**Comment by runes83** [comment]
Tried using your example text but still error, here is the swagger:

https://gist.github.com/runes83/35579c4faf28a9f765c3afaab28a8a9e

**Comment by RomanGotsiy** [comment]
I can't see markdown headers in your description field

They should start from `#` sign.

check example here: https://github.com/Rebilly/ReDoc/blob/master/demo/swagger.yaml#L8

**Comment by runes83** [comment]
@RomanGotsiy I've updated the gist with your petstore markdown and still the same result

**Comment by runes83** [comment]
![redoc](https://cloud.githubusercontent.com/assets/7079276/23399887/3c61c9ba-fda2-11e6-9634-eda04e8a3599.PNG)
Here is a screenshot of what it looks like

**Comment by RomanGotsiy** [comment]
Now you have extra spaces before your text which mean code block in markdown.

Please validate your markdown in any markdown editor, e.g. https://stackedit.io/editor

**Comment by RomanGotsiy** [comment]
@runes83 here is the working gist: https://gist.github.com/RomanGotsiy/d700746a48964a63610435e572319ae1

**Comment by runes83** [comment]
@RomanGotsiy Thanks it look like Swaschbuckle dis somthing to the markdown it works now :-)
