### ISSUE TITLE
Bug: Redoc shows spinner only when swagger definition is empty

### ISSUE THREAD

**Issue by SebastianStehle** [Rebilly/ReDoc#216]
Hi, 

I found a minor bug. When the swagger definition is empty, Redoc only shows the spinner. I have an API where you can enable and disable API's and it would be awesome if Redoc will be also rendered if no API is enabled.

**Comment by RomanGotsiy** [comment]
What you mean under the swagger definition empty?
Can you please open browser console and send the output?

**Comment by SebastianStehle** [comment]
There is nothing in the console. With and empty definition I mean a swagger definition without any paths.

**Comment by RomanGotsiy** [comment]
@SebastianStehle nice catch, thanks for reporting.
Will fix in the upcoming release

**Comment by SebastianStehle** [comment]
Awesome, do you have a timeline for the next release? we would like to release a product/open source project and it would be nice to bring it out with this fix.
