### ISSUE TITLE
https://github.com/Rebilly/ReDoc/releases/latest points to v0.7.14

### ISSUE THREAD

**Issue by tanel** [Rebilly/ReDoc#222]
Would it be possible to make it point to the actual latest release instead?

I'm using https://goswagger.io/ to generate swagger UI from Go code. It serves the UI using 

<script src="https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js"/>

which points to v0.7.14 which is almost 1 year old release.

**Comment by RomanGotsiy** [comment]
@tanel I can't verify this.
I just opened the link you sent https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js and I see the latest version 1.10.2

![image](https://cloud.githubusercontent.com/assets/3975738/23580422/329eecb2-010a-11e7-8895-147829bd5e0e.png)

**Comment by tanel** [comment]
I cannot reproduce the issue anymore. Looks like I mixed up something. Sorry about this.
