### ISSUE TITLE
How to provide multiple swagger files to ReDoc

### ISSUE THREAD

**Issue by prverma3** [Rebilly/ReDoc#226]
Hi Expert,
I am planning to use ReDoc for api doc generation.  I am very new to ReDoc.  I was able to run ReDoc with single swagger file. Is there any way to provide multiple swagger files to ReDoc?

In case, if  providing multiple swagger files to ReDoc is not possible, Could you please recommend a tool which works best in aggregating/merging multiple swagger files into one (for ReDoc). 

Thanks in advance.

**Comment by prverma3** [comment]
Hi Experts,

Did you get a chance to go through my question.

Thanks in advance for your reply.

**Comment by RomanGotsiy** [comment]
@prverma3 what do you mean under `multiple swagger files`. Redoc supports references so you can use `$ref` to split your file into chunks.
If you want to use ReDoc with completely different swagger files then you probably should use `Redoc.init` ([docs](https://github.com/Rebilly/ReDoc#advanced-usage)) method.

If you are new to swagger I recommend you our another tool: [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo). It will help you to setup your repo.

**Comment by prverma3** [comment]
Many Thanks for your reply.

Actually with multiple swaggers files i was referring to multiple swaggers files of different sub projects.

The Redoc.init seems to take only single swagger spec at the time. Can you recommend any tool to merge multiple swagger files and generate a single merged swagger file . So that, we can use that  single merged swagger file in ReDoc.init.

Thanks in advance for your reply.

**Comment by RomanGotsiy** [comment]
@prverma3 Check out the sample of how to use multiple swagger files with redoc: https://github.com/Rebilly/ReDoc/blob/master/demo/examples/multiple-apis/index.html

Hope it would be useful.

Regarding merging swagger files - I do not know about tools for merging multiple swagger files into one. Maybe stackoveflow would be better place to ask this question.

Closing this issue

**Comment by prverma3** [comment]
Many Thanks . 
Your link was very useful. Just one more question, is there any way to show the  multiple APIs links in first panel (left most) instead of showing it in top panel.

Thanks in advance.

**Comment by RomanGotsiy** [comment]
@prverma3 so far there are no such option. It may be added as part of https://github.com/Rebilly/ReDoc/issues/181 feature request but I don't have timeline for this so foar

**Comment by shahamit** [comment]
@RomanGotsiy - I need the capability discussed on this thread but the [sample ](https://github.com/Rebilly/ReDoc/blob/master/demo/examples/multiple-apis/index.html)referenced in this discussion in no more active. Could someone share an example of multiple api's?

**Comment by areebaasad77** [comment]
Hello. The link shared above regarding how to use multiple swagger files with redoc is no longer working. Could you please share a working link? I would like to know how to use multiple swagger files also

**Comment by guilhermegambetti** [comment]
I hope this helps @shahamit and @areebaasad77 

https://github.com/Rebilly/ReDoc/blob/039bbdb585f92a7e7c5d38ea5776c42d5d39480e/demo/examples/multiple-apis/index.html

**Comment by rushang7** [comment]
Hello,
In the example of "ReDoc Demo: Multiple apis". (https://github.com/Rebilly/ReDoc/blob/039bbdb585f92a7e7c5d38ea5776c42d5d39480e/demo/examples/multiple-apis/index.html)

Is it possible to put the 'api.name' in the url, so that we can share a url which can directly open particular api?

Thanks in advance.

**Comment by volbrene** [comment]
For everyone how use docker: I have written a Docker Image for that problem. Based on react: https://hub.docker.com/r/volbrene/redoc
