### ISSUE TITLE
Try it now / Change parameter value?

### ISSUE THREAD

**Issue by JFCote** [Rebilly/ReDoc#233]
Hi!

This swagger UI is amazing but I don't know if it's a problem of setup or something, but I can't find a way to:

- Change the value of each parameters
- Click on something like "Try it out!".

Since it's the primary goal of any API browser/documentation, I'm pretty sure I'm missing something or an options somewhere.

I have created the setup using the sample html page and the CDN version "latest".

Thanks!

**Comment by RomanGotsiy** [comment]
this is not swagger UI and not a fork of swagger UI. This is a separate tool developed from the ground.

The support for "Try it out" is still not implemented but it is in the our roadmap.
Track the progress in the issue: https://github.com/Rebilly/ReDoc/issues/53

**Comment by JFCote** [comment]
Ok thanks for the information! I'll keep an eye on the issue #53 .
Keep up the good work man!

**Comment by wll8** [comment]
Try [redoc-try](https://github.com/wll8/redoc-try), use `swagger Try it out` in` redoc` project.

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_WX20200518-152825.png)
