### ISSUE TITLE
Getting x-code-samples to work

### ISSUE THREAD

**Issue by squashvoice** [Rebilly/ReDoc#237]
Firstly, great project and thank you for all the hard work!

I followed the "TL;DR" steps, using the same `index.html`, with CDN-hosted `redoc.min.js`. When coupling this with the demo `swagger.yaml` I can see that everything works fine except for vendor extension features such as `x-code-samples`.

Could you confirm if there are additional libraries/steps I've missed in order to get these to work?

Thanks!

**Comment by RomanGotsiy** [comment]
@squashvoice what you mean under `x-code-samples` are not working? There should not be any additional steps

**Comment by squashvoice** [comment]
@RomanGotsiy sorry for wasting your time, I found out that swagger-node doesn't send through vendor extensions by default. I fixed the issue by following this case:

https://github.com/swagger-api/swagger-node/issues/441

Thanks!
