### ISSUE TITLE
Need urgent help

### ISSUE THREAD

**Issue by prverma3** [Rebilly/ReDoc#238]
Hi Experts,

I am facing a strange issue. I am able to render ReDoc for my api in chrome, firefox and safari but in case of IE 9,  I am getting blank screen. Do you have any idea what can be wrong here?

Thanks in advance for your help.

**Comment by RomanGotsiy** [comment]
@prverma3 ReDoc doesn't support IE9. And there are no plans to support it since even Microsoft stopped supporting it.
