### ISSUE TITLE
Allow display of multiple swagger files in the left pane?

### ISSUE THREAD

**Issue by gauravmokhasi** [Rebilly/ReDoc#239]
Can we display more than one swagger file in the left pane itself, instead of in the top bar?
- In the left pane, you will have multiple API families -- like Students, Teachers, Non-Teaching Staff etc...
- when you click on Students, it will load the students-swagger.yaml (or .json) and display it in 3 panels.
  - The other 2 families will remain collapsed.
- When you click on Teachers, it will load teachers-swagger.yaml (or .json) which will replace the old UI.
  - Students will get collapsed in the left pane, while Teachers expands to show the modules under it.

*Example Levels in the Left Pane when students-swagger.yaml is loaded:*
- Students
  - Grade
     - Get Grade
     - Set Grade
  - Class
- Teachers
- NonTeachingStaff

We don't want to combine the different API families into a single swagger, as each has their own endpoint. We also want the user to be able to download the particular swagger (e.g. teachers-swagger.yaml) by clicking on the "download" button.

**Comment by RomanGotsiy** [comment]
@gauravmokhasi 
No, this is not supported by ReDoc and there are not plans to support it
Instead you can have your families shown in the navbar. Here is the example of that: https://github.com/Rebilly/ReDoc/blob/master/demo/examples/multiple-apis/index.html

**Comment by guilhermegambetti** [comment]
The link above doesn't work anymore, please refer to the following link
https://github.com/Rebilly/ReDoc/blob/039bbdb585f92a7e7c5d38ea5776c42d5d39480e/demo/examples/multiple-apis/index.html
