### ISSUE TITLE
Provide versioning support for APIs?

### ISSUE THREAD

**Issue by gauravmokhasi** [Rebilly/ReDoc#240]
Can we support multiple versions of APIs?
- Provide a dropdown to select the correct version (perhaps next to the download button).
- Based on the version selected, the correct swagger is loaded.
  - e.g. if v2 is selected, then teachers-swagger-v2.yaml will be loaded and displayed in the 3 panels.
- provide option to mark certain versions as deprecated. (so that you can continue to display deprecated versions instead of removing them from the documentation altogether)

Is there some way to already do this?

**Comment by RomanGotsiy** [comment]
@gauravmokhasi you can have any switcher outside the redoc and use `Redoc.init` method to switch files.
Check example here: https://github.com/Rebilly/ReDoc/blob/master/demo/examples/multiple-apis/index.html

There is no plan to add this into ReDoc core.

**Comment by Shehzad777** [comment]
Thanks. @RomanHotsiy, but this only shows the first API and no option to select the other versions. Please assist.

**Comment by handhikadj** [comment]
please provide this on the next major version
