### ISSUE TITLE
https spec is loaded via http

### ISSUE THREAD

**Issue by SSANSH** [Rebilly/ReDoc#243]
its seems that Redoc fetch swagger without cors header? can you please confirm? 

please let me know if they have an redoc option in order to add header on request.

Fetch API cannot load http://x.com/docs. Redirect from 'x.com/docs' to 'https://x.com/docs' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.244.129:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by RomanGotsiy** [comment]
> No 'Access-Control-Allow-Origin' header is present on the requested resource

that means requested resource (server) doesn't return `Access-Control-Allow-Origin` header. This is a question to the `http://x.com` resource owner not to ReDoc.

**Comment by SSANSH** [comment]
in fact on http server I don't have Access control because http server just redirect to https server which provide access control.
I don't know how to retrieve a swagger file on https directly with redoc.
Even if I specify https on my code, redoc fetch document with http.

var apis = [
        {
          name: 'api boilerplate',
          url: 'https://x.com'
}
}

**Comment by RomanGotsiy** [comment]
@SSANSH thanks for clarification

**Comment by RomanGotsiy** [comment]
caused by https://github.com/substack/https-browserify/issues/6
