### ISSUE TITLE
Problem with rendering referenced regex pattern

### ISSUE THREAD

**Issue by gyszalai** [Rebilly/ReDoc#245]
I have the following property definition in one of my response schemas:
```json
    "myProperty": {
        "type": "string",
        "description": "Some description",
        "pattern": { "$ref": "#/patterns/uuid" }
    }
```
The pattern definition is the following: 
```json
    "patterns": {
        "uuid": "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
    }
```

It is rendered as:

![image](https://cloud.githubusercontent.com/assets/1856456/24659050/d9c40136-194b-11e7-878a-ce0b36056b92.png)

It is interesting though, that if the same reference is put into 
a request body schema, it is rendered correctly.

**Comment by RomanGotsiy** [comment]
You can't reference patterns. This is not valid according to swagger spec.
You can fix it on your side by some preprocessing step.
