### ISSUE TITLE
Overlapping markdown code blocks in lists

### ISSUE THREAD

**Issue by bpaczkowski** [Rebilly/ReDoc#248]
Markdown code blocks seem to be overlapping when they are used within lists:

![screenshot_20170412_193123](https://cloud.githubusercontent.com/assets/1371800/24971007/a31c6a9e-1fb6-11e7-96f7-262bb4cbe2a7.png)

Written in markdown:
```markdown
- `abc`
- `defg`
- `hjklm`
```

**Comment by RomanGotsiy** [comment]
fixed in the latest release
