### ISSUE TITLE
Support for custom methods

### ISSUE THREAD

**Issue by avkonst** [Rebilly/ReDoc#249]
I have got an API which supports custom methods in addition to POST/PUT/GET/DELETE. I list them in the specification, but the tool does not render the documentation for them. Is it by design? Would it be possible to allow any method names?

**Comment by RomanGotsiy** [comment]
@avkonst this is not supported by OpenAPI spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object

**Comment by avkonst** [comment]
Yes, OpenAPI supports only fixed set, unfortunately. ReDoc could be agnostic to method name.

**Comment by RomanGotsiy** [comment]
[`Path Item`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object) Object in OpenAPI may have `$ref` and `parameters` besides operations with different semantic. Also it can contain any vendor extension fields (`x-` fields). So how should ReDoc distinguish if `x-get` is method name or some vendor extension with some other meaning.

**Comment by avkonst** [comment]
Thanks for replying. I suppose if a field is not '$ref', is not 'parameters' and is does not start with 'x-', it is a method name.

**Comment by MikeRalphson** [comment]
`summary` and `description` should be reserved also for future compatibility with OpenAPI 3.0.x

**Comment by avkonst** [comment]
Just letting you know that I worked around implementation of my API by avoiding custom methods. If you think this feature is useful, keep it. Otherwise, we may cancel it.

**Comment by RomanGotsiy** [comment]
@avkonst great you did that. Custom methods in your spec would lead to issues with any other swagger-tooling.
Closing this issue.
