### ISSUE TITLE
Search function behavior

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#251]
We just upgraded to ReDoc 1.11.0 and found a couple of new fancy features, such as search, and multiple instances on one page. Thanks a lot. 

We tried out the Search function and found out some issues about it: 

- If a search term partially matches the initial several letters of a tag heading, the text after the highlighted match begins with a capital letter. For example, if you search "sto", the Store heading is highlighted and changes to StoRe.

- Some search results are not highlighted. If you search "status", the search result in "Update an existing pet", "Find pet by ID", and "Find pet by tags", etc are not highlighted. 

- The returned item doesn't contain the search keyword. If you search "inventories", the search result "Add a new pet to the store" actually doesn't contain this keyword.

- Some items that contain the search keyword are not listed.

Could you please help look into it?

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 thanks for detailed description.
I will look into it ASAP. Most likely at the end of the next week.

**Comment by jenniferwang2000** [comment]
Thank you!

**Comment by RomanGotsiy** [comment]
Should be not an issue with redoc@2.0.0-alpha.x
