### ISSUE TITLE
URL changes so fast

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#252]
We are running on ReDoc 1.11.0, and our YAML contains more than 200 operations. https://www.zuora.com/developer/api-reference/

- When Clicking the paperclip icon next to a heading, the # part of the URL changes very rapidly then become blank. 

- Scrolling can be slow because the URL (# part) has to rapidly change, stepping through all the sections in the page. Could you build in some delay, so that the URL only updates when the section has not changed after a couple of seconds? 

- Following a direct link to a tag, sometimes redirects to the preceding operation. For example https://www.zuora.com/developer/api-reference/#tag/Mass-Updater.

**Comment by RomanGotsiy** [comment]
The first issue you're facing is fixed in the latest version.
Could you please update to the latest and verify that other issues are still reproducible there?

**Comment by jenniferwang2000** [comment]
We update to the latest Redoc version in our test environment. 

- The first one is fixed. Great!

- The second one: when you use cmd+F to search for a word, if the two search results are in two very far sections. the URL changes very rapidly. Could the URL directly change to the destinated section? The URL also changes very rapidly if you drag the scroll button on the right panel. 

- The third one: it directs to the correct URL, but sometimes the section is on top, sometimes it's at the bottom of the page. A little bit weird.

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 thanks for detailed description. Will look into it next week.
