### ISSUE TITLE
Wrong color in inline Markdown code blocks

### ISSUE THREAD

**Issue by bartkummel** [Rebilly/ReDoc#255]
When I put a markdown code block in any **description** field, I get a nice code block with black background. However, the default foreground color is red, probably inherited from the inline code that is red too. Red on black is not very readable. Even worse, the color combinations get very ugly when syntax coloring kicks in. Please set the foreground color for code blocks to some white/grey-ish color. ;-)

**Comment by RomanGotsiy** [comment]
Will publish a new release in 1-2 days
