### ISSUE TITLE
$ref resolved only for first request

### ISSUE THREAD

**Issue by devnewton** [Rebilly/ReDoc#256]
I have two requests with an $ref description in my swagger file, only the first one is resolved:

https://taab.bci.im/docs/swagger.yaml
https://taab.bci.im/docs/swagger.html

**Comment by RomanGotsiy** [comment]
`$ref` are not allowed in `description` field according to [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject). `description` should be of type `string`:

![image](https://cloud.githubusercontent.com/assets/3975738/25314353/faa7e684-284a-11e7-9a43-d23b1d4b0302.png)
