### ISSUE TITLE
Discriminator support in nested object 

### ISSUE THREAD

**Issue by gprDalenys** [Rebilly/ReDoc#258]
Hello, 

We would like to use a discriminator, but having it in a nested object.
Here is an example, base on Petstore.

```
swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Pet'
definitions:
  Pet:
    required:
      - name
    type: object
    properties:
      name:
        type: string
      special:
        allOf:
          - $ref: '#/definitions/Special'
  Special:
    type: object
    discriminator: pet_type
    properties:
      pet_type:
        type: string

  Cat:
    allOf:
      - $ref: '#/definitions/Special'
      - type: object
        properties:
          cat_exclusive:
            type: string
  Dog:
    allOf:
      - $ref: '#/definitions/Special'
      - type: object
        properties:
          dog_exclusive:
            type: string
```

[example rendered by Redoc](http://i.imgur.com/bXpBTpr.png)

What is the correct usage for our case ? Our current yaml seems valide (according to swagger validate &  
swagger-tools validate), but Redoc doesn't seems to support it (discriminator's dropbox isn't rendered).

Thanks in advance, 

GPR.

**Comment by RomanGotsiy** [comment]
Change `Pet` definition to this (remove `allOf`) and it will work:

```yaml
Pet:
    required:
      - name
    type: object
    properties:
      name:
        type: string
      special:
        $ref: '#/definitions/Special'
```

![image](https://cloud.githubusercontent.com/assets/3975738/25341804/be15b39a-2912-11e7-9b29-b0f34a6cf041.png)

This is some issue in ReDoc, but I will not fix it as I am going to rewrite this part of code soon + it can be workarounded.

**Comment by samlinbris** [comment]
Hi @RomanGotsiy,

Unfortunately doing what you recommended didn't work.

I'm getting a `Cannot read property 'allOf' of null`

Here's my yaml example

```yaml
/pets:
    get:
      responses:
        200:
          description: default response
          schema:
            $ref: '#/definitions/Pet'
        400:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'


definitions:
 Pet:
    required:
      - name
    type: object
    properties:
      name:
        type: string
      special:
        $ref: '#/definitions/Special'

  Special:
    type: object
    discriminator: pet_type
    properties:
      pet_type:
        type: string

  Cat:
    $ref: '#/definitions/Special'
    type: object
    properties:
      cat_exclusive:
        type: string
  Dog:
    $ref: '#/definitions/Special'
    type: object
    properties:
      dog_exclusive:
        type: string

```

**Comment by RomanGotsiy** [comment]
You should have only removed `allOf` from `Pet` definition, not from all the definitions.

Here is the working sample:

```yaml
definitions:
  Pet:
    required:
      - name
    type: object
    properties:
      name:
        type: string
      special:
        $ref: '#/definitions/Special'
  Special:
    type: object
    discriminator: pet_type
    properties:
      pet_type:
        type: string

  Cat:
    allOf:
      - $ref: '#/definitions/Special'
      - type: object
        properties:
          cat_exclusive:
            type: string
  Dog:
    allOf:
      - $ref: '#/definitions/Special'
      - type: object
        properties:
          dog_exclusive:
            type: string
```

**Comment by samlinbris** [comment]
Hi @RomanGotsiy,

Thanks for your prompt response. I have changed to use your sample, however, I'm still getting the same error. Just checking you're also testing this with the latest redoc - `"https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js"`? with swagger version `swagger: '2.0'` ?

Thanks,

**Comment by RomanGotsiy** [comment]
@samlinbris,
I have make up a gist with working spec: [here](https://gist.githubusercontent.com/RomanGotsiy/12eb25618391220779bd12b2169ed4ff/raw/5441b0970611b641cd6bbced65b83f614552ceec/discriminator-sample.yaml)

It works fine for me ont the latest redoc version. Check it yourself in the [demo](http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/RomanGotsiy/12eb25618391220779bd12b2169ed4ff/raw/5441b0970611b641cd6bbced65b83f614552ceec/discriminator-sample.yaml)

It looks like this for me: 
![discriminator-wroking](https://cloud.githubusercontent.com/assets/3975738/25836230/c619e74c-348d-11e7-8094-34444edf4958.gif)

**Comment by samlinbris** [comment]
Hi @RomanGotsiy,

I can confirm it's working, the reason of why it wasn't working before was because I had definitions that weren't filled out. e.g - 

```
automations_id:
    type: string
    description: Unique identifier of an automation
    example: "523e0384-3d03-4fd8-8945-6ffac7241a4d"

  automations_event:

  automations_roles:

  automations_owned_by_user:

  automations_created_at:

  automations_updated_at:
```

Thanks! 👍
