### ISSUE TITLE
Show title on discriminator dropdown

### ISSUE THREAD

**Issue by javierRobledo** [Rebilly/ReDoc#260]
The dropdown for discriminator ignores the title attribute and shows the name of the schema object instead.

For example, given the following definition:
```
definitions:
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType
  CatItem:
    description: A representation of a cat
    title: Cat
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        huntingSkill:
          type: string
          description: The measured skill for hunting
          default: lazy
          enum:
          - clueless
          - lazy
          - adventurous
          - aggressive
      required:
      - huntingSkill
  DogItems:
    description: A representation of a dog
    title: Dog
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        packSize:
          type: integer
          format: int32
          description: the size of the pack the dog is from
          default: 0
          minimum: 0
      required:
      - packSize
```
The dropdown shows CatItems and DogItems instead of Cat and Dog. I've also tried to use the title attribute after type:object, with same results.

It would be great to customize what it's shown basing on title, because it's more flexible than the name of the schema (the title doesn't have to be unique)

**Comment by RomanGotsiy** [comment]
@javierRobledo the key point here is that the name of the schema object is the value of the discriminator field ([spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism)):

> The value of the chosen property has to be the friendly name given to the model under the definitions property. As such, inline schema definitions, which do not have a given id, cannot be used in polymorphism.

So changing this value with `title` field is not correct

**Comment by javierRobledo** [comment]
Hmmm, the problem we're facing here is that we have multiple objects that use similar values for discriminator field, but with different schemas. As the schema name must be unique we had to define multiple schema objects suffixed with a qualifier. That's not a problem with the schema itself, but when we don't want to use the suffixed value on the discriminator type, instead, we prefer to use the field without a suffix, because it looks weird using the suffixed version because of the openapi schema limitation.

Our problem is similar to this definition:
```
definitions:
  Query:
    type: object
    discriminator: queryType
    properties:
      queryType:
        type:string
    required:
      - queryType
  DogQuery:
    allOf:
      - $ref: '#/definitions/Query'
      - type: object
        properties:
          race:      
            type: string
  CatQuery:
    allOf:
      - $ref: '#/definitions/Query'
      - type: object
        properties:
          name:      
            type: string
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType
  CatPet:
    description: A representation of a cat
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        huntingSkill:
          type: string
          description: The measured skill for hunting
          default: lazy
          enum:
          - clueless
          - lazy
          - adventurous
          - aggressive
      required:
      - huntingSkill
  DogPet:
    description: A representation of a dog
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        packSize:
          type: integer
          format: int32
          description: the size of the pack the dog is from
          default: 0
          minimum: 0
      required:
      - packSize
```
With that definition, we don't want to use catPet/dogPet nor catQuery/dogQuery as discriminators, we want to use cat/dog in both cases. But I guess that's not possible with the openapi specification. 

Thanks for the fast reply!

**Comment by RomanGotsiy** [comment]
@javierRobledo you are not the only one who experience the issue with discriminator.
That's why ReDoc supports special vendor extension `x-extendedDiscriminator`. You can find [docs here](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-extendeddiscriminator)

**Comment by RomanGotsiy** [comment]
@javierRobledo I'm closing this issue.
Let me know if you `x-extendedDiscriminator` worked for you.

**Comment by javierRobledo** [comment]
Sorry @RomanGotsiy , I forgot to comment when I've tried it.The x-extendedDiscriminator was exactly what we was looking for. Thanks for the help!!
