### ISSUE TITLE
Can we integrate more than 3 instances on one single page?

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#261]
I tried this feature and found that I can only integrate at most 3 instances on one page. Is this the case or what I need to modify to make it work. Thanks!

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 I didn't get you. Can you explain what are you trying to do and which feature you are talking about?

**Comment by jenniferwang2000** [comment]
Sorry, I have made it working. Thank you and I will close it.
