### ISSUE TITLE
Suggestion: x-logo extension

### ISSUE THREAD

**Issue by icobani** [Rebilly/ReDoc#262]
Can we add this feature for logo integration if possible

{
  "consumes": [
    "application/json",
    "application/xml"
  ],
  "produces": [
    "application/json",
    "application/xml"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    **"x-logo": {
      "url": "./images/hrperformans/logo260x75x72.png",
      "backgroundColor": "#FFFFFF"
    },**
}

![alt text](https://content.screencast.com/users/Ibrahim_Cobani/folders/Snagit/media/36c98202-c254-4bf5-9dc5-8ee97ce16e50/2017-04-30_13-38-27.png "x-logo integration")

**Comment by RomanGotsiy** [comment]
@icobani what do you mean under "integration" ?

**Comment by icobani** [comment]
Sory it is my fault. Can i change if you have any suggestion. 👍

**Comment by RomanGotsiy** [comment]
Sorry, but I still do not understand :)
ReDoc supports [`x-logo` extension](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-logo) and you have even sent a screenshot with ReDoc that shows logo based on `x-logo`.
What is the feature you want to add?

**Comment by icobani** [comment]
Ooops wrong github project :/* this isue about https://github.com/go-swagger/go-swagger. I'm sorry to keep you busy

**Comment by RomanGotsiy** [comment]
🤣 
No problems!
As an additional reason for having this feature in go-swagger: [APIs.guru directory](https://github.com/APIs-guru/openapi-directory) has more than 400 specs and each has `x-logo`
