### ISSUE TITLE
Open Redirect & Possible XSS - No HTML Encoding

### ISSUE THREAD

**Issue by QuduSEC** [Rebilly/ReDoc#265]
Follow https://github.com/swagger-api/swagger-editor/issues/1312

Try explore in demo: [https://gist.github.com/QuduSEC/0733bed7b04ee9bda893894a428835a1](https://gist.github.com/QuduSEC/0733bed7b04ee9bda893894a428835a1)

**Comment by RomanGotsiy** [comment]
@QuduSEC usually ReDoc is used with the user specs which are trusted (users write them themselves) so I disabled html encoding for performance reasons.
But definitely, there may be use cases (e.g. ReDoc demo). I will provide an option which will enable encoding.
What do you think?

**Comment by QuduSEC** [comment]
@RomanGotsiy Yes, probably this will be a very good and flexible solution. But I would recommend setting it to the true by default. Because ReDoc can be used for example as a plugin for Confluence or other systems in the future, where you can specify the URL as a demo. And then it will become a more serious problem. Because, such code will be executed in this system.

**Comment by RomanGotsiy** [comment]
@QuduSEC,

> Because ReDoc can be used for example as a plugin for Confluence or other systems in the future, where you can specify the URL as a demo
Then these systems will have to set this option.

I set it to `false` by default for now as I don't want to introduce any breaking changes to existing users. I will change this to `true` with other breaking changes in version `2`.

I also added a note to README about this option and updated the ReDoc demo.

**Comment by RomanGotsiy** [comment]
@QuduSEC, Forgot to say "Thank you" for doing your job!
