### ISSUE TITLE
headers for spec-url

### ISSUE THREAD

**Issue by oliver-xapix-io** [Rebilly/ReDoc#272]
To get he Swagger file I wanna pull in I need to provide authentication headers.

How can I set those?

Thx for the great work, ReDoc is looking awesome, would love to integrate it! <3

**Comment by RomanGotsiy** [comment]
Hey @oliver-xapix-io,
are you doing cross-origin request? Or Swagger file is hosted on the same domain?

**Comment by RomanGotsiy** [comment]
just in case, you can download the spec yourself and then init ReDoc directly with the spec object.
To do so, don't specify `spec-url` in `<redoc>` tag. Instead, initialize ReDoc using API.

Here is an example using `fetch` (make sure to include polyfill, e.g. from CDN `<script src="//cdn.jsdelivr.net/fetch/0.9.0/fetch.min.js"></script>`)

```js
fetch('<URL>', {
  method: 'GET',
  headers: {
    'Authorization': 'Bearer <TOKEN>'
  }
})
.then(function(response) {
  return response.json()
})
.then(function(swagger) {
  ReDoc.init(swagger);
});
```

But this requires hard-coding token value in the javascript code, which is not secure.

Let me know if this works for you.

**Comment by pickledolives** [comment]
@RomanGotsiy Thx! Exactly what I was looking for! Security level in my use case not decreased by that.

**Comment by RomanGotsiy** [comment]
Awesome!

**Comment by jpOlivo** [comment]
> doing cross-origin reques

How i can do cross-origin request? My resource is under a repository external

<redoc spec-url='https://bitbucket-repo/api-spec.yaml'></redoc>

**Comment by SampaRasanie** [comment]
> ```js
> ReDoc.init
> ```

is there a guide to set ReDoc.init in angular 6 project?

**Comment by SampaRasanie** [comment]
is there any proper guide to initialize ReDoc using API in angular 6 project

**Comment by RomanHotsiy** [comment]
No. If you can figure it out we would appreciate it if you contribute back!
