### ISSUE TITLE
Issue with stick sidebar when there is content above reDoc

### ISSUE THREAD

**Issue by Alfaspider** [Rebilly/ReDoc#276]
Hi,

I'm trying to integrate redoc into existing website but I have issue with sticky sidebar overlaping content above redoc container. I've looked trough source code and I see postion should initially be absolute but in my case it immediately changes to fixed. If I scroll down a bit, sidebar fixes itself and stays ok even if I scroll up to top again. Problem is just initial load of page.

![image](https://cloud.githubusercontent.com/assets/546762/26541343/9989995c-4455-11e7-9fab-2aa949b44f45.png)

![image](https://cloud.githubusercontent.com/assets/546762/26541378/b14c45a8-4455-11e7-82b0-539543156591.png)

**Comment by RomanGotsiy** [comment]
@Alfaspider thanks for the bug report.
Will try to fix for the next version

**Comment by wimleers** [comment]
We ran into this too — wonderful to see this fixed already :)

When do you think there will be a release that contains this fix?

**Comment by Alfaspider** [comment]
Check out latest code and build it. Fix is already there.

**Comment by RomanGotsiy** [comment]
@wimleers @Alfaspider sorry for long replies and not releasing it earlier.
New release will be ready tomorrow morning!

**Comment by RomanGotsiy** [comment]
@wimleers should be fixed in the v1.16.1
