### ISSUE TITLE
Response composed with allOf not reflected in Response Schema

### ISSUE THREAD

**Issue by dmarmugi** [Rebilly/ReDoc#281]
Hi, 
I have a response built like 
```yaml
...
      responses:
        200:
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/Paging'
              - $ref: '#/definitions/ScheduleList'
...
```

Swagger editor properly models the response: 
![image](https://user-images.githubusercontent.com/13923591/26936598-203657bc-4c3d-11e7-9946-5c32b6916ac1.png)

but ReDoc only models the Paging element: 
![image](https://user-images.githubusercontent.com/13923591/26936721-7033920c-4c3d-11e7-8f17-e8e3f1ae179e.png)

It doesn't seem to matter whether I compose the schema in the response or in a separate definitions object. 

Let me know if you require further information, 
Thanks,
-David

**Comment by dmarmugi** [comment]
Specifying ScheduleList as `type: object` worked to fix the rendering. I'm not sure if you want to close this or not as a result. 
Thanks,
-David

**Comment by RomanGotsiy** [comment]
thanks for reporting. will close this
