### ISSUE TITLE
<redoc> as a shadow dom

### ISSUE THREAD

**Issue by pchaivong** [Rebilly/ReDoc#288]
I'm trying to use the Redoc.init(JSONObject) global object (because I have my spec as a JSON object instead of url). However, my <redoc> element seems to be in shadow dom (using Polymer), So the Redoc could not find it.

Is there any possible way to use JSON object with element <redoc> directly

Thank you very much

**Comment by RomanGotsiy** [comment]
Redoc has been rewritten to React since 2.0.0-alpha.x. Shadow DOM is not the case anymore
