### ISSUE TITLE
Strange character in contracted form

### ISSUE THREAD

**Issue by adamaltman** [Rebilly/ReDoc#29]
Look at this before and after it's expanded.  Notice the strange character in the contracted version:

![image](https://cloud.githubusercontent.com/assets/1161871/13723210/c545db1c-e823-11e5-98da-445e7e313cd0.png)

![image](https://cloud.githubusercontent.com/assets/1161871/13723208/c10dd63a-e823-11e5-8a62-db7a758be885.png)

**Comment by RomanGotsiy** [comment]
@adamaltman can you please provide more info: operating system, browser version, etc?

I can't reproduce this. Tried on IE11/Windows, Chrome/Mac and Safari/Mac.

**Comment by adamaltman** [comment]
Linux (ubuntu) Chrome.  Oddly, I don't seem able to reproduce it now myself.  (At least I have the screenshots to prove I wasn't crazy.)

**Comment by adamaltman** [comment]
I can reproduce this by running the deploy script on my local machine.

**Comment by RomanGotsiy** [comment]
Are you able to reproduce it always? Or like time by time?
Once you reproduce it could you please copy content of redoc.js file and send it to me?

**Comment by adamaltman** [comment]
The issue for me was the python-based simple http server which isn't utf-8 friendly.  This fixed the issue: http://stackoverflow.com/questions/15288891/how-can-i-serve-files-with-utf-8-encoding-using-python-simplehttpserver
