### ISSUE TITLE
Formatting Issue, Should be no top padding for H2 below H1

### ISSUE THREAD

**Issue by abagshaw** [Rebilly/ReDoc#291]
I could be missing something, and maybe there exists a current way to get around this, but I am running into a formatting issue with a lot of space between my H1 main titles and my H2 subtitles. See image below:

![capture](https://user-images.githubusercontent.com/8594541/27765856-d798553a-5e72-11e7-8104-e467a0aa2d79.JPG)

I don't believe there should be the large padding between the top H2 title and the H1 main title as it makes it unclear that the H2 elements are all contained with the H1 area. Is there a way to fix this?

**Comment by RomanGotsiy** [comment]
@abagshaw good point. Will fix it.
