### ISSUE TITLE
npm run build:prod currently fails

### ISSUE THREAD

**Issue by apriendeau** [Rebilly/ReDoc#293]
I just set up and I may have made a mistake but when following the developer commands at the bottom of the README and then running `npm run build:prod`, this is the output.

```
Error at /Users/austin/Projects/ReDoc/lib/services/search.service.ts:195:24: Argument of type 'Schema | Schema[]' is not assignable to parameter of type 'SwaggerSchema'.
  Type 'Schema[]' has no properties in common with type 'SwaggerSchema'.
Error at /Users/austin/Projects/ReDoc/tests/helpers.ts:24:49: Type 'true' has no properties in common with type 'MouseEventInit'.
```

**Comment by wilsonge** [comment]
Looks like this is related to the release of typescript 2.4. If I downgrade back to 2.3.2 this error goes away.

**Comment by wilsonge** [comment]
This should be fixed by https://github.com/Rebilly/ReDoc/pull/305
