### ISSUE TITLE
x-code-samples Copy Button

### ISSUE THREAD

**Issue by dillonwd6086** [Rebilly/ReDoc#296]
When using the vendor extension x-code-samples, I have been able to successfully add code samples to my ReDoc page.  The only issue is when I use the copy button to get the code sample, it includes formatting characters such as \n \r...etc.  Is there a work around to remove these?

**Comment by RomanGotsiy** [comment]
@dillonwd6086 sorry for not responding. I was on vacation.

Could you send an example of your swagger spec?
