### ISSUE TITLE
linking to endpoints via operationId

### ISSUE THREAD

**Issue by cheriewoo** [Rebilly/ReDoc#298]
First of all, kudos to ReDoc! It's super easy to use and its presentation format is clean and clear, especially wrt hierarchical structures. 

Our legacy API docs have tons of links across related API endpoints with unique resourceId's. I'm attempting to convert our resourceIds to Swagger's operationId and use them for linking across APIs. Is it possible to link to operationId's across Swagger files? 

I tried linking to an endpoint in a different swagger file, but URL keeps getting reset. To see the issue, click the "Get All Modules" link in the module query parameter description on this page: https://developer.dev.accela.com/docs/testdocs/redoc/index.html#operation/v4.post.reports.reportId. You will notice the URL is reset to https://developer.dev.accela.com/docs/testdocs/redoc/index.html#

**Comment by RomanGotsiy** [comment]
Hey @cheriewoo,

thanks for this issue report and sorry for not responding for a long time. I was on vacation.

I will check your issue ASAP and will get back to you

**Comment by RomanGotsiy** [comment]
@cheriewoo I've checked your issue.

Right now it can't be fixed in ReDoc.

To workaround this you can just have separate html for each spec instead of dynamic spec change.

**Comment by cheriewoo** [comment]
Thanks @RomanGotsiy  Is there a timeframe when it can be fixed?

**Comment by RomanGotsiy** [comment]
@cheriewoo 
> Right now it can't be fixed in ReDoc.

This can't be fixed in terms of ReDoc itself. But it can be fixed via `history` API in the browser.

I can update [multi-swagger sample](https://github.com/Rebilly/ReDoc/tree/master/demo/examples/multiple-apis) to address this issue.

**Comment by RomanGotsiy** [comment]
I've noticed it's an dup of https://github.com/Rebilly/ReDoc/issues/278
Closing in favour of https://github.com/Rebilly/ReDoc/issues/278
