### ISSUE TITLE
Feature: add possibility to comment on endpoints

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#3]
As suggested by @adamaltman:

> idea is to give users the ability to comment on endpoints (like for example, tweets, facebook comments, disqus, etc...)
> I was thinking that some may not want a DB, and use a 3rd party for comments like facebook comments https://developers.facebook.com/products/social-plugins/comments

**Comment by RomanGotsiy** [comment]
out of scope
