### ISSUE TITLE
readOnly: true property not hidden in REQUEST SAMPLES for nested objects 

### ISSUE THREAD

**Issue by Robinyo** [Rebilly/ReDoc#300]
It's great that the `readOnly: true` property allows you to use the same definitions for read (GET) and write (POST, PATCH, PUT) operations. However, the `readOnly: true` property is being ignored when generating REQUEST SAMPLES that include **nested objects** (e.g., the `names` array):

![image](https://user-images.githubusercontent.com/12203540/28101789-1f516dfa-670e-11e7-8a4d-bb4b639ae206.png)

The REQUEST BODY, however, is correctly rendered:

![image](https://user-images.githubusercontent.com/12203540/28101812-4dfe005a-670e-11e7-9825-a40dd9c9890f.png)

See: https://ato-team.github.io/business-registries-rest-api-specification

**Comment by RomanGotsiy** [comment]
@Robinyo thanks for issue report!

I will check it asap and will get back to you!
