### ISSUE TITLE
Odd encoding: _nghost-c18 .ellisis:after is garbled

### ISSUE THREAD

**Issue by philsturgeon** [Rebilly/ReDoc#302]
![screen shot 2017-07-13 at 11 59 48 am](https://user-images.githubusercontent.com/67381/28175770-2ac8bbce-67c3-11e7-8808-c42afe52c416.png)

**Comment by RomanGotsiy** [comment]
It's Unicode issue and this is a duplicate of https://github.com/Rebilly/ReDoc/issues/153 https://github.com/Rebilly/ReDoc/issues/29 and https://github.com/Rebilly/ReDoc/issues/213.

Check out these issue for the information of how to fix.
If the fixed won't work for you feel free to continue the conversation in this issue.

**Comment by philsturgeon** [comment]
Ha thank you! I had already tried #153 but hadn't seen the others. #213 fixed it!
