### ISSUE TITLE
Support for xml samples in response when there is no schema in response

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#307]
Now ReDoc supports xml sample in response when there is schema in response. Can we support to display xml sample in response when there is no schema in response? 

My sample file: 

        '200':
          description: |
            json sample without schema
          examples: 
            application/json:
              {
                "field1": "value1",
                "field2": "value2"
              }
        '400':
          description: |
            XML sample without schema
          examples: 
            application/xml:              
                <field>
                  <name>TaxMode</name>
                  <label>Tax Mode</label>
                  <type>picklist</type>
                  <options>
                    <option>TaxExclusive</option>
                    <option>TaxInclusive</option>
                  </options>
                  <contexts>
                    <context>export</context>
                  </contexts>
                </field>              
        '500':
          description: |
            XML sample with schema
          schema:
            $ref: '#/definitions/sampleSchema'          
          examples: 
            application/xml:              
                <field>
                  <name>TaxMode</name>
                  <label>Tax Mode</label>
                  <type>picklist</type>
                  <options>
                    <option>TaxExclusive</option>
                    <option>TaxInclusive</option>
                  </options>
                  <contexts>
                    <context>export</context>
                  </contexts>
                </field>

"XML sample without schema" can't be displayed in ReDoc.

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 thanks for detailed issue report.
This seems to be easy-fixable.
Will try to include this fix in the upcoming release!
