### ISSUE TITLE
How best to add code examples

### ISSUE THREAD

**Issue by potemkin17** [Rebilly/ReDoc#309]
It would be great if someone could explain how best to add python, js and java examples to ReDoc. What is the best way to generate them automatically based on the API endpoints. 

Thanks a lot!

**Comment by Robinyo** [comment]
Take a look at the Rebilly API: https://github.com/Rebilly/RebillyAPI/tree/master/spec/code_samples

The Rebilly API uses multiple specification files and the approach to adding code samples is very similar to how you add paths and definitions to a (multiple file) specification.

You can use Postman to generate code snippets:  http://blog.getpostman.com/2015/08/31/writing-front-end-api-code-with-postman/

Or, Paw: https://paw.cloud/

**Comment by potemkin17** [comment]
Thanks a lot - will explore and report back once I get it working

**Comment by RomanGotsiy** [comment]
@potemkin17 ReDoc doesn't support generating samples automatically. It just can render them.
As @Robinyo mentioned you can store each sample in a separate file and use scripts to bundle them into spec. We have yeoman generator for this. It will setup a repository with all the scripts ready. Check it out: https://github.com/Rebilly/generator-openapi-repo

Closing this issue.
feel free to continues conversation here though
