### ISSUE TITLE
Update lunr dependency

### ISSUE THREAD

**Issue by likern** [Rebilly/ReDoc#310]
Currently, I use http://www.webjars.org/ to supply `redoc`. And redoc requires lunr version `1.0.0`, which doesn't exist in http://www.webjars.org and looks like quite old. Could you update version of lunr in dependency to `2.1.0`?

**Comment by RomanGotsiy** [comment]
@likern I tried updating to `2.1.0` some time ago but the migrating is not so trivial and I it didn't work as expected at that time.

Once I have time I will try to update to latest `2.1.0`, maybe it is working now.

**Comment by likern** [comment]
@RomanGotsiy what problems did you have? At least I can test new `2.1.0` version, because it's urgent task for me.
I changed dependency manually (locally) and it looks like it works, at least my swagger/openapi json is working and I see rendered documentation page.

**Comment by RomanGotsiy** [comment]
How do you use ReDoc? Do you reference it from npm package or you are doing your own build?

at the moment npm package contains only bundled ReDoc which doesn't need any dependencies. So changing dependency locally without rebuilding ReDoc doesn't change anything.

So if you reference ReDoc either from npm package or from cdn you don't need any dependencies. ReDoc has them all bundled in.

**Comment by likern** [comment]
I use webjars at this site - http://www.webjars.org/ (packed files in jar format - java archive). I directly gave link to github repository - https://github.com/Rebilly/ReDoc and chose specific version `1.16.1`. This service can parse github repository and create jar package (java archive) and deploy it to maven repository (repository for java world) - http://repo1.maven.org/maven2/org/webjars/npm/redoc/1.16.1. http://repo1.maven.org/maven2/org/webjars/npm/redoc/1.16.1/redoc-1.16.1.pom describes dependencies:
```
<dependency>
<groupId>org.webjars.npm</groupId>
<artifactId>lunr</artifactId>
<version>1.0.0</version>
</dependency>
```
Probably these dependencies are taken from [`package.json`:](https://github.com/Rebilly/ReDoc/blob/master/package.json)
```
"dependencies": {
    ...
    "lunr": "^1.0.0",
    ...
  }
```
But for [`lunr`](http://repo1.maven.org/maven2/org/webjars/npm/lunr/) there is only two existing versions: `2.1.0`, `0.7.1`.

If unpack `jar xf redoc-1.16.1.jar` I get this content:
```
➜  test ls META-INF/resources/webjars/redoc/1.16.1 
bower.json    custom.d.ts  docker-compose.yml  karma.conf.js  package.json        README.md      tsconfig.webpack.json  yarn.lock
CHANGELOG.md  dist         docs                LICENSE        protractor.conf.js  tsconfig.json  tslint.json
```
and I use `META-INF/resources/webjars/redoc/1.16.1/dist/redoc.min.js`.

Thus I able to refer to local `redoc.min.js` in server (for security reasons) and at the same time no need to put javascript code directly in the project and can use them as a usual dependency:
```
<redoc spec-url="@routes.CasesController.getAsset("openapi/openapi.json")"></redoc>
<script src="@routes.CasesController.getAsset("lib/redoc/dist/redoc.min.js")"></script>
```

**Comment by likern** [comment]
Now, `lunr` with version `1.0.0` was added. It's no more urgent task. Anyway, it would be helpful to update  `lunr` to a newer version (if this make any sense for `ReDoc`).

**Comment by RomanGotsiy** [comment]
redoc@2.0.0-alpha.x used the latest lunr.
