### ISSUE TITLE
Is there a way to turn off 'Loading' and flash effect?

### ISSUE THREAD

**Issue by moon0326** [Rebilly/ReDoc#315]
Hi,

I'm testing out https://github.com/Rebilly/generator-openapi-repo#generator-openapi-repo live editing locally. Is there a way to turn off "Loading" and flash effect on refresh? Relatively small docs should render pretty fast.

Thanks,
Moon

**Comment by RomanGotsiy** [comment]
Hey @moon0326,

Great suggestion!
I will add new option for ReDoc to disable Loading
