### ISSUE TITLE
Deprecate bower?

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#316]
Anyone using bower to install ReDoc?

I am going to deprecate bower in two weeks if nobody suggests any reasons why to keep it before.

**Comment by jerguslejko** [comment]
Even the Bower team itself recommends switching away from it. (bower.io)

**Comment by RomanGotsiy** [comment]
@jerguslejko thanks! Bower is already deprecated in 2.0 alpha releases!
Closing this issue.
