### ISSUE TITLE
Response Headers not being rendered correctly

### ISSUE THREAD

**Issue by WagnerSilveira** [Rebilly/ReDoc#317]
Hello redoc maintainers !
I got a problem rendering response headers from a external file
Some parts, as the types and description are not loaded like the examples below
E.g 
image 1
![image](https://user-images.githubusercontent.com/3621676/28997429-f4defa84-79ea-11e7-8680-c02f20613ff1.png)
Image 2 
![image](https://user-images.githubusercontent.com/3621676/28997474-03b02aaa-79ec-11e7-8d03-a28cd23aff22.png)

Obs: this file is loaded repeatedly in my doc

This is my external file containing the response headers 

![image](https://user-images.githubusercontent.com/3621676/28997446-8ae77c2c-79eb-11e7-86d2-25118a22fb30.png)

![image](https://user-images.githubusercontent.com/3621676/28997489-549ea0a4-79ec-11e7-9d3c-d6446aa39d44.png)

**Comment by RomanGotsiy** [comment]
@WagnerSilveira headers can't be referenced according to Swagger 2.0 spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#headers-object

This is causing the issue. We have a script which inlines headers as a build step to have this working.

**Comment by RomanGotsiy** [comment]
@WagnerSilveira could I close this issue?

**Comment by WagnerSilveira** [comment]
Yes ! Thanks @RomanGotsiy
