### ISSUE TITLE
Discriminator selector dropdown overlaps

### ISSUE THREAD

**Issue by l1pton17** [Rebilly/ReDoc#318]
When using discriminator its dropdown overlaps by bellow accordion.

![image](https://user-images.githubusercontent.com/5460448/29005318-5faba050-7ae1-11e7-9538-f31bac14ecbb.png)

Quick fix for me was to add this code:

        [_nghost-c17] {
            overflow: visible !important;
        }

**Comment by RomanGotsiy** [comment]
Should be fixed in redoc@2.0.0-alpha.x
Feel free to open a new issue if it is not fixed
Thanks
