### ISSUE TITLE
Feature request: Clickable logo that points to specific url

### ISSUE THREAD

**Issue by khorolets** [Rebilly/ReDoc#322]
Hi!

I'd love to specify url somewhere somehow. And I'd like my logo to be clickable and point to that url.

Is it possible, now?

Thanks!

**Comment by RomanGotsiy** [comment]
Great idea!
Not possible now. We'll need to implement it.
Would you try to create a PR for this?

**Comment by khorolets** [comment]
@RomanGotsiy I'd love to but I'm not good in Angular :(

**Comment by khorolets** [comment]
Also, would be great to have a link at the top something like `Go back to <url>`.

**Comment by hlorofos** [comment]
Wow, link on the logo would be a great addition!

**Comment by khorolets** [comment]
@RomanGotsiy could you describe what parameter and in what section you expect, so we would know what PR you will accept. Thanks!

**Comment by khorolets** [comment]
@RomanGotsiy I'm trying to prepare PR, will discuss my prev comment in the PR, if you don't mind.
