### ISSUE TITLE
Question: Try this operation

### ISSUE THREAD

**Issue by bandantonio** [Rebilly/ReDoc#331]
Native Swagger implementation has a handy feature called "Try this operation" that allows users to interact with API by sending test requests directly from the documentation page. 
Are there any plans of implementing something similar in ReDoc?

**Comment by RomanGotsiy** [comment]
Hey @bandantonio,
yes, we have this on our roadmap. It is tracked in https://github.com/Rebilly/ReDoc/issues/53

**Comment by wll8** [comment]
Try [redoc-try](https://github.com/wll8/redoc-try), use `swagger Try it out` in` redoc` project.

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_WX20200518-152825.png)
