### ISSUE TITLE
Try it out

### ISSUE THREAD

**Issue by raderio** [Rebilly/ReDoc#335]
Can you please add "Try it out" posibility like it is in Swagger UI?

**Comment by RomanGotsiy** [comment]
@raderio this is a dup of https://github.com/Rebilly/ReDoc/issues/53

**Comment by wll8** [comment]
Try [redoc-try](https://github.com/wll8/redoc-try), use `swagger Try it out` in` redoc` project.

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_WX20200518-152825.png)

**Comment by wll8** [comment]
There is currently no npm library released, I feel it is unnecessary. :)
