### ISSUE TITLE
Unable to run ReDoc

### ISSUE THREAD

**Issue by lanxin11** [Rebilly/ReDoc#337]
I have installed node-v8.4.0 and npm-5.3.0. The install process looks fine except for a few warnings...
But when I execute the command `npm start`, errors occur and the http://localhost:9000/ page cannot perform normally. The majority of the page content is blank.
The output on the command line is like:
```
> redoc@1.18.1 start /Users/lzhao/Downloads/ReDoc-master
> webpack-dev-server --config build/webpack.dev.js --content-base demo

Project is running at http://localhost:9000/
webpack output is served from /
Content not from webpack is served from /Users/lzhao/Downloads/ReDoc-master/demo

[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/lzhao/Downloads/ReDoc-master/tsconfig.json (in a forked process).


[at-loader] Checking started in a separate process...

webpack: Compiled successfully.

[at-loader] Checking finished with 1 errors
[at-loader] ./lib/bootstrap.ts:4:36 
    TS2307: Cannot find module '../compiled/lib/app.module.ngfactory'. 
```

Can anybody explain what this means and how can I solve this problem?
Thanks a lot!!!

**Comment by RomanGotsiy** [comment]
Hey @lanxin11,
I don't see any issues in console output. `[at-loader]` error about `ngfactory` is a known issue and shouldn't affect compilation process.

Could you send screenshot of the page content and also send the output from browser console.

**Comment by lanxin11** [comment]
Hi @RomanGotsiy 
  
Still cannot have ReDoc work properly now. Please find the screenshot and the output file in the attachment. Many thanks!

Best,
Lanxin
<img width="1139" alt="screen shot 2017-09-07 at 10 28 29 am" src="https://user-images.githubusercontent.com/31644218/30143688-ce4158d4-93b9-11e7-9d91-2899eee131ac.png">

[consoleOutput.txt](https://github.com/Rebilly/ReDoc/files/1283320/consoleOutput.txt)

**Comment by lanxin11** [comment]
It seems that just the index.html consumes too much resources. I changed a simpler index.html and it works finally.
