### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by lanxin11** [Rebilly/ReDoc#339]
Hi there,

It turns out that when the yaml file (or json file) size is huge, ReDoc incurs serious performance issue. It takes me over ten seconds to open our company's API reference page.

Any suggestions how to fix this issue? Or are you going to improve the codes in the future? Many thanks!

Lanxin

**Comment by RomanGotsiy** [comment]
Hey @lanxin11, we are aware of the performance issues and are working to resolve them.
Have you tried [`lazy-rendering`](https://github.com/Rebilly/ReDoc#redoc-tag-attributes) option?

**Comment by lanxin11** [comment]
Hi @RomanGotsiy ,
  Thanks for your information, Roman. Really appreciate it.

  I haven't tried lazy-rendering yet. BTW, do you mean the ng-lazy-render directives? Should I install extra modules? 

Regards,
Lanxin

**Comment by RomanGotsiy** [comment]
@lanxin11 no, you don't need any extra modules.
just enable `lazy-rendering` ReDoc option:

```html
<redoc spec-url="..." lazy-rendering></redoc>
```
All ReDoc options are listed here: https://github.com/Rebilly/ReDoc#redoc-tag-attributes

**Comment by RomanGotsiy** [comment]
Closing this issue but feel free to continue discussion here

**Comment by ngthtung** [comment]
Hi guys, I'm using Redoc v2 and it's not support lazyRendering yet. Any idea about this problem when use version 2?

**Comment by RomanHotsiy** [comment]
It won't be supported. This was complicated to maintain feature which did not solve the underlying issue in a best way.
