### ISSUE TITLE
Error compiling - Uglify error

### ISSUE THREAD

**Issue by jimmyjames** [Rebilly/ReDoc#340]
Getting an error on `npm run build:all`: 

```
ERROR in redoc.min.js from UglifyJs
Unexpected token: punc (() [./node_modules/dropkickjs/src/utils.js:3,0][redoc.min.js:74800,10]
```

Looks related to https://github.com/Robdel12/DropKick/issues/349 but not sure what the best way to get around it in the ReDoc build...

**Comment by RomanGotsiy** [comment]
Fixed, reinstall your node_modules and try again

**Comment by jimmyjames** [comment]
👍 !
