### ISSUE TITLE
Loading Large Swagger Spec file gives error.

### ISSUE THREAD

**Issue by pkvenu** [Rebilly/ReDoc#341]
I am trying to run ReDocs with a super large spec file (23103 lines) and it returns an error (See attached).
<img width="1233" alt="screen shot 2017-09-20 at 1 52 44 am" src="https://user-images.githubusercontent.com/6444752/30635326-e9f39014-9da6-11e7-8083-99307e9c3a78.png">

When I am loading a small file it works as intended. I have also validated the swagger spec for any errors. Any help would be greatly appreciated. 

<img width="1280" alt="screen shot 2017-09-20 at 2 03 53 am" src="https://user-images.githubusercontent.com/6444752/30635687-088fe06c-9da8-11e7-826f-be177d0167e7.png">

**Comment by RomanGotsiy** [comment]
Most likely this issue has nothing to do with the spec size. Probably your large spec has some things ReDoc doesn't expect. Could you send me your spec so I can test it myself? Or if the spec is private, try to localize the issue e.g. by removing paths

**Comment by RomanGotsiy** [comment]
@pkvenu fixed in `v1.19.1`
