### ISSUE TITLE
Add x-permissions feature

### ISSUE THREAD

**Issue by zucher** [Rebilly/ReDoc#345]
Some api are accessible one for some user with a specific level of permission: superadmin admin, user, guest,...

I propose an x-permissions array object:
{
"name": "string",
"summary": "string",
"description": string"
}

example:
"x-permissions": [{
                    "name": "superadmin",
                    "title": "Solution Admin",
                    "description": "Solution Admin has high privileges on Pet API "
                }...]

With this information associated to operation api, a simple tag with mouse over or everything else is specified below the Operation label. like

## Get Pets operation
*Permissions* `Solution Admin` `User`...

The description could be either detailed below the authentication chapter or into every operation (a little bit heavy)

We also may add x-permissions list into swagger top level like tags, just refer to them into operation

**Comment by zucher** [comment]
See http://apidocjs.com/#param-api-permission for sample declaration into an other kind of rest api declaration

**Comment by zucher** [comment]
I do the job this the second solution, like tags after header description with under operation the lable for each of them
![image](https://user-images.githubusercontent.com/3034596/30899838-e2e75056-a361-11e7-9b7a-298ddefbe210.png)

**Comment by zucher** [comment]
I have to add documentation and tests

**Comment by zucher** [comment]
See https://github.com/Rebilly/ReDoc/pull/349

regards

**Comment by RomanGotsiy** [comment]
Closing this issue.
Reasons explained in the corresponding PR.

Thanks!
