### ISSUE TITLE
 npm installation throwing unmet peer dependency issues.

### ISSUE THREAD

**Issue by AnandhiE** [Rebilly/ReDoc#348]
├── UNMET PEER DEPENDENCY @angular/common@2.4.5
├── UNMET PEER DEPENDENCY @angular/core@2.4.5
└── UNMET PEER DEPENDENCY zone.js@0.7.6
npm WARN EPEERINVALID @angular/forms@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN EPEERINVALID @angular/forms@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN EPEERINVALID angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN EPEERINVALID angular2-universal-polyfills@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.

**Comment by RomanGotsiy** [comment]
What is the version of npm?
Anyway, these are just warnings and they will be resolved in the upcoming major release.

Closing this issue, feel free to continue discussion here
