### ISSUE TITLE
x-environments

### ISSUE THREAD

**Issue by adamaltman** [Rebilly/ReDoc#35]
Idea of sandbox, live, integration, test, and other environments.

**Comment by cevatkerim** [comment]
I generate different swagger file per environment and have a dropdown in redoc header for choosing which swagger file to point at. It works well. Just wanted to share how I am doing it today.

**Comment by RomanGotsiy** [comment]
Resolved with `x-servers` ([docs](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-servers)) (back-ported from OpenAPI 3)
