### ISSUE TITLE
Overriding global x-servers

### ISSUE THREAD

**Issue by vietnguyen010** [Rebilly/ReDoc#350]
According to [Swagger document](https://swagger.io/docs/specification/paths-and-operations/) at Overriding Global Servers, I can override global `servers` but with `x-servers` from ReDoc, is not work.

	x-servers:
	  - url: //example.com/api/
		description: Default server
	paths:
	  /oauth/get_token:
		x-servers:
		  - url: https://authen.example.com
		     description: Override base path for all operations with the /files path

Can anyone tell me the way to override `x-servers` URL? Or just customise server for specific paths

Any idea?

**Comment by RomanGotsiy** [comment]
@vietnguyen010 thanks. This is not supported by ReDoc yet.
Should be fixed with the next major release.

**Comment by BenAHammond** [comment]
Any update on this feature? I'd hate to have to force this with JS.

**Comment by RomanGotsiy** [comment]
It should work just fine with the latest redoc@2.0.0-alpha.x
Closing this issue.
Feel free to reopen if this is still not fixed
