### ISSUE TITLE
GraphQL documentation

### ISSUE THREAD

**Issue by raderio** [Rebilly/ReDoc#351]
Is it possible to document GraphQL using ReDoc?

**Comment by RomanGotsiy** [comment]
@raderio!
No, ReDoc works only with OpenAPI.
For GraphQL there is [GraphiQL](https://github.com/graphql/graphiql) which has `Docs` panel:
![image](https://user-images.githubusercontent.com/3975738/31067701-e3b1b59a-a75c-11e7-8808-2c9c46727995.png)

Also, you may be interested in [GraphQL Voyager](https://github.com/APIs-guru/graphql-voyager) (I'm co-creator) and [GraphQL Playground](https://github.com/graphcool/graphql-playground)

**Comment by dude-awesome** [comment]
this  should also work with the introspection from a graphql api. graphiql is okay but not so clear and lean like this.
