### ISSUE TITLE
npm dependencies not showing up in related folder eventhough the packages has been successfully installed and restored

### ISSUE THREAD

**Issue by AnandhiE** [Rebilly/ReDoc#352]

**Comment by RomanGotsiy** [comment]
I do not understand. Could you explain it in other words?

**Comment by AnandhiE** [comment]
The project dependencies folder remains empty always

**Comment by RomanGotsiy** [comment]
Why do you think it is ReDoc issue? Can you post your terminal commands? Does it work with other projects? Which operating system you are running on? npm version? node version?
