### ISSUE TITLE
Standalone enum parameters are not displayed correctly in request sample.

### ISSUE THREAD

**Issue by luukp** [Rebilly/ReDoc#358]
Some of our operations accept a lone string value with an enum for the request body.  Instead of being displayed as (e.g.) `"METRIC_LATENCY"` or `"string"` in the request sample, they are displayed as:
```
{
    "val": "METRIC_LATENCY",
    "type": "string"
}
```
which is incorrect.

The attached [swagger.yaml.gz](https://github.com/Rebilly/ReDoc/files/1385889/swagger.yaml.gz) file shows the issue. The "set domain list description" operation takes a string value (no enum) and displays the request sample correctly, while the "update a performance profile's preferred metric" operation is very similar, but has an enum, and displays the request sample incorrectly.

If I change the "general" injector to  `return value;` instead of `return {val: value, type: typeof value};` for enum fields, it fixes the issue, but breaks the enum display in other places.

**Comment by RomanGotsiy** [comment]
@luukp, could you attach a screenshot and specify which version of ReDoc you use!
thanks

**Comment by luukp** [comment]
We are using the latest version of ReDoc. The screenshot is below.

![issue](https://user-images.githubusercontent.com/14119301/31866744-b292aaa2-b7e0-11e7-81ea-93178a1766c4.png)

**Comment by RomanGotsiy** [comment]
@luukp thanks for screenshot and sorry for the long reply (i've been traveling last week).

I can verify the issue.
How urgent is it for you? I can cut the minor release with this issue fixed in 2-3 days.
Alternatively, you can wait for the upcoming major release which is React rewrite of Redoc which doesn't have this issue.

**Comment by luukp** [comment]
It isn't super urgent for us.  I'm happy to wait for a major release.  We haven't released our API documentation yet, and we currently have a temporary workaround in place to remove the enum attribute from the yaml file for standalone enum parameters.

**Comment by RomanGotsiy** [comment]
Fixed in redoc@2.0.0-alpha.x
