### ISSUE TITLE
Consider using oai-ts-core for OAI modeling

### ISSUE THREAD

**Issue by EricWittmann** [Rebilly/ReDoc#359]
I haven't dug into the **ReDoc** code to determine how the OAI documents are being read/processed.  However, as part of the **Apicurio** OpenAPI visual editor we've created a standalone data model library for OAI written in typescript:

https://github.com/Apicurio/oai-ts-core

We've got support for 2.0 and 3.0.0 (although validation rules are currently missing for the latter).  In addition, the data model supports the visitor pattern, which might be useful for a doc generator.

Perhaps have a look and see if **oai-ts-core** might be of some use in this project. :)

**Comment by RomanGotsiy** [comment]
Hey @EricWittmann!

Thanks for working on oai-ts-core! I haven't dug so deep too, but this looks pretty useful when it goes to manipulating the OpenAPI file.

Right now I am busy with migrating ReDoc codebase to React and it already took too much time so I don't want to make it even longer by migrating to your lib considering it lacks some features I need.

I agree that this would be great to collaborate on such kind of lib so I will definitely consider this lib in the future and will monitor your repo!

Thanks again for open-sourcing your lib! Hope we'll manage to collaborate on this at some point.
