### ISSUE TITLE
Customized CSS break when upgrading to new ReDoc version

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#361]
Our company customized the CSS when we first published our docs on production (https://www.zuora.com/developer/api-reference/). Now we want to upgrade ReDoc version and tested it on our production testing server (http://yamlsandbox-zuora.pantheonsite.io/developer/api-reference/), the color of the code font changed to red, which is very weird. 

Can you think of any reason causing this break? Do we need to change our CSS each time to upgrade to a new version, or is there an easy fix on your side? Thanks!

**Comment by RomanGotsiy** [comment]
@jenniferwang2000, unfortunately, I didn't make sure to not make breaking changes in css as ReDoc was mainly used in a standard look.

I suggest you wait for the React rewrite of ReDoc is ready and then migrate your styling. It will support customizations in a non-breakable way.

Closing this issue, feel free to continue the discussion here!

**Comment by damianobarbati** [comment]
@RomanHotsiy is there a way to inject custom css in the single page without using the React component of redoc?
