### ISSUE TITLE
Alternative solution to anyOf

### ISSUE THREAD

**Issue by ben-foster-cko** [Rebilly/ReDoc#363]
Hi,

I have a property that is either a `string` or an `object`. How would be the best way to represent this? I see Open API 3.0 has `anyOf` but it doesn't look like ReDoc supports v3.0 yet.

**Comment by RomanGotsiy** [comment]
There is no way to do it in OpenAPI 2.0 and ReDoc doesn't support v3.0 yet.
But it will support it very soon, together with React rewrite. Please, track this issue: https://github.com/Rebilly/ReDoc/issues/327
