### ISSUE TITLE
x-extendedDiscriminator for responses

### ISSUE THREAD

**Issue by ben-foster-cko** [Rebilly/ReDoc#364]
Should `x-extendedDiscriminator` work for responses? I configured my response as per the example on the WIKI and I don't see a dropdown to select the response type.

**Comment by RomanGotsiy** [comment]
Could you send your spec? Or minimal reproducible example?

**Comment by ben-foster-cko** [comment]
This is now working so it must have been an issue with my spec. However, the JSON example does not reflect the selected type. Is this the expected behavior and is it possible to work around this with `x-example`?

**Comment by RomanGotsiy** [comment]
No, this is known issue (https://github.com/Rebilly/ReDoc/issues/99) and can't be workarounded at the moment.
Fortunately, it will work in the upcoming major release (React rewrite)

Can I close this issue?

**Comment by ben-foster-cko** [comment]
That's great to know it's being addressed. Do you have any idea when the react version will be available?

**Comment by RomanGotsiy** [comment]
I'm working on this but a bit busy recent weeks 😞 
I expect to prepare an alpha release in 2 weeks.
