### ISSUE TITLE
Discriminator not showing

### ISSUE THREAD

**Issue by SebastianStehle** [Rebilly/ReDoc#366]
Hi,

I have a hard time figuring out why my discriminators are not showing: https://cloud.squidex.io/api/docs#operation/SchemaFields_PostField

The fieldType is a discriminator and I am very sure that it worked some month ago, but I cannot find out what I have changed in the meantime :(

**Comment by SebastianStehle** [comment]
I have reduced my example to: https://gist.githubusercontent.com/SebastianStehle/7642f3e2fa398f605b62ecbbb6b651d8/raw/b050c3405b45cfbb89c4359b17601436d91bf322/foo.json

**Comment by SebastianStehle** [comment]
Works with discriminator on the root level: https://gist.githubusercontent.com/SebastianStehle/053cc60ca2f0a8dde05661a04005e843/raw/4dd78dea9266464e411fd7b8afc58ecbe65a113b/flat.json

**Comment by SebastianStehle** [comment]
Duplicate of: https://github.com/Rebilly/ReDoc/issues/314 

Very strange, I am sure it was working.

**Comment by RomanGotsiy** [comment]
closing in favor of #314 
Thanks for the detailed bug report!
