### ISSUE TITLE
Provide CDN links for released versions.

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#37]
It would be useful to have stable CDN links for each release not just for most recent one.

**Comment by IvanGoncharov** [comment]
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by IvanGoncharov** [comment]
Alternatively this project could be used:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by RomanGotsiy** [comment]
OK, I've checked GitHub releases and it doesn't work as CDN.
Instead, it uses Amazon S3 under the hood - the slowest storage ever.

CDNJS is not a variant for us for now, cause they don't accept beta-releases and they require lib to be popular (e.g. 100 stars on GH) as well.

I'll investigate other possible options.

**Comment by adamaltman** [comment]
We could use Amazon Cloudfront CDN.  Thoughts?  

It's relatively cheap, and priced based on actual usage.  So it will only really cost anything if this is really popular... which we know it will be. 

On the other hand, is using Amazon S3 under the hood bad?  This is to be used in what way exactly?  By the creators of documentation? Or by the readers of the documentation?

**Comment by adamaltman** [comment]
https://media.amazonwebservices.com/FS_WP_AWS_CDN_CloudFront.pdf (I'm sure it's biased, but seems it performs.)

**Comment by RomanGotsiy** [comment]
@adamaltman Amazon CloudFront is not very good solution as it provides by default some random domain name which looks not very well. So it will require us to set up our own domain. As well it requires setup Amazon Account.

A better very simple solution just dawned on me: we will store releases on github pages. GitHub Pages are CDN so I will just put versions into a folder e.g. `releases`.
In such case we will have pretty domain name:
```rebilly.github.io/ReDoc/releases/vx.x.x/redoc.min.js```

I don't know why I hadn't came up with it earlier.

**Comment by adamaltman** [comment]
Okay, great.  

FYI, we have AWS accounts and domains already, in case it is necessary to go the cloudfront route.

I think your solution sounds good.

**Comment by RomanGotsiy** [comment]
Now releases are available at the following addresses:
 - latest release: [http://rebilly.github.io/ReDoc/releases/**latest**/redoc.min.js](http://rebilly.github.io/ReDoc/releases/latest/redoc.min.js)
 - some particular release, e.g. v0.9.0: [http://rebilly.github.io/ReDoc/releases/**v0.9.0**/redoc.min.js](http://rebilly.github.io/ReDoc/releases/v0.9.0/redoc.min.js)
