### ISSUE TITLE
Allow Accept headersto be customized when loading resources

### ISSUE THREAD

**Issue by bartfeenstra** [Rebilly/ReDoc#370]
Resources are sometimes behind HTTP resources that must be requested as specific content types. Example: I am currently working with schemas that must be requested as `application/schema+json` (the official JSON Schema content type), and the same HTTP resource that serves ReDoc when requested as `text/html`, serves instead the raw OpenAPI/Swagger specification as JSON when requested as `application/json`. I'd be happy to configure these myself when rendering ReDoc, but I don't see a way to instruct ReDoc to retrieve particular resources as specific content types. Pattern matching would be nice, so if multiple schemas at `https://example.com/schemas/...` are referenced `"https://example.com/schemas/*": "application/json"` would tell ReDoc to use that `Accept` header value for requests to resources matching that pattern.

Is something like this possible, or would it be possible to allow this? I'm totally loving ReDoc, and this is the only thing preventing me from using it everywhere. I'm no JS coder, but if there's anything else I can do to help move this along, please let me know :)

**Comment by RomanGotsiy** [comment]
Hey @bartfeenstra!
You can solve the issue if you use [ReDoc advanced initialization](https://github.com/Rebilly/ReDoc#advanced-usage). You will have to load your spec manually and provide ReDoc directly with the spec object. Using [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) the code may look like:

```js
fetch('https://example.com/schemas/test', {
  headers: { Accept: 'application/schema+json' }
}).then(response => response.json()).then(spec => {
   Redoc.init(spec, {
      // additional options
   });
});
```

Make sure to remove `spec-url` attribute from `<redoc>` tag as it triggers auto-initialization.

Closing this issue but feel free to continue the discussion here or ask any further questions!

**Comment by bartfeenstra** [comment]
Привіт, Романе. Дякую за вашу швидку допомогу! This would indeed solve the fetching of the OpenAPI resource, but other resources, such as referenced (`$ref`) JSON Schemas still seem to be retrieved from within ReDoc somewhere. Can I intercept those HTTP requests somehow?

**Comment by RomanGotsiy** [comment]
@bartfeenstra ahhh, that's a valid point.
Unfortunately, you can't workaround this in the current version :(

The only solution is to bundle all the referenced JSON schemas into one file before passing it to ReDoc.
The proper solution would be to provide you with the ability to overwrite fetching logick e.g. `fetcher` property. I will address this in the upcoming 2.0 version.
Unfortunately, I don't have enough time to fix it in the current 1.x branch as the fix is not obvious.
Thanks for understanding!

**Comment by bartfeenstra** [comment]
Thanks for explaining this. Shall I write up a new issue and mark it an *enhancement*?
