### ISSUE TITLE
Multiple response examples not supported

### ISSUE THREAD

**Issue by GCGarrettG** [Rebilly/ReDoc#371]
The examples key can only be used to specify a single example response.  If more than one example is provided only the first is displayed.  

```paths:
  "/myCar":
    get:
      operationId: CAR
      produces:
      - application/json
      - text/plain
      responses:
        '200':
          description: OK
          examples:
            application/json:
              car: 'blue'
            text/plain: 'TextAboutMyCar'
          schema:
            "$ref": "#/def/cars"
      security: []
      parameters: []```

**Comment by mpasaric** [comment]
Isn't multiple response examples only supported by OpenAPI 3.0? For which ReDoc support is still in development?

**Comment by RomanGotsiy** [comment]
@mpasaric I believe @GCGarrettG is talking about examples for `application/json` and `text/plain`.

This is an issue and I can reproduce it. Will try to fix asap and publish new patch release

**Comment by RomanGotsiy** [comment]
@GCGarrettG I've fixed the issue and will release new version soon.
Unfortunately, ReDoc supports only json, xml and text-like samples.

ReDoc 2.0 will support all the mime samples correctly so I am not going to fix it properly for ReDoc 1.x

Thanks for the bug report!

**Comment by GCGarrettG** [comment]
@RomanGotsiy My pleasure.  Thanks for the expedient fix, I look forward to the next release!

**Comment by zucher** [comment]
@RomanGotsiy, you can also take my fork, on my we want to returns csv text format, not only text/plain.
An other point not already treated is the returns format: If the REST request doesn't return application/json, we don't have to display the JSON associated tab.

**Comment by rishagit** [comment]
> text-

hi
i am working on the latest version of redoc and for me examples are ignored if type is plain/text. Any way to show example for plain/text type as well?

**Comment by edno** [comment]
I can see that Redoc still ignore `object` response examples when `content-type` is not `application-json`.

@RomanHotsiy - Do you have an update on
> ReDoc 2.0 will support all the mime samples correctly so I am not going to fix it properly for ReDoc 1.x
