### ISSUE TITLE
How do I translate?

### ISSUE THREAD

**Issue by danielsalles** [Rebilly/ReDoc#372]
I've seen that in the swagger-ui folder it has some translations, but I do not understand how I use it.

**Comment by RomanGotsiy** [comment]
Hey @danielsalles!

Have you confused projects? It's not Swagger UI, it's ReDoc :)
For Swagger UI questions/issues go to [Swagger UI](https://github.com/swagger-api/swagger-ui) repo.

If you want ReDoc to support different languages you can track issue: https://github.com/Rebilly/ReDoc/issues/367
