### ISSUE TITLE
Getting error at the time npm start

### ISSUE THREAD

**Issue by shivkumarsingh7** [Rebilly/ReDoc#373]
npm start

> redoc@1.19.1 start /Users/shivam/Sites/ReDoc
> webpack-dev-server --config build/webpack.dev.js --content-base demo

Error: listen EADDRINUSE 127.0.0.1:9000
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at GetAddrInfoReqWrap.doListen (net.js:1492:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redoc@1.19.1 start: `webpack-dev-server --config build/webpack.dev.js --content-base demo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redoc@1.19.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by RomanGotsiy** [comment]
You have another server or just another instance of redoc dev servers listening 9000 port.
Try to restart your computer and try again. If this won't help you can manually change port number in webpack config: https://github.com/Rebilly/ReDoc/blob/master/build/webpack.dev.js#L28

**Comment by shivkumarsingh7** [comment]
@RomanGotsiy Its work after changing port. Thanx
