### ISSUE TITLE
How to render <> characters?

### ISSUE THREAD

**Issue by monolithed** [Rebilly/ReDoc#378]
**Problem:**

1.

```java
Messages.auth('<TYPE>', <CREDENTIALS>);
```

```java
Messages.auth('', );
```

2.

```java
Messages.auth('<<TYPE>>', <<CREDENTIALS>>);
```

```java
Messages.auth('<>', <>);
```

3.

```java
Messages.auth('\<TYPE\>', \<CREDENTIALS\>);
```

```java
Messages.auth('\', \);
```

**Expected:**

```java
Messages.auth('<TYPE>', <CREDENTIALS>);
```

**Comment by jroweboy** [comment]
@monolithed `Messages.auth('&lt;TYPE&gt;', &lt;CREDENTIALS&gt;);` should work.

**Comment by RomanGotsiy** [comment]
@monolithed can you explain where you put this content and face these issues?
Can you share a snippet of your spec?

I tried to put the first snippet into markdown blocks (e.g. `description`) and they worked fine. One thing to notice you have to wrap them with backticks (```) - but it's not specific to ReDoc but to markdown in general. So the following worked just fine for me:

```yaml
description: |
  `Messages.auth('<TYPE>', <CREDENTIALS>);` Some free form text
```

or even

````yaml
description: |
  ```java
  Messages.auth('<TYPE>', <CREDENTIALS>);
  ```
  Some free form text
````

**Comment by RomanGotsiy** [comment]
@monolithed I've just managed to reproduce it. It works wrong if using just backticks without language specified:

````yaml
description: |
  ```
  Messages.auth('<TYPE>', <CREDENTIALS>);
  ```
  Some free form text
````

I've fixed and will release a new version soon.
