### ISSUE TITLE
Enable compression for OpenAPI spec download

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#38]
Set appropriate headers to allow for `gzip` compression.
Discovered by Google's PageSpeed Insights: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Frebilly.github.io%2FReDoc%2F&tab=mobile

**Comment by RomanGotsiy** [comment]
The only file which is not compressed according to PageSpeed Insights is `http://rebilly.github.io/SwaggerTemplateRepo/swagger.yaml`. But this file is served from GitHub pages. I have no control over GitHub pages HTTP headers. GitHub auto gzips most of the files. But it seems that it doesn't gzips `yaml` files.
Closing this issue.
