### ISSUE TITLE
Arrow Issues

### ISSUE THREAD

**Issue by lanxin11** [Rebilly/ReDoc#383]
Hi @RomanGotsiy,
We updated ReDoc v1.19.3 to our sandbox environment and found the following issues:

After expanding an item in the left pane, the arrow stays the same and it cannot collapse the expanded content. It is weird because down arrows should become up arrows after expanding. Arrows work fine for the samples in the right pane though.

![2017-11-23_16-25-36](https://user-images.githubusercontent.com/31644218/33164303-19061acc-d06d-11e7-8555-0f2895c0c45d.png)

Could you take a look and help solve this issues? Thanks!

Lanxin

**Comment by RomanGotsiy** [comment]
@lanxin11 would be awesome if you sent me a link to your sandbox environment so I can see it.

**Comment by lanxin11** [comment]
Sure. See [here](http://yamlsandbox-zuora.pantheonsite.io/developer/api-reference/#section/Introduction).

**Comment by lanxin11** [comment]
@RomanGotsiy I think the sandbox link is not ready to be exposed to the public, so I'll send you an email about it. Also I think the first two issues are because of Zuora's customization, not because of the ReDoc itself. So I'll only leave the third issue here and include the details about the first two issues, which absolutely needs your help, in the email as well.
Thanks for your help!

Regards,
Lanxin

**Comment by lanxin11** [comment]
Hi @RomanGotsiy,
Is this issue fixed? If it is a 'yes', are you going to include this fix in your next release?
Thanks for your reply.

Best Regards,
Lanxin
![2017-12-07_11-13-08](https://user-images.githubusercontent.com/31644218/33697058-07252af4-db40-11e7-8c22-a545f30d95ac.png)
