### ISSUE TITLE
Connot make 'x-tagGroups` work

### ISSUE THREAD

**Issue by hpatoio** [Rebilly/ReDoc#385]
I've this section in my swagger but I can't see any grouped menu

```
        "tags": [
            {
                "name": "customer"
            },
            {
                "name": "invoice"
            }
        ],
        "x-tagGroups": [
            {
                "name": "billing",
                "tags": [
                    "invoice",
                    "customer"
                ]
            }
        ]
```
What can it be ?

**Comment by RomanGotsiy** [comment]
Could you create a minimal reproducible sample of the whole spec? It's hard to guess like that.
The snipped you shared looks ok, maybe you made mistake somewhere else.
Could you share screenshot also?

**Comment by hpatoio** [comment]
My fault. I was putting the section above under "info" section. Thanks
