### ISSUE TITLE
Add instructions on generating aggregated JS files

### ISSUE THREAD

**Issue by bartfeenstra** [Rebilly/ReDoc#388]
Hi! We had a quick chat at API The Docs on my trouble debugging ReDoc and my schemas. I figure what would help me most, is to be able to embed a non-minified version of the JS file, so I can see for myself what assumptions the code makes. Would you be able to add such instructions?

For production, I'd like to host my own minified version of the JS file, identical to the one you host. If these instructions are similar, could they perhaps be added as well?

Thanks!

**Comment by RomanGotsiy** [comment]
Hey @bartfeenstra!
Sorry for late reply, I've been traveling recently.

That would be definitely useful not only for you but for other potential contributors. I will create CONTRIBUTING.md ASAP, most likely on weekends.
Thanks for the suggestion!

**Comment by bartfeenstra** [comment]
Thanks! That sounds useful :)

**Comment by RomanGotsiy** [comment]
CONTRIBUTING.md is ready: https://github.com/Rebilly/ReDoc/blob/master/.github/CONTRIBUTING.md
