### ISSUE TITLE
"Fixed" sidebar causes page to jump

### ISSUE THREAD

**Issue by scottybo** [Rebilly/ReDoc#393]
https://www.chooseholly.com/documentation

I would like to display ReDoc within a container on my page (as shown in the above link), but changing the sidebar from being "fixed" via CSS causes the page to jump when scrolling down the page using the mouse wheel.

The issue goes away if the sidebar is changed back to "fixed", but then the sidebar appears at the top of the site:

![joxi_screenshot_1513263185863](https://user-images.githubusercontent.com/11498904/33998127-8a2dda38-e0de-11e7-9264-cbff6d10e1e6.png)

**Comment by RomanGotsiy** [comment]
@scottybo this is a ReDoc bug. You can workaround it by removing: 

position: relative from the section containing ReDoc:
```css
#cs-content  #x-section-3 .x-container {
   position: static;
}
```
and removing your hack to make sidebar alway `abolute`.

**Comment by scottybo** [comment]
Great, thank you!

**Comment by scottybo** [comment]
Hm, that doesn't seem to work - any other ideas?

**Comment by RomanGotsiy** [comment]
This should work. I have tested it personally on your site and it worked just fine.

**Comment by RomanGotsiy** [comment]
@scottybo do you need help with fixing this?

**Comment by RomanGotsiy** [comment]
Closing as inactive
feel free to reopen!

**Comment by scottybo** [comment]
sorry, missed your reply - it's still an issue and it'd be great to have a fix :)

**Comment by galz** [comment]
@scottybo - looking at your documentation page, seems like you fixed it? Can you share how - I am seeing the same problem...
Thanks!
