### ISSUE TITLE
Hide the "Download OpenAPI specification" button.

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Rebilly/ReDoc#394]
Is there an easy way to hide this button/functionality? We don't want to expose this option to our users.

**Comment by shreyas-agnihotri** [comment]
Would be ideal if this could be specified as a tag attribute.
<redoc spec-url='swagger.yaml' no-download-openapi lazy-rendering>

**Comment by bartfeenstra** [comment]
Would you be able to apply some custom CSS to hide it?

As someone who has consumed many third-party APIs I do appreciate being able to easily download specs so my code can use it too, though :)

**Comment by willvincent** [comment]
There aren't enough classes to really write a "good" css selector but this seems to work, at least in the new 2.0 alpha version, I don't have the prior version handy to see if the markup is the same.

```
  .api-content .api-info > p {
    display: none !important;
  }
```

Agree, there really needs to be a config option to disable rendering of the button entirely. For my current usage, we have a private API that we control access to the docs via user login, since our api changes over time and is private, we don't want anyone downloading it.

**Comment by RomanGotsiy** [comment]
@willvincent @bartfeenstra thanks for answering.

I will definitely add a config option to hide this button.

**Comment by adamaltman** [comment]
It seems that even if the button is hidden, the spec still downloads to the browser, if that's what the page uses to render the docs.  So, the user is still capable of saving it, if that's what they are after doing.

**Comment by shreyas-agnihotri** [comment]
I guess just hiding the button would be fine for most people.

**Comment by RomanGotsiy** [comment]
New option will be added in the upcoming `redoc@1.21.0` - `hide-download-button`

Usage:

```html
<redoc spec-url="..." hide-download-button> </redoc>
```

**Important**: THIS **DOESN'T** MAKE YOUR SPEC PRIVATE! As @adamaltman mentioned, the spec still downloads to the browser so the user is still capable of saving it.

**Comment by RomanGotsiy** [comment]
Released in `1.21.0`

**Comment by MikeChristensen** [comment]
This doesn't seem to work when using the React component.

```
render() {
  return (
    <div>
      <RedocStandalone specUrl="/Specs/home.yaml" hide-download-button />
    </div>
  );
```

**Comment by MikeChristensen** [comment]
Figured it out:

```
<RedocStandalone specUrl="/Specs/home.yaml" options={{ "hideDownloadButton": true }} />
```

**Comment by levpachmanov** [comment]
if you are using the cli you can use `--options='{"hideDownloadButton": true}'`

**Comment by sionlane** [comment]
Can anyone confirm where this option should be added/defined?

I added it here in the redoc.html file within /templates

<script src="/script/redoc.standalone.js"> </script>
  </body>
  <script language="JavaScript">
    Redoc.init(
      '/{{documentationId}}/apispec',
      {
        nativeScrollbars: true,
        noAutoAuth: true,
        requiredPropsFirst: true,
        hideHostname: true,
        hideSchemaTitles: true,
        menuToggle: true,
        pathInMiddlePanel: false
        hideDownloadButton: true 
	  },
      document.getElementById('redoc-container'));
  </script>

And the redoc pages no longer rendered!

**Comment by adamaltman** [comment]
@sionlane I think you're missing a comma after `pathInMiddlePanel: false,`.

**Comment by sionlane** [comment]
great, thanks

**Comment by Taoshan98** [comment]
is it possible to hide the "Download" button from the .yaml file?

**Comment by Brian-Webster** [comment]
If you need your spec to be private, you can use redoc to render the spec offline, save the resulting output, and then host only that output.

**Comment by hadpro24** [comment]
> New option will be added in the upcoming `redoc@1.21.0` - `hide-download-button`
> 
> Usage:
> 
> ```
> <redoc spec-url="..." hide-download-button> </redoc>
> ```
> 
> **Important**: THIS **DOESN'T** MAKE YOUR SPEC PRIVATE! As @adamaltman mentioned, the spec still downloads to the browser so the user is still capable of saving it.

Thank you

**Comment by vfa-tanna** [comment]
hideDownloadButton: true not working with me?

**Comment by thibleroy** [comment]
@vfa-tanna use theme.openapi.hideDownloadButton parameter, available on build-docs
example : `redocly build-docs spec.yaml --output=spec-front.html --template redoc-template.html  --theme.openapi.hideDownloadButton`
