### ISSUE TITLE
Discriminator doesn't work if split to several files

### ISSUE THREAD

**Issue by Sorix** [Rebilly/ReDoc#399]
ReDoc doesn't support `discriminator` if yaml file split on several files. For example I placed model to separate `model.yaml` file, if I use `discriminator` in that file ReDoc throws an error and doesn't render anything:

> [Error] ERROR – Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 't.charAt')

I have attached test yaml files to gists: https://gist.github.com/Sorix/1a22ee5b7c7b19bf613c3ac61e3a3852, so you can easily reproduce that error.

[→ Show JS error log](https://github.com/Rebilly/ReDoc/files/1580679/Console.txt)

Tested on 1.x & 2.x versions.

**Comment by RomanGotsiy** [comment]
The way you use discriminator is against [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism):
![image](https://user-images.githubusercontent.com/3975738/34340119-ac45d23c-e986-11e7-9298-8266308b525d.png)

You can workaround this by referencing remote schemas from definitions sections:

```yaml
swagger: '2.0'
info:
  version: "0.1"
  title: Test API
host: example.com
basePath: "/"
schemes:
  - https
consumes:
  - application/json

paths:
  /test:
    get:
      summary: Test
      responses:
        200:
          description: OK
          schema:
            $ref: '#definitions/Answer'
definitions:
  Answer:
    $ref: './model.yaml#/Answer'
```

I will close this issue, feel free to continue discussion here though
