### ISSUE TITLE
Path parameters are not correctly overriden

### ISSUE THREAD

**Issue by axnsan12** [Rebilly/ReDoc#400]
Hello,

According to the swagger specification, parameters can be defined both at the [operation level](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) and at the [path item level](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object), where parameters redeclared in Operation must override the ones in the path.

Redoc currently fails to handle this, and displays both parameters.

Example spec:

```yaml
swagger: '2.0'
info:
  title: Path parameter test
  version: v1
paths:
  '/snippets/{id}/':
    delete:
      operationId: snippetsDelete
      description: delete method docstring
      parameters:
        - name: id
          in: path
          description: Operation-level parameter override
          required: true
          type: string
      responses:
        '204':
          description: ''
      consumes:
        - application/json
      tags:
        - snippets
    parameters:
      - name: id
        in: path
        description: Path-level parameter
        required: true
        type: integer

```

Result:

![image](https://user-images.githubusercontent.com/6382979/34712353-d54e148a-f522-11e7-8909-c99783487cef.png)

If you paste the example on https://editor.swagger.io/, you will see that it is handled correctly.

**Comment by RomanGotsiy** [comment]
@axnsan12 good catch! thanks. Will be fixed in the upcoming release
