### ISSUE TITLE
Trying to run the demo but get this error

### ISSUE THREAD

**Issue by work3t** [Rebilly/ReDoc#405]
[at-loader] Checking finished with 7 errors
[at-loader] ./lib/bootstrap.ts:4:36 
    TS2307: Cannot find module '../compiled/lib/app.module.ngfactory'. 

[at-loader] ./lib/services/menu.service.ts:393:25 
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/122server/Documents/redoc/ReDoc-master/node_modules/slugify/index"' has no compatible call signatures. 
When the demo page shows, It shows "Loading"...

In the console log I see the errors below. What shall I do to load the demo page successfully?

[at-loader] ./lib/services/search.service.ts:89:23 
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/122server/Documents/redoc/ReDoc-master/node_modules/slugify/index"' has no compatible call signatures. 

[at-loader] ./lib/utils/md-renderer.ts:64:16 
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/122server/Documents/redoc/ReDoc-master/node_modules/slugify/index"' has no compatible call signatures. 

[at-loader] ./lib/utils/spec-manager.ts:74:27 
    TS2339: Property 'protocol' does not exist on type '{}'. 

[at-loader] ./lib/utils/spec-manager.ts:74:47 
    TS2339: Property 'protocol' does not exist on type '{}'. 

[at-loader] ./lib/utils/spec-manager.ts:82:46 
    TS2339: Property 'host' does not exist on type '{}'.

**Comment by ilMattion** [comment]
Hi, I've the same problem. There is my open issue #402 .

**Comment by RomanGotsiy** [comment]
The error should not appear on the latest master.
Please verify. Thanks.

**Comment by RomanGotsiy** [comment]
Closing as stale
