### ISSUE TITLE
Markdown code-block not working on IE 11

### ISSUE THREAD

**Issue by krishna-vempati** [Rebilly/ReDoc#406]
My swagger documentation contains ``` to illustrate code examples, which are not necessarily related to API operations.

The code examples render well on Chrome, Firefox or Safari. However, the rendering fails on IE 11 with the following error:

<img width="677" alt="screen shot 2018-01-12 at 2 05 17 pm" src="https://user-images.githubusercontent.com/513261/34891200-a6bec6c8-f7a2-11e7-96ab-554ef1fdc313.png">

![image](https://user-images.githubusercontent.com/513261/34891210-b4d1d82c-f7a2-11e7-95bd-68524e2e0188.png)

I am using v1.19.3 to render the documentation. IE version is `11.0.9600.18817`.

If there is a workaround to move the code sample to the third column, I can live with that :) Thanks.

![screenshot_1](https://user-images.githubusercontent.com/513261/34891475-bca5549c-f7a3-11e7-990b-e6e56785af35.png)

**Comment by zeroorone13** [comment]
We have experienced the same issue. The bug in IE11 appears to be caused by using the `parentElement` function in the `HTMLEscape` method (https://github.com/Rebilly/ReDoc/blob/master/lib/utils/md-renderer.ts#L11). Using `parentNode` appears to resolve the issue.

**Comment by RomanGotsiy** [comment]
@krishna-vempati thanks for the bug report.
@zeroorone13 thanks so much for investigating this!

I will release a new package soon.

**Comment by krishna-vempati** [comment]
Awesome! Thank you so much. I see you have released 1.20.0 already.
