### ISSUE TITLE
"example" doesn't work for array.

### ISSUE THREAD

**Issue by hpatoio** [Rebilly/ReDoc#408]
I've this definition

```
{
  "name": "category_in",
  "in": "query",
  "description": "Filter by category | Category code need to be passed",
  "required": false,
  "type": "array",
  "items": {
      "type": "string",
      "example": [
         "cat1-code,cat2-code",
         "cat3-code"
      ]
  },
  "collectionFormat": "csv"
},
```

But examples are not rendered in the doc. This is what I get

![image](https://user-images.githubusercontent.com/249948/35052891-fcfcbcde-fba8-11e7-8024-dfbaf79a72b3.png)

Is the definition wrong or am I missing something ?

**Comment by RomanGotsiy** [comment]
Your definition is completely OK. It's a ReDoc issue.
Thanks for reporting.
