### ISSUE TITLE
[react-rewrite] port "copy to clipboard" /  "expand/collapse all" functionality

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#410]

**Comment by joshprice** [comment]
Would love to try this out but am having issues installing the HEAD of the react-rewrite branch using yarn.

    yarn add "https://github.com/Rebilly/ReDoc.git#react-rewrite"

This appears to install correctly (although I have 2 copies of redoc unless I explicitly remove the alpha-10 version). But I keep getting:

    Module not found: Can't resolve 'redoc' in '<my-app>/src'

Any idea what I might be doing wrong? When are you likely to release a new alpha version?

Thanks!

**Comment by RomanGotsiy** [comment]
It has been resolved a day earlier by https://github.com/Rebilly/ReDoc/commit/5bb0bdfd2967347430e4b2a93089c52437051440.
Sorry didn't see your comment and forgot to close this issue.

If you decide to contribute in the future, please refer to [CONTRIBUTING.md](https://github.com/Rebilly/ReDoc/blob/react-rewrite/.github/CONTRIBUTING.md) for dev instructions

Thanks!
