### ISSUE TITLE
The <redoc> element violates custom elements specification

### ISSUE THREAD

**Issue by ibnesayeed** [Rebilly/ReDoc#419]
According to the HTML Custom Elements specification, every custom element must contain at least one hyphen (`-`) sign in its name. Here is the relevant part of the grammar under the [Core Concepts](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts) section.

```
PotentialCustomElementName ::= [a-z] (PCENChar)* '-' (PCENChar)*
```

And here is the relevant note describing the reasoning behind it.

> They contain a hyphen, used for namespacing and to ensure forward compatibility (since no elements will be added to HTML, SVG, or MathML with hyphen-containing local names in the future).

This restriction is not new, it has been there since its early drafts.

**Comment by RomanGotsiy** [comment]
ReDoc has been rewritten to React and using <redoc> tag is just backward compatibility now.

Closing this issue.
Feel free to continue the discussion here!
Thanks!
