### ISSUE TITLE
How to display only required parameters in the sample request?

### ISSUE THREAD

**Issue by antondomih** [Rebilly/ReDoc#424]

**Comment by RomanGotsiy** [comment]
@antondomih, there is no way to do this at the moment.
Feel free to open PR and add this option, e.g. with the name `only-required-in-samples`.

tip: this will also require changes in [`openapi-sampler`](https://github.com/APIs-guru/openapi-sampler)

**Comment by exoego** [comment]
I think this issue can be closed since #646 introduced the feature.

**Comment by RomanGotsiy** [comment]
@exoego right! Thanks!
