### ISSUE TITLE
Source map not available

### ISSUE THREAD

**Issue by unional** [Rebilly/ReDoc#425]
While we can use this to get the script:
https://rebilly.github.io/ReDoc/releases/v1.x.x/redoc.min.js

Source map does not exist:
https://rebilly.github.io/ReDoc/releases/v1.x.x/redoc.min.map

Is there a way to get the source map for each release?

**Comment by RomanGotsiy** [comment]
Unfortunately, source maps are not deployed to our github pages-based CDN and it will be deprecated soon.

But you can use ReDoc from unpkg which has source maps: `https://unpkg.com/redoc@1.21.2/dist/redoc.min.js` and source-map `https://unpkg.com/redoc@1.21.2/dist/redoc.min.map`
