### ISSUE TITLE
Angular 5 rerender issue

### ISSUE THREAD

**Issue by parajanoff** [Rebilly/ReDoc#428]
Hi,

Is Angular 5 properly supported? I did the following: 

1. Installed redoc npm package.
2. Imported RedocModule.
3. Created a new Angular component and created html like this: 

`<redoc spec-url='SCHEMA_URL'></redoc>`

During the first redirection to the page Redoc is properly initialized and rendered.

**ISSUE**: When revisiting the page, Redoc is partially initialized and navigation pane is greyed out with no errors. See attached screenshot.
<img width="716" alt="screen shot 2018-02-28 at 6 30 12 pm" src="https://user-images.githubusercontent.com/8421486/36818988-78620820-1cb5-11e8-9e00-43a65263b39e.png">

**Comment by parajanoff** [comment]
@RomanGotsiy Hi Roman, thanks for your response and sorry for my late one... been busy.

I'm not able to setup a repo with a minimal reproducible sample at the moment. We got a workaround with iframe + JS initialization which works OK for now, but eventually, this should be changed to a proper way.

I hope community will help with the sample sooner than I will.

**Comment by RomanGotsiy** [comment]
Thanks, @parajanoff,

Great you found a workaround!

ReDoc has been rewritten to React since version 2.0.0-alpha.x and 1.x version will receive only critical bug fixes.
