### ISSUE TITLE
Feature Request: add tags/x-title

### ISSUE THREAD

**Issue by unional** [Rebilly/ReDoc#430]
The `tags/name` is used both as a reference key (`tags: [<tag name>]) as well as text to be displayed on the sidebar and the content.

This mix usage prevents i18n.

I would suggest to add `tags/x-title` and use it for display instead of the name.

This would be a solution for redoc, but I also think that it can also be fixed at OpenAPI by allowing `tags: ['string' | 'Reference']`

**Comment by RomanGotsiy** [comment]
Redoc already has this functionality just with different name: [`x-displayName`](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-displayname)
