### ISSUE TITLE
BUG: Same comments for different properties of same type

### ISSUE THREAD

**Issue by ptricak** [Rebilly/ReDoc#432]
Hi,
I've got a response object which have properties of the same type /it is a custom object/, which already have a different comments - I can see this comments correctly in generated json file but when using this JSON in ReDoc, all properties have same comment like there is within the first property.

![image](https://user-images.githubusercontent.com/28383954/37022134-505933c8-2122-11e8-837a-c9a3a21fb015.png)

Many thanks for response.

**Comment by RomanGotsiy** [comment]
which version of ReDoc do you use? Could you share your spec or minimal reproducible sample?

**Comment by ptricak** [comment]
Hi Roman,
I've attached simplified documentation json file. As you can see on screen bellow, this json file contains comments of properties in correct form, but in generated ReDoc documentation it's incorrect. 
![image](https://user-images.githubusercontent.com/28383954/37092964-fb790fd0-220d-11e8-97e6-bcfd1f04108a.png)

Json file with documentation:

[swagger_example.zip](https://github.com/Rebilly/ReDoc/files/1789177/swagger_example.zip)

**Comment by RomanGotsiy** [comment]
by spec `$ref` overwrites the content of the object it is placed in.
To fix this in your spec use the following trick with `allOf`:

```json
"resolvedBy": {
  "allOf": [
	{ "$ref": "#/definitions/UserResponseDTO" },
    { "description": "Alternative description" }
  ]
}
```
