### ISSUE TITLE
Scroll not working

### ISSUE THREAD

**Issue by FrantisekVrab** [Rebilly/ReDoc#433]
Hi,

first, I have installed Redoc from cdn. Alsto I installed gem https://github.com/krsyoung/redoc-rails on Rails 4 with Turbolinks 5. In both tries everything works except the scroll after the click on the menu, or menu highlighting menu items when scrolling.

Can you assist how to proceed? Thanks.

**Comment by RomanGotsiy** [comment]
How can I reproduce this? could you create a minimal reproducible sample?
Would be great if you created a repo with all the setup.

@krsyoung, maybe you can help out.
@FrantisekVrab try also the new version of redoc-rails with updated ReDoc. Maybe the issue will be resolved.

**Comment by RomanGotsiy** [comment]
@FrantisekVrab did you solve the issue?

**Comment by FrantisekVrab** [comment]
Hi, I have also used a redoc-rails, however with no success. There was no error message.

Later I found that problem is probably that we are using a jQuery, jQuery-rails and turbolinks on the site an that's in conflict with the Angular that redoc is build on. I wasn't able to debug this.

So I have moved to the non-rails application and everything works.

**Comment by RomanGotsiy** [comment]
Thanks for the update! Closing this issue.

**Comment by bmxkakw** [comment]
In case somebody's still in trouble:
`html {
    scroll-behavior: smooth;
}`
broke scrolling of Redoc document for me.

**Comment by thefolake** [comment]
Remove
 html{
 scroll-behavior: smooth;
}
and you are good to go.
