### ISSUE TITLE
CSS seems to be broken in the recent commits

### ISSUE THREAD

**Issue by vikrantk365** [Rebilly/ReDoc#438]
I'm exploring redoc's `react-rewrite` renderer.
It looks great.
Although in recent commits after alpha-12, css seems to be broken a bit.
(Background-color for Response line and enum)
PFA screenshot
![petstore-redoc](https://user-images.githubusercontent.com/5028204/37535993-4399a556-2941-11e8-9e87-4be923faecba.png)

**Comment by RomanGotsiy** [comment]
@vikrantk365 thanks for reporting!
Now fixed by https://github.com/Rebilly/ReDoc/commit/6018042180a48564ee04b3762a2fbcfe2842f44c

New release will be ready in a few minutes
