### ISSUE TITLE
Attribute type css color too light

### ISSUE THREAD

**Issue by vikrantk365** [Rebilly/ReDoc#439]
I'm trying https://unpkg.com/redoc@2.0.0-alpha.16/bundles/redoc.standalone.js
In that, the color of the attribute type (string,object) is too light.
PFA
![redoc-attribute-type-css](https://user-images.githubusercontent.com/5028204/37658242-011e722c-2c45-11e8-8915-a1b58b075041.png)

**Comment by RomanGotsiy** [comment]
Fix will be shipped in the next alpha.
Thanks for reporting!

**Comment by vikrantk365** [comment]
Thanks
