### ISSUE TITLE
CLI watch mode does not work reliably with Vim

### ISSUE THREAD

**Issue by robertknight** [Rebilly/ReDoc#444]
When the `--watch` mode is enabled in `redoc-cli`, the CLI fails to notice when I make edits to the spec file using Vim.

I do not experience the issue if I turn off the `writebackup` option (see https://stackoverflow.com/a/607475/434243) or if I edit the spec file in Atom.

**Steps to reproduce:**

1. Run `redoc-cli --watch <path to spec>`
2. Edit the spec file in Vim and save changes

**Expected:** redoc-cli notices changes and rebuilds docs
**Actual:** redoc does not see the change

System: macOS 10.13.3, Vim 8.0

A search for "vim file save fs.watch" turns up a bunch of related issues. It looks like `fs.watch`'s interaction with how Vim saves files causes problems for a bunch of other tools too.

**Comment by mes3yd** [comment]
This is fixed on Linux. Can you confirm/deny it is working for you on macOS?

**Comment by robertknight** [comment]
This is working for me now with redoc-cli v0.7.0 on macOS 10.14 with Node 10.11. Thank-you!
