### ISSUE TITLE
What are the pre-requisites required for installing redoc on Windows

### ISSUE THREAD

**Issue by shahamit** [Rebilly/ReDoc#445]
I am trying to install redoc on my windows 10 machine. On trying to execute the npm command, I get the below error

`Error: Can't find Python executable "C:\Program Files\Python3\python.exe", you can set the PYTHON env variable`

The complete log file is pasted [here](https://paste.ee/p/sTpJN).
I have the latest python installed (version - 3.6.5) with both the PYTHON & PATH variables updated. Despite it I get the above error.

Could some one please guide me through the installation?

Thanks!

**Comment by RomanGotsiy** [comment]
Looks like this should be fixed on the latest version since it has been fixed in the dependency: https://github.com/siddharthkp/bundlesize/pull/214/files

Please, feel free to reopen in case the error still happens
