### ISSUE TITLE
IE 11-incompatible APIs

### ISSUE THREAD

**Issue by fritz-c** [Rebilly/ReDoc#448]
I found instances of the following two IE 11-incompatible APIs being used in the source code:
* `String.prototype.endsWith`
* `Math.trunc`

They can be replaced without too much effort, and I'm willing to create a pull request doing so, but it may take me a while to get the time to do so. What would you suggest I do?

**Comment by RomanGotsiy** [comment]
@fritz-c just add specific polyfills from 'core-js' [here](https://github.com/Rebilly/ReDoc/blob/master/src/polyfills.ts). Or I can do this.

**Comment by fritz-c** [comment]
So is this polyfill not applied in the alpha version? Using the alpha version, I was getting the following error displayed in place of the component:
![image](https://user-images.githubusercontent.com/4413963/38185955-76e66406-368b-11e8-8815-640fe39d7598.png)

**Comment by RomanGotsiy** [comment]
I will check it out. It's strange

**Comment by fritz-c** [comment]
Thank you. Let me know if I can provide any more information.

**Comment by jemerald** [comment]
Also getting the errors

![image](https://user-images.githubusercontent.com/9168432/38967131-c07d0876-43d9-11e8-8fbf-739f8b354ae1.png)

The `'Promise' is undefined` error happens on page load.
The `trunc` error happens when scrolling up.

I'm using the "next" release `https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js`

**Comment by sam666666** [comment]
Got the same problem. For Math.trunc i found that you can add this to your index.html and it seems to fix it but i still dont have a fix for the promise.

FYI i'm using the standalone version.

```
<script>
        Math.trunc = Math.trunc || function (x) {
    if (isNaN(x)) {
        return NaN;
    }
    if (x > 0) {
        return Math.floor(x);
    }
    return Math.ceil(x);
};
</script>
```

**Comment by jemerald** [comment]
@RomanGotsiy why is this closed? The same problem is still happening in the latest alpha.23 release...
