### ISSUE TITLE
Discriminator broken in referenced file

### ISSUE THREAD

**Issue by countergram** [Rebilly/ReDoc#449]
I have a use case very similar to the discriminator in the pet example, and also tried to split it into multiple files with $ref. Eventually I figured out that the bundle function in json-schema-ref-parser only transforms $ref values, and the "refs" under a discriminator do not have $ref as their key, so they do not get transformed and become invalid.

**Comment by RomanGotsiy** [comment]
Closing as stale.
Feel free to continue discussion here

**Comment by trajano** [comment]
Seems to be the same issue as https://github.com/Rebilly/ReDoc/issues/862
