### ISSUE TITLE
Showing 3 panes on smaller viewports

### ISSUE THREAD

**Issue by arnonzooz** [Rebilly/ReDoc#450]
Hello!

Is there a way I can show a 3-pane output, also on smaller screens? Attached a screenshot from my MacBook screen. I would like the Request Samples area to appear as a third pane on the right, but I cannot seem to influence this (on larger screens it appears correctly).

<img width="1259" alt="screen shot 2018-04-03 at 9 01 14" src="https://user-images.githubusercontent.com/37036454/38231979-c5166b20-371d-11e8-80d1-766ec0549c9a.png">

Thanks!

Arnon

**Comment by arnonzooz** [comment]
Thank you! Works like a charm.

**Comment by IamVman** [comment]
> Thank you! Works like a charm.

What value did you set for medium breakpoint? I tried different values, yet couldn't get it working.
My code as follows - 
```
Redoc.init(url,{
          breakpoints: {
            medium: '70rem'
          }
        });
```

**Comment by arjunsk** [comment]
If you are looking for `redoc-cli` command

`redoc-cli serve --options.theme.breakpoints.medium=70rem swagger.yaml`
