### ISSUE TITLE
Request sample does not appear when using allOf + 2 schemas with required fields

### ISSUE THREAD

**Issue by bcharna** [Rebilly/ReDoc#460]
I have two OpenAPI specs that are very similar, except one has an allOf where both schemas in the allOf specify required fields, and the other OpenAPI spec has an allOf, but only one schema under it (thus in this case the allOf is not really needed).

A) Only one schema in the allOf:
[Raw JSON](https://gist.githubusercontent.com/bcharna/6f3843a3c954bb6839625cdfa291fb37/raw/283403949e222cf51e202a924bf46ac140bd775b/no_require_in_second_schema.json)
[ReDoc link](http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/bcharna/6f3843a3c954bb6839625cdfa291fb37/raw/283403949e222cf51e202a924bf46ac140bd775b/no_require_in_second_schema.json&nocors)

B) Two schemas in allOf, both with required fields:
[Raw JSON](https://gist.githubusercontent.com/bcharna/30e4c6ae6c8bcc56b66bf2f8541d1646/raw/bb924f65b0c8b7af657f8e8df179101e3214e1bd/require_in_second_schema.json)
[ReDoc link](http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/bcharna/30e4c6ae6c8bcc56b66bf2f8541d1646/raw/bb924f65b0c8b7af657f8e8df179101e3214e1bd/require_in_second_schema.json&nocors)

Notice how the request sample appears correctly in A, but appears as `{}` in B. I am new to OpenAPI, but it seems that my specs are indeed correct as this issue does not surface in SwaggerUI. Also note that the request parameters appear fine in ReDoc, it's just the request sample that is broken for B.

**Comment by cmeeren** [comment]
I just experienced this myself. However, I added more properties in the second `allOf` item, and the sample only included properties from the second `allOf` item. So it seems the samples are only be generated based on the last `allOf`, and not the combined schema (as is correctly done in the middle column).

**Comment by RomanGotsiy** [comment]
Thanks for such a detailed issue-report ❤️!

Fixed by updating openapi-sampler dependency in https://github.com/Rebilly/ReDoc/commit/3698598d607ce0136ea5ddadc35dc63f1822e0d7

This will be released in the next version of ReDoc: 2.0.0-alpha.22
