### ISSUE TITLE
Download button just opens a new tab with same viewer

### ISSUE THREAD

**Issue by auahmed** [Rebilly/ReDoc#462]
So i was using RedocStandalone from redoc and passing it a specUrl with the actual json swagger content for the content but when i click the download button, i dont get the yaml or json downloaded.
It just opens a brand new tab with the same window. 

Also is there any way of hiding the search option on the left panel?

````js
<RedocStandalone specUrl={this.props.selectedDefinition} />
````

**Comment by RomanGotsiy** [comment]
Which browser are you using? Could you set up a minimal reproducible sample?
Thanks

**Comment by samallisonds** [comment]
I get the same thing, but I'm passing in the spec directly (having loaded it earlier from an api).

`<RedocStandalone spec={this.state.swagger}`

It happens in both Chrome and Edge

**Comment by fogine** [comment]
This might be caused by incorrect routing rules of your back-end server which is responsible for serving the files.
