### ISSUE TITLE
Weird text for No content response icon

### ISSUE THREAD

**Issue by vikrantk365** [Rebilly/ReDoc#463]
PFA screenshots.
![screenshot2](https://user-images.githubusercontent.com/5028204/38998170-ea04e60c-43e6-11e8-87e9-9bdad62e285c.png)
![screenshot1](https://user-images.githubusercontent.com/5028204/38998173-eacfebcc-43e6-11e8-8795-68bf1bf178a4.png)

**Comment by RomanGotsiy** [comment]
add 

```html
  <meta charset="UTF-8" />
```

to the head section of you HTML
