### ISSUE TITLE
Model Composition not working

### ISSUE THREAD

**Issue by JLNNN** [Rebilly/ReDoc#464]
Hey, when trying to combine $ref and additional properties (examples) like valid in the [OAS3](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) "Model Composition", this is not working correctly I think. Can you please check this?

[Here's an example](https://gist.github.com/JLNNN/5988f37e76f4d897db25a70b728d64b7) of the API spec I'm using.

If I'm posting the same yaml file into the [Swagger Editor](http://editor.swagger.io/), it's working fine.

== Update 2018-04-20 ==
This is the correct result when loading the yaml into swagger editor:
![bildschirmfoto 2018-04-20 um 09 35 40](https://user-images.githubusercontent.com/1099235/39036817-ff94182e-447e-11e8-9d65-b1b842d820cf.png)

This is the result I get when using ReDoc:
![bildschirmfoto 2018-04-20 um 09 36 40](https://user-images.githubusercontent.com/1099235/39036833-09f8a8ac-447f-11e8-9f75-26143364bd87.png)

It would be really nice if ReDoc is able to merge $ref values with example values.

Greetings from Germany,
  Julian

**Comment by RomanGotsiy** [comment]
Redoc behavior valid according to the spec. `example` field is 

> A *free-form* property to include an example of an instance for this schema

according to the spec. Treating it as a schema (with `allOf`) may break things for users who want an explict allOf property in the example.
