### ISSUE TITLE
ReDoc install issue on windows

### ISSUE THREAD

**Issue by areebaasad77** [Rebilly/ReDoc#471]
I am trying to install and run ReDoc on windows but it is giving me the below error. I have already installed the latest version of npm and python:

51882 warn babel-loader@7.1.2 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.
51883 warn ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
51884 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules\fsevents):
51885 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
51886 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
51886 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
51886 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
51886 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
51887 verbose stack Error: iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
51887 verbose stack Exit status 1
51887 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
51887 verbose stack     at EventEmitter.emit (events.js:180:13)
51887 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
51887 verbose stack     at ChildProcess.emit (events.js:180:13)
51887 verbose stack     at maybeClose (internal/child_process.js:936:16)
51887 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
51888 verbose pkgid iltorb@1.3.10
51889 verbose cwd C:\Users\Areeba.Asad\Redoc
51890 verbose Windows_NT 10.0.16299
51891 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
51892 verbose node v9.10.1
51893 verbose npm  v5.6.0
51894 error code ELIFECYCLE
51895 error errno 1
51896 error iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
51896 error Exit status 1
51897 error Failed at the iltorb@1.3.10 install script.
51897 error This is probably not a problem with npm. There is likely additional logging output above.
51898 verbose exit [ 1, true ]

**Comment by RomanGotsiy** [comment]
Could you please verify with the latest version! thanks!

**Comment by RomanGotsiy** [comment]
closing as stale
