### ISSUE TITLE
Use of hint.css / ReDoc is incorrectly licensed

### ISSUE THREAD

**Issue by rickity-cricket** [Rebilly/ReDoc#478]
Hi there, (@RomanGotsiy)

Looking at your pre-v2.0.0 releases, you are using a component called hint.css. This component is licensed with a strong copyleft AGPL v3. This means ReDoc has [no choice but to use the same license](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) or else to remove hint.css entirely.

Were you aware of this issue? Would you be willing to remove the dependency?
Any thoughts?

Thank you for your attention,

rickity-cricket

**Comment by RomanGotsiy** [comment]
I just checked and I am using version 2.3.2. of hint.css which was licensed under MIT: https://github.com/chinchang/hint.css/tree/v2.3.2

They switched to AGPL v3 since version 2.4.0 so ReDoc use of hint.css is absolutelly legal.

**Comment by rickity-cricket** [comment]
Oh! Good spot :)

Thanks for the reactivity!

**Comment by rickity-cricket** [comment]
I was reading here: https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json 

The caret (^) resolves the ^2.3.2 to the latest version of 2.x.x, so I think just removing the caret would solve the licensing issue... @RomanGotsiy , what do you think?

**Comment by RomanGotsiy** [comment]
Yes, I just noticed this too 😞 

I just pinpointed hint.css to 2.3.2: https://github.com/Rebilly/ReDoc/commit/a966b1fee2a100692b53b3352ffd302e13b8edc7

Will build 1.22.0 release of ReDoc ASAP

**Comment by RomanGotsiy** [comment]
Released `1.22.0`

**Comment by rickity-cricket** [comment]
@RomanGotsiy I can't see the new version/tag, but maybe it takes some time? I will check back. Thanks again for the quick reaction
