### ISSUE TITLE
Is it possible to sent request(like "Try it out") from UI, and get response in UI?

### ISSUE THREAD

**Issue by harutyunyan-vahe** [Rebilly/ReDoc#489]
Is it possible to sent request(like "Try it out") from UI, and get response in UI ?

If not, then is is possible to add that new feature, it is very useful  and that feature exist in other swaggerui s

**Comment by ajermaky** [comment]
I believe you are referring to the API Console

you can follow the thread open on this issue: https://github.com/Rebilly/ReDoc/issues/53

**Comment by RomanGotsiy** [comment]
Closing as a duplicate
Thanks @ajermaky

**Comment by wll8** [comment]
Try [redoc-try](https://github.com/wll8/redoc-try), use `swagger Try it out` in` redoc` project.

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_WX20200518-152825.png)
