### ISSUE TITLE
Prism CSS global styles conflict with existing Prism CSS

### ISSUE THREAD

**Issue by jonavila** [Rebilly/ReDoc#491]
I noticed that prism's dark theme is used with Redoc and it overrides existing Prism styles on my site. Is there a way Redoc can avoid using `injectGlobal`?
https://github.com/Rebilly/ReDoc/blob/0d6deff8c8477a72f5d3229aae21c0b705bd801c/src/utils/highlight.ts#L24

**Comment by RomanGotsiy** [comment]
Thanks for bug report. I will investigate this. I think I can omit `injectGlobal` usage!
