### ISSUE TITLE
Payload json body is wrong example for array

### ISSUE THREAD

**Issue by ntloi95** [Rebilly/ReDoc#494]
In request body schemas, I have an array of string field. 
But in payload, it's show only a string.

**Comment by ntloi95** [comment]
This is error field.
![image](https://user-images.githubusercontent.com/9493402/40102456-c08004a4-5914-11e8-9aee-64d1e72c9246.png)
This is payload json
![image](https://user-images.githubusercontent.com/9493402/40102476-cf2b9edc-5914-11e8-814f-c3385a9bc5ef.png)
This is full schemas
![image](https://user-images.githubusercontent.com/9493402/40102519-eda3d474-5914-11e8-848e-f74f5a262501.png)

**Comment by RomanGotsiy** [comment]
Thanks, could you also share the corresponding definition spec/schema ?

**Comment by ntloi95** [comment]
So sorry, I click to close button because of mistake.
This is definition. I remove some unnecessary things.
```
{
    "user": {
        "description": "User defines data model for User.",
        "properties": {
            "id": {
                "description": "The id of user.",
                "example": "Wu8LGFBgDAuDzFA8",
                "type": "string"
            },
            "integrations": {
                "description": "Array of fitness partners user may have connected to our app.",
                "example": [
                    "jawbone",
                    "underarmour"
                ],
                "items": {
                    "$ref": "#/components/schemas/integration"
                },
                "type": "array"
            }
        },
        "type": "object"
    },
    "userResponse": {
        "description": "UserResponse represents a response item for User.",
        "properties": {
            "id": {
                "description": "The id of user.",
                "example": "Wu8LGFBgDAuDzFA8",
                "type": "string"
            },
            "integrations": {
                "description": "Array of fitness partners user may have connected to our app.",
                "example": [
                    "jawbone",
                    "underarmour"
                ],
                "items": {
                    "$ref": "#/components/schemas/integration"
                },
                "type": "array"
            }
        },
        "type": "object"
    }
}
```

**Comment by ntloi95** [comment]
```
"responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/userResponse"
                }
              }
            },
            "description": "Update user success."
          }
```

**Comment by RomanGotsiy** [comment]
I can't reproduce your issue locally.

Could you share **a full** simplified schema on which this issue can be reproduced? You can upload it somewhere (e.g. gist) and put link to it into demo: http://rebilly.github.io/ReDoc/

And then share the demo-link here. Thanks!

**Comment by ntloi95** [comment]
Hi,
This is simplified schema I edited can reproduce bug.

https://raw.githubusercontent.com/ntloi95/hack/master/redoc-v6.json

![image](https://user-images.githubusercontent.com/9493402/40161963-8975361e-59dc-11e8-823e-34514e6f13e7.png)

**Comment by ntloi95** [comment]
This json can reproduce the bug.
https://raw.githubusercontent.com/ntloi95/hack/master/redoc-v6.json
![image](https://user-images.githubusercontent.com/9493402/40162025-c33588b8-59dc-11e8-847d-a2a09caa3643.png)

**Comment by RomanGotsiy** [comment]
You have an issue in your spec:

```js
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "properties": {
          "integrations": {
            "description": "Integrations",
            "enum": [ // <---- HERE
                "jawbone",
                "underarmour",
                "healthkit",
                "googlefit"
            ],
            "in": "body",
            "items": {
              "$ref": "#/components/schemas/integration"
            },
            "name": "integrations",
            "type": "array"
          }
        },
        "type": "object"
      }
    }
  },
  "required": true
```

Enum on this level according to the spec means that value of this field (`integrations` MUST be one of the enum values (strings) while field type is `array` so this schema is invalid.
If you need to specify possible values for items you should put `enum` inside `items`. But in your case, just remove enum as you anyway have same enum in `integration` definition

ReDoc is rendering your spec correctly

**Comment by ntloi95** [comment]
Remove "enum" is ok. ReDoc render correctly.
Thank you very much indeed.
