### ISSUE TITLE
Html element title issue

### ISSUE THREAD

**Issue by gerbil** [Rebilly/ReDoc#499]
Right now i can see only 'Test' and 'oops' titles on mouseover elements. How can i fix this?
BTW it's a common issue cause i can clearly see it on https://rebilly.github.io/RebillyAPI/ also

**Comment by RomanGotsiy** [comment]
Fixed by https://github.com/Rebilly/ReDoc/commit/6b1e8e75b030f5a19b5f8bb90438baac17f696c8
Will go into next release
