### ISSUE TITLE
Vendor extension suggestion: 'x-description-extended' for responses

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#500]
I sometimes need to write a lengthy explanation for a specific `response` (possibly with lists and other formatted text). AFAIK `description` is the only field for this, but a lengthy description here doesn't look too good with ReDoc - it seems like the response description is intended to be kept short.

Unless I'm missing an existing way to accomplish this, I suggest a simple vendor extension `x-description-extended` for `response` objects, functioning similarly to `description` except that the contents are placed "below the fold". See the image below for an example of where (roughly) I'd like it placed.

See the below image 

![image](https://user-images.githubusercontent.com/7766733/40442066-07e8e01e-5ec3-11e8-90d9-474dec2660a3.png)

**Comment by RomanGotsiy** [comment]
I think x-summary + description would be better.
I can change ReDoc to render only the first line of description in the button and the rest under
And if x-summary is provided, x-summary would be rendered in the button and description below.

What do you think?

**Comment by cmeeren** [comment]
I like `x-summary`, that's much better (especially since I suggested an official `summary` field in the OAS repo).

As for the first paragraph vs. the whole description, I'll leave that to you. I don't have any problem with the current behavior. If you choose to render the rest below, you should perhaps add an indicator that the sentence is incomplete (something like `...`).
