### ISSUE TITLE
alpha-20 has `tslib` removed from dependencies

### ISSUE THREAD

**Issue by carlovirtucio** [Rebilly/ReDoc#501]

**Comment by carlovirtucio** [comment]
I created a repository for this
https://github.com/carlovirtucio/redoc-bug-test

1. Run create-react-app
2. Add redoc to dependencies
3. Import redoc in App.js

Error occurs: Module not found: Can't resolve 'tslib' in '/Users/carlovirtucio/Desktop/Lab/bug-test/node_modules/redoc/bundles'

In package.lock.json, tslib does not seem to be added to redoc's dependencies. When downloading the latest .tar.gz from the Redoc releases and checking its package.json, tslib is not included.

I was able to replicate this while cleaning up my repo by deleting package-lock.json and node_modules then running `nom install` again for an audit.

**Comment by carlovirtucio** [comment]
I think this was already fixed, but a new release to include it would be great.
https://github.com/Rebilly/ReDoc/commit/8e1a5cb7a186f78584681370ef14209a3e58ded4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by RomanGotsiy** [comment]
Just released `2.0.0-alpha.21`

**Comment by carlovirtucio** [comment]
Thanks!
