### ISSUE TITLE
Vertical line under "response schema" misaligned on Firefox

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#503]
See the image. Looks fine on Chrome and Edge.

![image](https://user-images.githubusercontent.com/7766733/40470835-f5a997aa-5f34-11e8-8cfa-3dd32d23ae16.png)

**Comment by cmeeren** [comment]
This happens both for request and response schema. It happens for three or more parameters (two look fine).

**Comment by cmeeren** [comment]
I found out that the problem disappears if I disable the `border-collapse: collapse` rule for the relevant table. (I tried this in FF dev tools and have no idea what this translates to in the original source files.)

**Comment by RomanGotsiy** [comment]
Thanks for figuring it out! I will fix it!
