### ISSUE TITLE
Typeerror when I expand a field in a rendered OpenAPI 2.0 spec

### ISSUE THREAD

**Issue by imnotashrimp** [Rebilly/ReDoc#505]
I got this error when I expanded the `triggerOn` parameter in my OpenAPI 2.0 spec. Everything rendered normally, with no errors.

From my Chrome console:
```
TypeError: Cannot read property 'fields' of undefined
    at t.render (ObjectSchema.tsx:24)
    at x (mobx.module.js:235)
    at index.module.js:741
    at Mt (mobx.module.js:3277)
    at e.track (mobx.module.js:3481)
    at t.i [as render] (index.module.js:736)
    at t.<anonymous> (index.module.js:805)
    at t.c.render (index.module.js:923)
    at h (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
wr @ react-dom.production.min.js:151
```
![image](https://user-images.githubusercontent.com/6845404/40495447-e66eee3e-5f7f-11e8-8a23-2eea1ee14eee.png)

ReDoc v 2.0.0-alpha.20
Commit 0a9d09d

I use Redoc from the CDN- 
`<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>`

**Comment by RomanGotsiy** [comment]
Minimal reproducible sample?

**Comment by RomanGotsiy** [comment]
It doesn't matter. Whatever is better for you!

**Comment by imnotashrimp** [comment]
https://github.com/imnotashrimp/logz-docs-test/blob/develop/_source/api-src/logzio-public-api.yaml

The problem is when I expand `triggerOn` ([line 1788](https://github.com/imnotashrimp/logz-docs-test/blob/3d1a19ca269b8e352ea12843d8c33e7e1277a9b8/_source/api-src/logzio-public-api.yaml#L1788)), which references the `TriggerOn` definition ([line 1862](https://github.com/imnotashrimp/logz-docs-test/blob/3d1a19ca269b8e352ea12843d8c33e7e1277a9b8/_source/api-src/logzio-public-api.yaml#L1862))

**Comment by imnotashrimp** [comment]
Thank you! Our spec was auto-generated, so I'll look into this on our end as well.

Appreciate the help
