### ISSUE TITLE
Is jsDelivr being updated?

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#508]
Are you pushing to jsDelivr?

I just noticed the "oops" error, which was fixed 9 days ago in commit https://github.com/Rebilly/ReDoc/commit/6b1e8e75b030f5a19b5f8bb90438baac17f696c8, but when using `https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js` I still see the error.

**Comment by RomanGotsiy** [comment]
There was no new release yet. I will cut a new one later today

**Comment by RomanGotsiy** [comment]
Just released `2.0.0-alpha.21`
