### ISSUE TITLE
Add in-page search with result highlighting (feature request)

### ISSUE THREAD

**Issue by darklynx** [Rebilly/ReDoc#51]
It would be great to implement an in-page search with results highlighting similar to something available here: http://docs.fidor.de (just enter the word "unique" within the search input field and click on one of the found references)

If you look at http://docs.fidor.de/javascripts/all.js there are a lot of open source JavaScript libraries that helps to implement search and highlight the results, like: 
- http://lunrjs.com (full-text search)
- http://tartarus.org/~martin/PorterStemmer/js.txt (removes morphological and inflexional endings from words in English, see http://tartarus.org/~martin/PorterStemmer)
- http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html (text highlighting)
- and others

Looks like it is possible to implement an in-page search with support from those libraries that would add a lot of credits to the wonderful ReDoc project! This may become a killing feature of the project ;)

Thank you in advance!

**Comment by darklynx** [comment]
P.S. they are using https://github.com/gfranko/jquery.tocify.js for TOC, i'm not sure what is used in ReDoc, but i'm sure the dynamic update of TOC isnt an issue for you.

The concept of in-page search implemented by developers of http://docs.fidor.de looks really nice.

**Comment by RomanGotsiy** [comment]
@darklynx, great idea. We liked it.
It's definitely something to consider for after-1.0 releases.

**Comment by erlend-sh** [comment]
+1 to this from us at Discourse as well. We're building a new API docs site with ReDoc. Here's the WIP:

http://blakeerickson.com/discourse_api_docs/

Thanks for a great product!

**Comment by RomanGotsiy** [comment]
@erlend-sh I have great news: this feature is coming soon. I've already started working on it.

**Comment by RomanGotsiy** [comment]
The feature is implemented now 🎉 🚀 
@darklynx thanks for patience 😂
