### ISSUE TITLE
Auto-generate JavaScript request sample?

### ISSUE THREAD

**Issue by brylie** [Rebilly/ReDoc#52]
On the demo page, there seem to be code samples support for C# and PHP. Is there support for, or plans to implement, JavaScript request snippets?

**Comment by RomanGotsiy** [comment]
These examples are not autogenerated. They are included into spec itsself using vendor extensions.
Check out the docs: https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#operation-object-vendor-extensions

**Comment by RomanGotsiy** [comment]
Hey @brylie! May I ask you if we could close this issue? Or maybe you have any other questions or suggestions?

**Comment by brylie** [comment]
Sure, thanks for following up :-)

**Comment by jgabriels** [comment]
I have a fully working code generator:
https://github.com/Direct-Freight/df-api-docs/blob/master/scripts/generate-code-samples.js
It's called during the build:
https://github.com/Direct-Freight/df-api-docs/blob/master/scripts/build.js
You can see what the final results looks like here:
http://apidocs.directfreight.com/#tag/boards
I created a pull request here: #18
but haven't tested it on any third party definitions.

**Comment by rishabh12j** [comment]
> I have a fully working code generator:
> https://github.com/Direct-Freight/df-api-docs/blob/master/scripts/generate-code-samples.js
> It's called during the build:
> https://github.com/Direct-Freight/df-api-docs/blob/master/scripts/build.js
> You can see what the final results looks like here:
> http://apidocs.directfreight.com/#tag/boards
> I created a pull request here: #18
> but haven't tested it on any third party definitions.

it does not work with openapi: 3.0.0 is there a way i can use this to auto generate code samples, thanks in advance
