### ISSUE TITLE
AllOf with multilevel $ref and param override

### ISSUE THREAD

**Issue by am0nshi** [Rebilly/ReDoc#520]
Hi guys, trying to make some inherited response object using reDoc over the swagger.json file.
Currently found that in Response section i see only original "base" file, while i'm referencing on some extended one. In right "Response samples" panel object built seems to be ok.
I'm referencing "#/definitions/EventlistResource" in $ref but in response i have all data from only  "#/definitions/BaseResource".

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/7633061/40721372-fe6afb76-6421-11e8-80ec-d80a88275c7a.png">

Definition example:
```
    "EventlistResource" : {
      "title" : "EventlistResource",
      "allOf" : [ {
        "$ref" : "#/definitions/BaseResource"
      }, {
        "type" : "object",
        "properties" : {
          "data" : {
            "type" : "array",
            "description" : "eventlist request payload",
            "items" : {
              "$ref" : "#/definitions/EventlistResource_data"
            }
          }
        }
      } ]
```
BaseResource:
```
    "BaseResource" : {
      "type" : "object",
      "properties" : {
        "data" : {
          "type" : "array",
          "description" : "Should be filled by inherited collections",
          "items" : {
            "type" : "object",
            "properties" : { }
          }
        },
        "links" : {
          "$ref" : "#/definitions/Links"
        },
        "meta" : {
          "$ref" : "#/definitions/Meta"
        }
      },
      "title" : "BaseResource"
    },
```
Demo:
https://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/am0nshi/311c9c85489002859ae9314462870791/raw/5733da90e5462d8ba313588efea02218d0ae9182/swagger_redoc.json#
Swagger.json:
https://gist.githubusercontent.com/am0nshi/311c9c85489002859ae9314462870791/raw/5733da90e5462d8ba313588efea02218d0ae9182/swagger_redoc.json

**Comment by RomanGotsiy** [comment]
This should be fixed once I merge https://github.com/Rebilly/ReDoc/pull/511

**Comment by RomanGotsiy** [comment]
Fixed by #511

**Comment by am0nshi** [comment]
Thank you for quick reply and fix! One-level inheritance seems to be works fine now, but multi-level is not:
https://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/am0nshi/311c9c85489002859ae9314462870791/raw/5733da90e5462d8ba313588efea02218d0ae9182/swagger_redoc.json#operation/V1EventsByOrganisationGet
![image](https://user-images.githubusercontent.com/7633061/40959499-89edf1a8-68a5-11e8-991a-84bf0a9e60cb.png)

**Comment by am0nshi** [comment]
@RomanGotsiy ^^ :)
