### ISSUE TITLE
Support to show operationId

### ISSUE THREAD

**Issue by exoego** [Rebilly/ReDoc#536]
As an user of Swagger-based API, it is helpful if `operationId` is shown on ReDoc. 

I and my team uses [swagger-codegen](https://github.com/swagger-api/swagger-codegen) or similar a lot. Those code generators uses `operationId` as a method name on the generated API client. If `operationId` is shown on ReDoc, I will be able to find the method name smoothly.

**Comment by RomanGotsiy** [comment]
I understand your use case but adding this in ReDoc may bloat other people docs.

Considered adding `operationId` to the summary or to the `operation` description.
You can automate this with a simple script if you are concerned about duplications.

**Comment by forderation** [comment]
+1, is there any update ?

**Comment by zba** [comment]
> Please, Consider adding operationId to the summary or to the operation description.

people not always use own schemas, mostly they use vendor's schema, why not add the option ? I doing backends based on huge schemas, my client use operationId to point operation, I need to `grep` schemas every time I want to use api endpoint.
