### ISSUE TITLE
Expose callback in ReactStandalone

### ISSUE THREAD

**Issue by vaskevich** [Rebilly/ReDoc#537]
Would it be possible to expose the `callback` that's available in `init` to the `ReactStandalone` component? Would be useful for doing things such as configuring any interactive components in the docs.

**Comment by RomanGotsiy** [comment]
Thanks for suggestion!
Closed in 16313b8

Added `onLoaded` callback. Check [README](https://github.com/Rebilly/ReDoc#usage-as-a-react-component) for details.

Will be released soon.
