### ISSUE TITLE
Array of schema does not appear correctly in UI

### ISSUE THREAD

**Issue by bcharna** [Rebilly/ReDoc#538]
Adding an `array` type property like so:
```
property :items, type: :array, items: { "$ref": "#/definitions/Item" }
```
results in a description in the UI like "Array of object" instead of "Array of Item". Also, the schema description does not appear either.

<img width="776" alt="screen shot 2018-06-15 at 12 09 05 pm" src="https://user-images.githubusercontent.com/1569074/41486333-ef765844-7098-11e8-9963-7f89a68b7c7d.png">

**Comment by RomanGotsiy** [comment]
what do you expect to see? thanks!

**Comment by bcharna** [comment]
In this case, I'd expect to see "Array of Item". Currently it says "Array of Object", so the reader doesn't know that it's actually the `Item` schema in this case.

Additionally, if the property has a `description`, that should appear in the UI as well.

**Comment by RomanGotsiy** [comment]
should be fixed in the latest alpha.25.
Could you please verify?

**Comment by RomanGotsiy** [comment]
I verified it myself. It's fixed already
