### ISSUE TITLE
Callback error / Catch error

### ISSUE THREAD

**Issue by jodacame** [Rebilly/ReDoc#543]
Hi, Exist any way to catch the error when Redoc try load a wrong url? 

Example: 

Redoc.init('WRONG OR NOT VALID URL', {
            hideLoading:true
        }, document.querySelector('#doc'),function(e){
});            

How I can catch the error? 

Thanks.

**Comment by RomanGotsiy** [comment]
Closed in 16313b8. Now callback is called on errors with an error as the first argument.
Will be released in the next alpha

**Comment by hazarathaiahdasari** [comment]
could you please give me how sytnax for that

**Comment by broccolism** [comment]
@RomanHotsiy Could you please give us the syntax to catch the error???
I registered callback function but it still doesn't work.

```
Redoc.init(
          event.data,
          config,
          document.getElementById('container'),
          callbackFunction -----> Not called on error
        )
```
