### ISSUE TITLE
Logo alt text

### ISSUE THREAD

**Issue by viralanomaly** [Rebilly/ReDoc#546]
Is there support for alt-text for the logo image we specify with x-logo?

**Comment by RomanGotsiy** [comment]
Nice suggestion!
PRs are welcome!

**Comment by viralanomaly** [comment]
I have a fix for it, but when I run the tests out of paranoia (yarn test), the license check step is failing on an MIT license, which doesn't really make sense.  Should I just ignore that problem since I certainly didn't introduce it?
