### ISSUE TITLE
Add button to copy request/reply samples

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#55]
Currently, you can't simply select a sample and copy it since you lose all indentation.
Plus you need manually uncollapse all levels.

**Comment by IvanGoncharov** [comment]
Something like this: 
![image](https://cloud.githubusercontent.com/assets/8336157/16337632/a0e0f2ae-3a1f-11e6-81db-75bc4726beb8.png)

**Comment by RomanGotsiy** [comment]
Implemented via 6c2bfd8
