### ISSUE TITLE
Response Schema does list multiple options, but preselects wrong one

### ISSUE THREAD

**Issue by Dalabad** [Rebilly/ReDoc#557]
If I use the attached swagger file, the Response Schema list two response schemas for both the response sample view and the response "tree view":

- `*/*`
- `application/json`

While the middle view must be on `*/*` in order to display the expected information, the code example on the right block needs to be on `application/json` in order to show the example codes.

Is there any way to either remove the "invalid" options from the respective lists or preselect the correct ones?

Currently at least one of the two is always on the invalid option by default.

`{
    "swagger": "2.0",
    "info": {
        "title": "Example API",
        "contact": {
            "email": "foo@bar.com",
            "name": "Foo Ag",
            "url": "https://example.com"
        },
        "license": {
            "name": "unlicensed",
            "url": ""
        },
        "version": "1.0.0"
    },
    "basePath": "/",
    "schemes": [
        "https"
    ],
    "paths": {
        "/job/{scanJobId}/status": {
            "get": {
                "tags": [
                    "service"
                ],
                "summary": "Retrieve the status of a scan job on the current service",
                "description": "Collects all jobs for a scan (queued, running and finished) and returns the combined status.",
                "operationId": "getStatus",
                "parameters": [
                    {
                        "name": "scanJobId",
                        "in": "path",
                        "description": "ID of the scan job",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        },
                        "type": "integer"
                    }
                ],
                "responses": {
                    "500": {
                        "description": "internal server error"
                    },
                    "200": {
                        "description": "status of the scan job and all its sub-jobs on the current service",
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "status_retrieved",
                                    "type": "string"
                                },
                                "data": {
                                    "description": "ScanStatus",
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/ScanStatus"
                                    }
                                }
                            },
                            "type": "object"
                        },
                        "examples": {
                            "application/json": {
                                "message": "status_retrieved",
                                "data": {
                                    "code": 200,
                                    "stats": {
                                        "overall": 1,
                                        "done": 1,
                                        "failed": 0,
                                        "queued": 0,
                                        "computing": 0,
                                        "stopped": 0
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "service"
                ],
                "summary": "Start a new scan job",
                "description": "Takes a request from the core api and starts a new job with the provided information.",
                "operationId": "postStart",
                "parameters": [
                    {
                        "name": "scanJobId",
                        "in": "path",
                        "description": "ID of the scan job",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        },
                        "type": "integer"
                    }
                ],
                "responses": {
                    "500": {
                        "description": "internal server error"
                    },
                    "200": {
                        "description": "a new scan job has been created on the current service",
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "scan_created",
                                    "type": "string"
                                },
                                "data": {
                                    "description": "queue_response",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "examples": {
                            "application/json": {
                                "message": "scan_created",
                                "data": "Queue-Job 123456 created"
                            }
                        }
                    }
                }
            }
        },
        "/job/{scanJobId}": {
            "delete": {
                "tags": [
                    "service"
                ],
                "summary": "Stop a scan job",
                "description": "Takes a request from the core api and stops all not yet processed jobs for a scan.",
                "operationId": "deleteStop",
                "parameters": [
                    {
                        "name": "scanJobId",
                        "in": "path",
                        "description": "ID of the scan job",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        },
                        "type": "integer"
                    }
                ],
                "responses": {
                    "500": {
                        "description": "internal server error"
                    },
                    "200": {
                        "description": "all jobs belonging to the scan have been stopped on the current service",
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "scan_stopped",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "examples": {
                            "application/json": {
                                "message": "scan_stopped"
                            }
                        }
                    }
                }
            }
        },
        "/job/{scanJobId}/findings": {
            "get": {
                "tags": [
                    "service"
                ],
                "summary": "Retrieve all findings of a scan job on the current service",
                "description": "Collects all gathered findings for a scan and returns them.",
                "operationId": "getFindings",
                "parameters": [
                    {
                        "name": "scanJobId",
                        "in": "path",
                        "description": "ID of the scan job",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        },
                        "type": "integer"
                    }
                ],
                "responses": {
                    "500": {
                        "description": "internal server error"
                    },
                    "200": {
                        "description": "findings of the scan job on the current service",
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "findings_retrieved",
                                    "type": "string"
                                },
                                "data": {
                                    "description": "Findings",
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Finding"
                                    }
                                }
                            },
                            "type": "object"
                        },
                        "examples": {
                            "application/json": {
                                "message": "findings_retrieved",
                                "data": [
                                    {
                                        "information": "bar",
                                        "created_at": "2017-08-18 09:02:14",
                                        "modified_at": "2017-08-18 09:02:14"
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CrawlerScanStatus": {
            "properties": {
                "code": {
                    "description": "The return code for the scanner",
                    "type": "integer"
                }
            }
        },
        "Finding": {
            "properties": {
                "information": {
                    "description": "The finding information",
                    "type": "string"
                },
                "created_at": {
                    "description": "The timestamp of the models creation",
                    "type": "integer"
                },
                "modified_at": {
                    "description": "The timestamp of the models last modification",
                    "type": "integer"
                }
            }
        },
        "ScanStatus": {
            "properties": {
                "code": {
                    "description": "The return code for the scanner",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "service",
            "description": "General operations"
        }
    ]
}`

**Comment by RomanGotsiy** [comment]
yes, just add

```json
  "produces": ["application/json"]
```

to your spec.

Full spec:
```json
{
   "swagger":"2.0",
   "info":{
      "title":"Example API",
      "contact":{
         "email":"foo@bar.com",
         "name":"Foo Ag",
         "url":"https://example.com"
      },
      "license":{
         "name":"unlicensed",
         "url":""
      },
      "version":"1.0.0"
   },
   "basePath":"/",
   "schemes":[
      "https"
   ],
   "produces": ["application/json"],
   "paths":{
      "/job/{scanJobId}/status":{
         "get":{
            "tags":[
               "service"
            ],
            "summary":"Retrieve the status of a scan job on the current service",
            "description":"Collects all jobs for a scan (queued, running and finished) and returns the combined status.",
            "operationId":"getStatus",
            "parameters":[
               {
                  "name":"scanJobId",
                  "in":"path",
                  "description":"ID of the scan job",
                  "required":true,
                  "schema":{
                     "type":"integer"
                  },
                  "type":"integer"
               }
            ],
            "responses":{
               "500":{
                  "description":"internal server error"
               },
               "200":{
                  "description":"status of the scan job and all its sub-jobs on the current service",
                  "schema":{
                     "properties":{
                        "message":{
                           "description":"status_retrieved",
                           "type":"string"
                        },
                        "data":{
                           "description":"ScanStatus",
                           "type":"array",
                           "items":{
                              "$ref":"#/definitions/ScanStatus"
                           }
                        }
                     },
                     "type":"object"
                  },
                  "examples":{
                     "application/json": {
                        "message":"status_retrieved",
                        "data":{
                           "code":200,
                           "stats":{
                              "overall":1,
                              "done":1,
                              "failed":0,
                              "queued":0,
                              "computing":0,
                              "stopped":0
                           }
                        }
                     }
                  }
               }
            }
         },
         "post":{
            "tags":[
               "service"
            ],
            "summary":"Start a new scan job",
            "description":"Takes a request from the core api and starts a new job with the provided information.",
            "operationId":"postStart",
            "parameters":[
               {
                  "name":"scanJobId",
                  "in":"path",
                  "description":"ID of the scan job",
                  "required":true,
                  "schema":{
                     "type":"integer"
                  },
                  "type":"integer"
               }
            ],
            "responses":{
               "500":{
                  "description":"internal server error"
               },
               "200":{
                  "description":"a new scan job has been created on the current service",
                  "schema":{
                     "properties":{
                        "message":{
                           "description":"scan_created",
                           "type":"string"
                        },
                        "data":{
                           "description":"queue_response",
                           "type":"string"
                        }
                     },
                     "type":"object"
                  },
                  "examples":{
                     "application/json":{
                        "message":"scan_created",
                        "data":"Queue-Job 123456 created"
                     }
                  }
               }
            }
         }
      },
      "/job/{scanJobId}":{
         "delete":{
            "tags":[
               "service"
            ],
            "summary":"Stop a scan job",
            "description":"Takes a request from the core api and stops all not yet processed jobs for a scan.",
            "operationId":"deleteStop",
            "parameters":[
               {
                  "name":"scanJobId",
                  "in":"path",
                  "description":"ID of the scan job",
                  "required":true,
                  "schema":{
                     "type":"integer"
                  },
                  "type":"integer"
               }
            ],
            "responses":{
               "500":{
                  "description":"internal server error"
               },
               "200":{
                  "description":"all jobs belonging to the scan have been stopped on the current service",
                  "schema":{
                     "properties":{
                        "message":{
                           "description":"scan_stopped",
                           "type":"string"
                        }
                     },
                     "type":"object"
                  },
                  "examples":{
                     "application/json":{
                        "message":"scan_stopped"
                     }
                  }
               }
            }
         }
      },
      "/job/{scanJobId}/findings":{
         "get":{
            "tags":[
               "service"
            ],
            "summary":"Retrieve all findings of a scan job on the current service",
            "description":"Collects all gathered findings for a scan and returns them.",
            "operationId":"getFindings",
            "parameters":[
               {
                  "name":"scanJobId",
                  "in":"path",
                  "description":"ID of the scan job",
                  "required":true,
                  "schema":{
                     "type":"integer"
                  },
                  "type":"integer"
               }
            ],
            "responses":{
               "500":{
                  "description":"internal server error"
               },
               "200":{
                  "description":"findings of the scan job on the current service",
                  "schema":{
                     "properties":{
                        "message":{
                           "description":"findings_retrieved",
                           "type":"string"
                        },
                        "data":{
                           "description":"Findings",
                           "type":"array",
                           "items":{
                              "$ref":"#/definitions/Finding"
                           }
                        }
                     },
                     "type":"object"
                  },
                  "examples":{
                     "application/json":{
                        "message":"findings_retrieved",
                        "data":[
                           {
                              "information":"bar",
                              "created_at":"2017-08-18 09:02:14",
                              "modified_at":"2017-08-18 09:02:14"
                           }
                        ]
                     }
                  }
               }
            }
         }
      }
   },
   "definitions":{
      "CrawlerScanStatus":{
         "properties":{
            "code":{
               "description":"The return code for the scanner",
               "type":"integer"
            }
         }
      },
      "Finding":{
         "properties":{
            "information":{
               "description":"The finding information",
               "type":"string"
            },
            "created_at":{
               "description":"The timestamp of the models creation",
               "type":"integer"
            },
            "modified_at":{
               "description":"The timestamp of the models last modification",
               "type":"integer"
            }
         }
      },
      "ScanStatus":{
         "properties":{
            "code":{
               "description":"The return code for the scanner",
               "type":"integer"
            }
         }
      }
   },
   "securityDefinitions":{
      "Bearer":{
         "type":"apiKey",
         "name":"Authorization",
         "in":"header"
      }
   },
   "tags":[
      {
         "name":"service",
         "description":"General operations"
      }
   ]
}
```

**Comment by Dalabad** [comment]
perfect, thank you!
