### ISSUE TITLE
The docs would be better readable if not expanded by default

### ISSUE THREAD

**Issue by karussell** [Rebilly/ReDoc#56]
As I learned today about your docs, [this](https://rebilly.github.io/ReDoc/?url=https://apis-guru.github.io/api-models/graphhopper.com/1.0/swagger.yaml) is our automatically generated docs and looks useful. But as a developer I'm overloaded with attributes. Instead I would like to see root entries at the start only (for our API and the "vrp" endpoint this would be just `algorithm`, `relations`, `services`, ...) and then expand just one entry like `services` to see `address`, `allowed_vehicles`, etc

**Comment by RomanGotsiy** [comment]
@karussell great idea! Thanks.
I will definitely implement this for the first public release.

**Comment by RomanGotsiy** [comment]
@karussell I've implemented the feature.
You can check [your spec](https://rebilly.github.io/ReDoc/?url=https://apis-guru.github.io/api-models/graphhopper.com/1.0/swagger.yaml) look now!

**Comment by karussell** [comment]
Cool, looks good! 

Will include this then in our docs -> https://github.com/graphhopper/directions-api/issues/32
