### ISSUE TITLE
Cannot minify with create-react-app (reftools again) 2.0.0-alpha.29

### ISSUE THREAD

**Issue by PerfectPixel** [Rebilly/ReDoc#566]
In version 2.0.0-alpha.26 and above creating a minified build is not possible anymore:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/reftools/lib/jptr.js:40

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The same issue as discussed here: https://github.com/Rebilly/ReDoc/issues/384#issuecomment-348103112 is appearing again.

You can recreate this issue by updating the dependency in this [repo](https://github.com/APIs-guru/create-react-app-redoc) and updating the version to `redoc@^2.0.0-alpha.26`.

**Comment by RomanGotsiy** [comment]
Will work again with `alpha.30`

**Comment by Bad-Listener** [comment]
Hello all! 

I am using "redoc": "^2.0.0-alpha.30" and when I try to do npm build, I get the following error as described above. 

Failed to minify the code from this file:

        ./node_modules/reftools/lib/jptr.js:40

Any ideas? Thanks!
