### ISSUE TITLE
how Can I generate new redoc app with redoc-cli

### ISSUE THREAD

**Issue by richard457** [Rebilly/ReDoc#567]
I need to use redoc, how can I generate redoc app(server) with redoc-cli

**Comment by richard457** [comment]
I found solution https://github.com/Rebilly/generator-openapi-repo#generator-openapi-repo--

**Comment by RomanGotsiy** [comment]
Can I close this?

**Comment by RomanGotsiy** [comment]
Closing, feel free to continue discussion here
