### ISSUE TITLE
question: passing options to docker run

### ISSUE THREAD

**Issue by amn41** [Rebilly/ReDoc#570]
trying to pass redoc options when running the docker image. built sucessfully, so far have tried:

` -e REDOC_OPTIONS="nativeScrollbars=true" `

` -e REDOC_OPTIONS="options.nativeScrollbars=true" `

`-e REDOC_OPTIONS="{{nativeScrollbars: true}}"`

`-e REDOC_OPTIONS="{nativeScrollbars: true}"`

**Comment by RomanGotsiy** [comment]
Use [kebab-cased analogs](https://github.com/Rebilly/ReDoc#redoc-options-object) of options:

`-e REDOC_OPTIONS="native-scrollbars=true"`

**Comment by luisfmelo** [comment]
What about nested json? 
Like the main primary color:

It would be:
`-e REDOC_OPTIONS="theme.colors.primary.main=#999999`?

**Comment by kaarelr** [comment]
> What about nested json? Like the main primary color
> 
> It would be:
> `-e REDOC_OPTIONS="theme.colors.primary.main=#999999`?

This does not seem to be working for me. No colours are changed.

**Comment by aminaev-idt** [comment]
> > What about nested json? Like the main primary color
> > It would be:
> > `-e REDOC_OPTIONS="theme.colors.primary.main=#999999`?
> 
> This does not seem to be working for me. No colours are changed.

Did you find any solution with docker env?

**Comment by kaarelr** [comment]
> > > What about nested json? Like the main primary color
> > > It would be:
> > > `-e REDOC_OPTIONS="theme.colors.primary.main=#999999`?
> > 
> > This does not seem to be working for me. No colours are changed.
> 
> @kaarelr
> Did you find any solution with docker env? 

@aminaev-idt I did not. 

Still waiting for someone to explain themeing support for docker set up.
