### ISSUE TITLE
Error - Cannot find module 'mobx'

### ISSUE THREAD

**Issue by jpvalenciag** [Rebilly/ReDoc#576]
I'm getting this strange error whenever I try to run any `redoc-cli` command. It was working fine when I tried it a couple of days ago but now it isn't.

```
$ npx redoc-cli --help
Cannot find module 'mobx'
```
I installed the package globally but it shows the same error.

Thanks!

**Comment by RomanGotsiy** [comment]
Thanks for reporting.

Fixed by 75ced44 and released as `redoc-cli@0.6.1`
