### ISSUE TITLE
Combining multiple authentication types display

### ISSUE THREAD

**Issue by thibaud31** [Rebilly/ReDoc#577]
Hello,

I have noticed that combining multiple authentication types using logical AND is not displayed properly.
In the attached OpenAPI specification file,  it will be displayed : api_key & **OR** client_id
Whereas it should be  someting like : api_key **AND** client_id

[spec.txt](https://github.com/Rebilly/ReDoc/files/2227384/spec.txt)

**Comment by RomanGotsiy** [comment]
fixed, will be released in the next alpha later today or tomorrow
