### ISSUE TITLE
redoc@2.0.0-alpha.30 Cannot find module mobx

### ISSUE THREAD

**Issue by llirikkk** [Rebilly/ReDoc#579]
redoc@2.0.0-alpha.30 doesn't work with redoc-cli, cause mobx was moved to DevDependencies and it results in throwing an error "Cannot find module mobx"

**Comment by RomanGotsiy** [comment]
should have been fixed already: @llirikkk Fixed in https://github.com/Rebilly/ReDoc/issues/576
