### ISSUE TITLE
Discriminator example from OAI spec seems to not work

### ISSUE THREAD

**Issue by Devin-Grant** [Rebilly/ReDoc#581]
I am unable to use the `discriminator` feature described in the [Discriminator Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#discriminator-object).

Example:
```
MyResponseType:
  oneOf:
  - $ref: '#/components/schemas/Cat'
  - $ref: '#/components/schemas/Dog'
  - $ref: '#/components/schemas/Lizard'
  - $ref: 'https://gigantic-server.com/schemas/Monster/schema.json'
  discriminator:
    propertyName: pet_type
    mapping:
      dog: '#/components/schemas/Dog'
      monster: 'https://gigantic-server.com/schemas/Monster/schema.json'
```

the above example doesn't work in ReDoc.

**Comment by RomanGotsiy** [comment]
What are you getting? Any screenshots? Errors?


Are you trying it with `https://gigantic-server.com/schemas/Monster/schema.json`.
If yes, then it won't work as the URL doesn't respond.

**Comment by thelimarenan** [comment]
Follows an example that worked with me:
```
components:
  schemas:
    Pet:
      type: object
      discriminator:
        propertyName: type
        mapping:
          DOG: '#/components/schemas/Dog'
          CAT: '#/components/schemas/Cat'
      properties:
        Name:
          type: string
        age:
          type: integer
        type:
          type: string
          description: Animal type
          enum:
            - DOG
            - CAT
    Dog:
      description: Dog
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            favorite_toy:
              type: string
    Cat:
      description: Cat
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            hunting_mice:
              type: boolean
```

**Comment by RomanGotsiy** [comment]
@Devin-Grant have you resolved the issue?

**Comment by RomanGotsiy** [comment]
Closing as inactive
Feel free to reopen or continue discussion here

**Comment by henhal** [comment]
I find it strange that this was closed without action; the spec says that `discriminator` must be used together with `oneOf` or `anyOf`, and lists a example with a request having a oneOf and a discriminator next to it. This does not work in redoc; the request body becomes empty.

The example listed above shows a completely different approach where there is no `oneOf` and the `discriminator` is instead part of the "base" schema, to which the request has a single reference. This seems to be two slightly different ways of looking at it. Surely ReDoc should support discriminator as a sibling to `oneOf` though?

**Comment by RomanHotsiy** [comment]
@henhal can you post a minimal reproduction example here? I can't reproduce the issue
