### ISSUE TITLE
XHR error

### ISSUE THREAD

**Issue by kiplingw** [Rebilly/ReDoc#583]
My HTML is very simple and is verbatim from the example, with the exception that the spec file URL is different:

````
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='https://heliosmusic.io/OpenAPI.yml'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
````
But for some reason when the page is actually "executed", I see the following:

````
Something went wrong...
Error downloading https://heliosmusic.io/OpenAPI.yml XHR error

Stack trace

s/<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:25518
e/</<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:103:40716
a@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:73:121599
I/<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:73:121744
c@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:73:125148


f.prototype._onFinish/d.onerror@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:103:43820

ReDoc Version: 2.0.0-alpha.32
Commit: dba3995
````

This doesn't appear to be a problem with the actual spec file because it appears to load fine via the [demo site](https://rebilly.github.io/ReDoc/?url=https://heliosmusic.io/OpenAPI.yml).

Any help appreciated.

**Comment by RomanGotsiy** [comment]
Any errors logged to console?

**Comment by kiplingw** [comment]
Good call. Looks like it's possibly something to do with CORS, but not sure how to disable that. Or this could be innocuous:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://heliosmusic.io/OpenAPI.yml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 

But there's also this:

Error: "Error downloading https://heliosmusic.io/OpenAPI.yml 
XHR error"
redocnext/bundles/redoc.standalone.js:55:25518redocnext/bundles/redoc.standalone.js:103:40716redocnext/bundles/redoc.standalone.js:73:121599redocnext/bundles/redoc.standalone.js:73:121744redocnext/bundles/redoc.standalone.js:73:125148redocnext/bundles/redoc.standalone.js:103:43820 react-dom.production.min.js:188:139

**Comment by RomanGotsiy** [comment]
This is not a ReDoc issue. ReDoc just can't load your spec due to same-origin policy.

You should [configure CORS on your server](https://enable-cors.org/server.html) or use CORS proxy (ReDoc demo does this) or host ReDoc on the same origin as the spec.

Feel free to ask here if you have any further questions!

**Comment by kiplingw** [comment]
Thanks Roman. It seems to work fine if I upload it to my production http server.
