### ISSUE TITLE
After upgrade from v1 to v2, "Response Samples" section doesn't show anymore but "Request Samples" still shows, despite no change in how the JSON is generated

### ISSUE THREAD

**Issue by vtruong74** [Rebilly/ReDoc#588]

**Comment by RomanGotsiy** [comment]
Could you please provide any more details? Minimal reproducible sample? Share your spec?

**Comment by vtruong74** [comment]
Sure I can get some details. In the meantime, what prompts the generation of the Sample Response. Without defining specific examples, can you generate the Sample Response through what is defined in the schema?

**Comment by lafrech** [comment]
@vtruong74 Possible cause and fix: https://github.com/Rebilly/ReDoc/issues/535#issuecomment-398000542

**Comment by RomanGotsiy** [comment]
@vtruong74 have you managed to resolve this?

**Comment by vtruong74** [comment]
@lafrech That was the fix, you are a wizard, thank you sir. @RomanGotsiy It is fixed now!

**Comment by lafrech** [comment]
Credits go to @RomanGotsiy  for the fix.

@vtruong74 you may close this issue.
