### ISSUE TITLE
section/Authentication strange behavior redoc@2.0.0-alpha.33

### ISSUE THREAD

**Issue by savage4pro** [Rebilly/ReDoc#590]
1. ### swagger 2.0 + redoc@2.0.0-alpha.32 = things are normal
```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='https://raw.githubusercontent.com/Rebilly/ReDoc/master/demo/swagger.yaml'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.32/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```
![swagger 2.0 + redoc@2.0.0-alpha.32](https://monosnap.com/image/IWDTzlKCaT6rQdtoT3ZYlMrtLAHUuv.png)

---
2. ### openapi 3.0.0 + redoc@2.0.0-alpha.32 = duplicated schemas
```
...
  <body>
    <redoc spec-url='https://raw.githubusercontent.com/Rebilly/ReDoc/master/demo/openapi.yaml'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.32/bundles/redoc.standalone.js"> </script>
  </body>
...
```
![openapi 3.0.0 + redoc@2.0.0-alpha.32](https://monosnap.com/image/HyxOiv0QqBwgs5beGIc36VGcxpyGYw.png)

---
3. ### swagger 2.0 + redoc@2.0.0-alpha.33 = no schemas is visible (but refs are presented as well)
```
...
  <body>
    <redoc spec-url='https://raw.githubusercontent.com/Rebilly/ReDoc/master/demo/swagger.yaml'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.33/bundles/redoc.standalone.js"> </script>
  </body>
...
```
![swagger 2.0 + redoc@2.0.0-alpha.33](https://monosnap.com/image/29RYbwltg2gSthUPxbJEN8q2e6E1fL.png)

---
4. ### openapi 3.0.0 + redoc@2.0.0-alpha.33 = no securitySchemes is visible (but refs are presented as well)
```
...
  <body>
    <redoc spec-url='https://raw.githubusercontent.com/Rebilly/ReDoc/master/demo/openapi.yaml'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.33/bundles/redoc.standalone.js"> </script>
  </body>
...
```
![openapi 3.0.0 + redoc@2.0.0-alpha.33](https://monosnap.com/image/ply75TSaP80xfs8orbZP3CLbDc4JZG.png)

___

Nevertheless, in my current project a bunch of `openapi 3.0.0` with `redoc@2.0.0-alpha.32` works as expected (in this case), because i'm not using `<security-definitions />` injection causes duplication, but `alpha.33` doesn't show securitySchemes too.

![current openapi 3.0.0 + redoc@2.0.0-alpha.32](https://monosnap.com/image/eGqtW5SyIYIuPiqETiUKQDX8W2LUXi.png)

**Comment by RomanGotsiy** [comment]
I must have broken something.
I will check it up asap.
