### ISSUE TITLE
Download button is downloading HTML not JSON

### ISSUE THREAD

**Issue by karlismelderis** [Rebilly/ReDoc#594]
Noticed that "Download" button is just providing same API spec HTML file.
I think it makes more sense to provide API spec in JSON/YAML format.

**Comment by RomanGotsiy** [comment]
Which version of ReDoc do you use?
Could you share a minimal reproducible example?

**Comment by karlismelderis** [comment]
[index.html.zip](https://github.com/Rebilly/ReDoc/files/2261748/index.html.zip)
I used redoc-cli@^0.6.1 and redoc@2.0.0-alpha.30 to get reported behaviour

But if I run redoc@1.22.0 it I got proper download.

Unfortunately I lost record of which tool I used and got JSON in download option.

**Comment by RomanGotsiy** [comment]
Thanks for details.
I can reproduce it now.

Will be fixed in the upcoming release
