### ISSUE TITLE
Add headings from GFM descriptions into menubar

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#60]
This will allow more flexibility with writing docs.
- It will stop developers adding tags just to add menu items.

**Comment by RomanGotsiy** [comment]
Partially implemented: first-level headings are pulled into menu

**Comment by jaingaurav** [comment]
@RomanGotsiy: Are you working on sub-section support? If not maybe I can provide a patch? Not sure if it'll interfere with your section grouping work.

**Comment by RomanGotsiy** [comment]
@jaingaurav I am not working on sub-section support right now but I have significantly refactored menu-generation code. So if you'd to provide a patch do it on top of a branch [`menu-refactor`](https://github.com/Rebilly/ReDoc/tree/menu-refactor).

Unfortunately, source code is almost not documented so let me know if you need any help.

**Comment by jaingaurav** [comment]
@RomanGotsiy: Thanks the new code looks a lot cleaner. I'll give it a shot. Hopefully will have a PR up soon.

**Comment by jaingaurav** [comment]
@RomanGotsiy PR #175 adds support for second level headings. Please note that I know very little about TypeScript, so hopefully some parts of it are somewhat sane.

**Comment by RomanGotsiy** [comment]
@jaingaurav thanks! I've merged your PR and released a new version with subheadings support.

Closing this issue 🎉

**Comment by jaingaurav** [comment]
Thanks @RomanGotsiy
