### ISSUE TITLE
Support IP address as host

### ISSUE THREAD

**Issue by unional** [Rebilly/ReDoc#600]
Hi, when using redoc and accessing it through ip address directly, the host is `undefined`.

It is caused by this:
https://github.com/Rebilly/ReDoc/blob/v1.x/lib/utils/spec-manager.ts#L69-L72
https://github.com/Rebilly/ReDoc/blob/v1.x/lib/utils/spec-manager.ts#L85

I'm using 1.x, don't know if the issue is fixed in 2.x

Thanks. 🌷

**Comment by RomanGotsiy** [comment]
Could you open a PR against 1.x branch to fix this out?

Why are you using `1.x`? Can you switch to `2.x`?

**Comment by unional** [comment]
We are releasing soon and have a long release cycle, so we can't switch to `2.x` (and also since it is still in alpha, management would not approve to make the switch).

Do you have any suggestion on how to fix this?
I would consider using `window.location.host` as the default value. Would that be ok with you?

**Comment by RomanGotsiy** [comment]
Yes, as long as it fixes the issue for you.
Can you confirm it fixes the issue?

**Comment by unional** [comment]
Yes, I confirm this fixes it.

**Comment by RomanGotsiy** [comment]
Should be fixed in `v1.22.2`
