### ISSUE TITLE
Standalone error: "t is undefined" 2.0.0-alpha.34 and 2.0.0-alpha.35

### ISSUE THREAD

**Issue by stevegoossens** [Rebilly/ReDoc#602]
When using `node_modules/redoc/bundles/redoc.standalone.js` with the following releases:
* 2.0.0-alpha.34
* 2.0.0-alpha.35

A stacktrace appears with "t is undefined".

This appears to be a new bug introduced in 2.0.0-alpha.34, as 2.0.0-alpha.33 and previous versions work with the same swagger spec file.

**Comment by RomanGotsiy** [comment]
Could you share your spec? Or link to your docs?

**Comment by gormed** [comment]
I am having the same issue, tested for alpha 28, 33 and 34, none is working. Here is my spec file.
It was converted from swagger 2 to openapi 3, but as far as i can say it is a valid spec (tested with swagger editor).

[invalid.openapi.json.zip](https://github.com/Rebilly/ReDoc/files/2302218/invalid.openapi.json.zip)

**Comment by RomanGotsiy** [comment]
Closing as a dup of #608

Thanks for investigation

> Is this intentional?
no, fixed already. Will be released in the next alpha.
