### ISSUE TITLE
Error I don't understand preventing doc rendering

### ISSUE THREAD

**Issue by rcrooks** [Rebilly/ReDoc#604]
Attaching screenshot. Here's the text:
Something went wrong...

Error downloading https://docs.brightcove.com/live-api/swagger/start_token HTTP ERROR 404
Stack trace
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:16125
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:103:40952
promiseReactionJob@[native code]

https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:16125
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:103:40462
promiseReactionJob@[native code]

ReDoc Version: 2.0.0-alpha.36 
Commit: e0d82f4

![2018-08-12_14-06-18](https://user-images.githubusercontent.com/619617/44004956-50665b18-9e39-11e8-86c6-6389143b0fb5.png)

**Comment by RomanGotsiy** [comment]
You clearly get the reason for this error: "Error downloading ... HTTP ERROR 404"

Your endpoint returns 404 Not Found:

![image](https://user-images.githubusercontent.com/3975738/44020997-561dce66-9eec-11e8-9589-b449877c473a.png)

It is not a ReDoc issue

**Comment by rcrooks** [comment]
Hi @RomanGotsiy - can we reopen this? The 404 isn't on the spec - it's on something called "start_token" - I don't know that that is. The spec definitely validates on editor.swagger.io
![2018-08-13_07-34-38](https://user-images.githubusercontent.com/619617/44029674-21ecfe52-9ecc-11e8-9316-618b2721d4e6.png)

**Comment by RomanGotsiy** [comment]
Could you share the code snipped of you use ReDoc as well as your `openapi-tmp.json`?
This will help to reproduce the issue

**Comment by rcrooks** [comment]
I will, but let me work on it a bit more first. What happened was that I was cleaning up an old spec that was very disorganized. Sadly, I made a **lot** of changes without re-checking the page as I went. I reverted back to the last working version, and am working through the cleanup systematically now. If I run into this again, should be easier to pinpoint what caused it. If I don't, I'll just close this.

**Comment by rcrooks** [comment]
I think it was a spec error after all - surprised the swagger editor didn't catch it....

**Comment by pjena1seic** [comment]
I am facing this issue in 11/11/2025 same 404 Not found for this URL https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

**Comment by pjena1seic** [comment]
Please suggest how we can resolve it

**Comment by leesh1022** [comment]
> Please suggest how we can resolve it

maybe "next" tag removed, 
so use "lastest" instead 
ex) https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js

**Comment by Quintenvw** [comment]
For anyone using FastAPI, a quick workaround is to override the default ReDoc JS URL.
You can do this by explicitly setting `redoc_js_url` in `get_redoc_html`:
```python
return get_redoc_html(
    redoc_js_url="https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js",
)
```
