### ISSUE TITLE
Is there any option to load multiple swaggers in SpecUrl

### ISSUE THREAD

**Issue by binobose** [Rebilly/ReDoc#605]
Hi, I am loading the Swagger in the below format,

```
<RedocStandalone
        specUrl = 'https://....../datafile.json'
        onLoaded = { error => {
          if (error) {
            console.log('Error: ', error);
          }
        }}
        />
```

can anyone please help me, how can I load multiple Swaggers in this context.

**Comment by RomanGotsiy** [comment]
You **can't load multiple swagger files at once**. ReDoc doesn't support this.

Although, you can add some buttons/links/dropdown to change `specUrl`. Changing `specUrl` will update ReDoc with the corresponding spec.

You can also provide different `specUrl` based on the current path and have multiple pages each with the separate ReDoc instance.

Closing this issue.
Feel free to continue discussion here!

**Comment by binobose** [comment]
Thanks @RomanGotsiy for the quick response.

**Comment by J-Gonzalez** [comment]
@binobose - Did you find a clean way to get various swaggers to work? A central source for seeing all documentation for all of our microservices is what we really need. Ability to pass in multiple specUrls would be amazing, but modifying app with dropdown/links also would work fine.

**Comment by marcelstoer** [comment]
This is a feature request that has come up again and again (search the issues for 'multiple') e.g. #442 or #278. Most of them got closed pretty quickly as out-of-scope.

I agree with @J-Gonzalez that specifying a `specUrls` attribute would be the sane thing to expect. That's exactly what Swagger UI does:

```javascript
const ui = SwaggerUIBundle({urls: [{url: "foo.yaml",name: "Foo"},{url: "bar.yaml",name: "Bar"}], etc});
...
window.ui = ui;
```

**Comment by volbrene** [comment]
@binobose I have create a docker image which fix your problem: https://hub.docker.com/r/volbrene/redoc

**Comment by marcelstoer** [comment]
@volbrene Interesting, where's the code to that?

**Comment by volbrene** [comment]
At the moment the code is in my private gitlab.

**Comment by marcelstoer** [comment]
Oh, ok. Then this - from your Docker Hub page - is going to be a bit difficult 😜 
> You are invited to contribute new features, fixes, or updates, large or small; we are always thrilled to receive pull requests, and do our best to process them as fast as we can.

**Comment by volbrene** [comment]
Huch sorry, I have remove this part. Thanks for this info 👌

**Comment by marcelstoer** [comment]
Doing the opposite (making the repo public) would have been more helpful...Your choice of course but I would have liked to contribute new features.

**Comment by volbrene** [comment]
Which feature for example? :)

**Comment by marcelstoer** [comment]
We obviously don't have the same philosophy with regards to _using_ and _creating_ (open-source) software. This isn't the right place to discuss them. So, never mind.

**Comment by davinchia** [comment]
@marcelstoer want to share how you ended up solving this issue? running into the same issue right now. @volbrene's solution is fine but i would like to do this with yamls that are not hosted on the public internet, which might mean not hacking/building on top of his image

**Comment by marcelstoer** [comment]
I didn't solve it yet. Doing this with a Docker image is certainly a good approach but building something closed-source around an open-source project certainly isn't.

**Comment by davinchia** [comment]
@volbrene will be helpful if you can share the code to your image!

**Comment by volbrene** [comment]
Hello guys, I have public my code: https://github.com/volbrene/redoc Hope it would be helpfull.

**Comment by davinchia** [comment]
Thanks @volbrene! Do you know if this works with local yaml files? if I package my yamls with the docker image, would that work out of the box?

**Comment by volbrene** [comment]
@davinchia I will use the offical redoc implementation. It hope this ticket helps: https://github.com/Redocly/redoc/issues/149
