### ISSUE TITLE
Hide description

### ISSUE THREAD

**Issue by chatelao** [Rebilly/ReDoc#609]
Having very detailled descriptions of the parameters (esp. Key/Value lists) makes the documentation very big.

Possible solutions:
- Show the description only on demand
- Show the description only in seperate models

**Comment by RomanGotsiy** [comment]
Unfortunately, the way ReDoc renders descriptions is one of the key design principles of ReDoc.

Most of the users are pretty happy with it so we're not going to change this.

You can either optimize your spec for ReDoc or maybe some other documentation engine may be a better fit for your use case.
