### ISSUE TITLE
Authorization support for loading specs

### ISSUE THREAD

**Issue by momania** [Rebilly/ReDoc#612]
I'm using bearer tokens for both the access to the api, but also to the specs, so that a user only sees the documentation for the part he has access too (reduces noise).

Is it possible for the UI to support this? So that it loads the specs using an authorization header?

**Comment by RomanGotsiy** [comment]
You can manually download a spec using for example `fetch` and then init ReDoc using spec object instead of URL:

```js
Redoc.init(specOrSpecUrl, options, element, callback?)
```

Just do not forget to remove `spec-url` attribute from `<redoc>` tag if you have one as it triggers auto-initialization.

Closing this issue, feel free to continue discussion here!

**Comment by momania** [comment]
Ah great!

For reference, might anybody look for the same, here's a small snippet for doing so:

```javascript
function fetchSpec(url, jwt) {
    fetch(url, {
        headers: new Headers({
            'Accept': 'application/json',
            'Authorization': 'Bearer ' + jwt
        })
    })
    .then((response) => response.json())
    .then((responseJson) => {
        Redoc.init(responseJson);
    })
    .catch((error) => {
        console.error(error);
    });
}
```
