### ISSUE TITLE
The allOff change in 720e282

### ISSUE THREAD

**Issue by fredriklengstrand** [Rebilly/ReDoc#621]
Was the commit https://github.com/Rebilly/ReDoc/commit/720e28284c6ee9878a9f8c36a29af6a3ae7a48ef also meant to remove the name of the schema from the title for anyOf and oneOf?

Before:
![screen shot 2018-08-24 at 09 44 23](https://user-images.githubusercontent.com/10126466/44571852-51841d80-a782-11e8-97a5-18553003543a.png)

After:

![screen shot 2018-08-24 at 09 31 52](https://user-images.githubusercontent.com/10126466/44571853-521cb400-a782-11e8-9b1a-2eb1eb483f44.png)

The relevant yaml:

```
any:
  anyOf:
    - $ref: "#/components/schemas/Foo"
    - $ref: "#/components/schemas/Bar"
one:
  oneOf:
    - $ref: "#/components/schemas/Foo"
    - $ref: "#/components/schemas/Bar"
all:
  allOf:
    - $ref: "#/components/schemas/Foo"
    - $ref: "#/components/schemas/Bar"
```

```
Foo:
  type: object
  properties:
    foo:
      type: string
Bar:
  type: object
  properties:
    bar:
      type: string
```

**Comment by RomanGotsiy** [comment]
@fredriklengstrand no, it didn't mean so.
Thanks for reporting. I will investigate.

**Comment by RomanGotsiy** [comment]
Fixed in https://github.com/Rebilly/ReDoc/commit/39b930d0eeb908317aef178dbf83ce21231cf1a7
