### ISSUE TITLE
How to install and invoke redoc-cli

### ISSUE THREAD

**Issue by marians** [Rebilly/ReDoc#628]
I am trying to make use of the `redoc-cli` for bundling as described here: https://github.com/Rebilly/ReDoc/tree/master/cli

The following Dockerfile illustrates what I'm doing:

```Dockerfile
FROM node:10 as builder

WORKDIR /
RUN git clone --depth 1 https://github.com/Rebilly/ReDoc.git

WORKDIR /ReDoc/cli
RUN npm install
RUN npm run
RUN find / -type f -name "redoc-cli"
RUN which redoc-cli
```

I would expect an executable `redoc-cli` to be created somewhere, but there is none.

`npm run` only lists a `ci-publish` command.

I also tried `npm install -g` instead of `npm install`, which fails. See terminal output below output.

What am I missing?

As you may guess, I am not an avid NodeJS user. If I can help make the README more accessible for people like me, please let me know.

<details>
<summary>Terminal output</summary>

npm WARN rollback Rolling back amdefine@1.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/amdefine is not a child of /usr/local/lib
npm WARN rollback Rolling back ansi-regex@3.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/ansi-regex is not a child of /usr/local/lib
npm WARN rollback Rolling back asap@2.0.6 failed (this is probably harmless): /ReDoc/cli/node_modules/asap is not a child of /usr/local/lib
npm WARN rollback Rolling back async@1.5.2 failed (this is probably harmless): /ReDoc/cli/node_modules/async is not a child of /usr/local/lib
npm WARN rollback Rolling back base64-js@1.3.0 failed (this is probably harmless): /ReDoc/cli/node_modules/base64-js is not a child of /usr/local/lib
npm WARN rollback Rolling back call-me-maybe@1.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/call-me-maybe is not a child of /usr/local/lib
npm WARN rollback Rolling back camelcase@1.2.1 failed (this is probably harmless): /ReDoc/cli/node_modules/camelcase is not a child of /usr/local/lib
npm WARN rollback Rolling back classnames@2.2.6 failed (this is probably harmless): /ReDoc/cli/node_modules/classnames is not a child of /usr/local/lib
npm WARN rollback Rolling back wordwrap@0.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/cliui/node_modules/wordwrap is not a child of /usr/local/lib
npm WARN rollback Rolling back code-point-at@1.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/code-point-at is not a child of /usr/local/lib
npm WARN rollback Rolling back core-js@1.2.7 failed (this is probably harmless): /ReDoc/cli/node_modules/core-js is not a child of /usr/local/lib
npm WARN rollback Rolling back css-color-keywords@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/css-color-keywords is not a child of /usr/local/lib
npm WARN rollback Rolling back decamelize@1.2.0 failed (this is probably harmless): /ReDoc/cli/node_modules/decamelize is not a child of /usr/local/lib
npm WARN rollback Rolling back decko@1.2.0 failed (this is probably harmless): /ReDoc/cli/node_modules/decko is not a child of /usr/local/lib
npm WARN rollback Rolling back delegate@3.2.0 failed (this is probably harmless): /ReDoc/cli/node_modules/delegate is not a child of /usr/local/lib
npm WARN rollback Rolling back dom-walk@0.1.1 failed (this is probably harmless): /ReDoc/cli/node_modules/dom-walk is not a child of /usr/local/lib
npm WARN rollback Rolling back dompurify@1.0.7 failed (this is probably harmless): /ReDoc/cli/node_modules/dompurify is not a child of /usr/local/lib
npm WARN rollback Rolling back esprima@4.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/esprima is not a child of /usr/local/lib
npm WARN rollback Rolling back eventemitter3@3.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/eventemitter3 is not a child of /usr/local/lib
npm WARN rollback Rolling back fast-levenshtein@2.0.6 failed (this is probably harmless): /ReDoc/cli/node_modules/fast-levenshtein is not a child of /usr/local/lib
npm WARN rollback Rolling back foreach@2.0.5 failed (this is probably harmless): /ReDoc/cli/node_modules/foreach is not a child of /usr/local/lib
npm WARN rollback Rolling back format-util@1.0.3 failed (this is probably harmless): /ReDoc/cli/node_modules/format-util is not a child of /usr/local/lib
npm WARN rollback Rolling back get-caller-file@1.0.3 failed (this is probably harmless): /ReDoc/cli/node_modules/get-caller-file is not a child of /usr/local/lib
npm WARN rollback Rolling back get-stream@3.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/get-stream is not a child of /usr/local/lib
npm WARN rollback Rolling back good-listener@1.2.2 failed (this is probably harmless): /ReDoc/cli/node_modules/good-listener is not a child of /usr/local/lib
npm WARN rollback Rolling back has-flag@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/has-flag is not a child of /usr/local/lib
npm WARN rollback Rolling back hoist-non-react-statics@2.5.5 failed (this is probably harmless): /ReDoc/cli/node_modules/hoist-non-react-statics is not a child of /usr/local/lib
npm WARN rollback Rolling back ieee754@1.1.12 failed (this is probably harmless): /ReDoc/cli/node_modules/ieee754 is not a child of /usr/local/lib
npm WARN rollback Rolling back buffer@5.2.1 failed (this is probably harmless): /ReDoc/cli/node_modules/buffer is not a child of /usr/local/lib
npm WARN rollback Rolling back invert-kv@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/invert-kv is not a child of /usr/local/lib
npm WARN rollback Rolling back is-buffer@1.1.6 failed (this is probably harmless): /ReDoc/cli/node_modules/is-buffer is not a child of /usr/local/lib
npm WARN rollback Rolling back is-fullwidth-code-point@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/is-fullwidth-code-point is not a child of /usr/local/lib
npm WARN rollback Rolling back is-stream@1.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/is-stream is not a child of /usr/local/lib
npm WARN rollback Rolling back isexe@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/isexe is not a child of /usr/local/lib
npm WARN rollback Rolling back js-tokens@4.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/js-tokens is not a child of /usr/local/lib
npm WARN rollback Rolling back json-pointer@0.6.0 failed (this is probably harmless): /ReDoc/cli/node_modules/json-pointer is not a child of /usr/local/lib
npm WARN rollback Rolling back kind-of@3.2.2 failed (this is probably harmless): /ReDoc/cli/node_modules/kind-of is not a child of /usr/local/lib
npm WARN rollback Rolling back lazy-cache@1.0.4 failed (this is probably harmless): /ReDoc/cli/node_modules/lazy-cache is not a child of /usr/local/lib
npm WARN rollback Rolling back lcid@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/lcid is not a child of /usr/local/lib
npm WARN rollback Rolling back longest@1.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/longest is not a child of /usr/local/lib
npm WARN rollback Rolling back loose-envify@1.4.0 failed (this is probably harmless): /ReDoc/cli/node_modules/loose-envify is not a child of /usr/local/lib
npm WARN rollback Rolling back lunr@2.3.2 failed (this is probably harmless): /ReDoc/cli/node_modules/lunr is not a child of /usr/local/lib
npm WARN rollback Rolling back mark.js@8.11.1 failed (this is probably harmless): /ReDoc/cli/node_modules/mark.js is not a child of /usr/local/lib
npm WARN rollback Rolling back marked@0.3.18 failed (this is probably harmless): /ReDoc/cli/node_modules/marked is not a child of /usr/local/lib
npm WARN rollback Rolling back memoize-one@4.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/memoize-one is not a child of /usr/local/lib
npm WARN rollback Rolling back mimic-fn@1.2.0 failed (this is probably harmless): /ReDoc/cli/node_modules/mimic-fn is not a child of /usr/local/lib
npm WARN rollback Rolling back mem@1.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/mem is not a child of /usr/local/lib
npm WARN rollback Rolling back min-document@2.19.0 failed (this is probably harmless): /ReDoc/cli/node_modules/min-document is not a child of /usr/local/lib
npm WARN rollback Rolling back minimist@0.0.10 failed (this is probably harmless): /ReDoc/cli/node_modules/minimist is not a child of /usr/local/lib
npm WARN rollback Rolling back minimist@0.0.8 failed (this is probably harmless): /ReDoc/cli/node_modules/mkdirp/node_modules/minimist is not a child of /usr/local/lib
npm WARN rollback Rolling back ms@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/ms is not a child of /usr/local/lib
npm WARN rollback Rolling back debug@3.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/debug is not a child of /usr/local/lib
npm WARN rollback Rolling back number-is-nan@1.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/number-is-nan is not a child of /usr/local/lib
npm WARN rollback Rolling back object-assign@4.1.1 failed (this is probably harmless): /ReDoc/cli/node_modules/object-assign is not a child of /usr/local/lib
npm WARN rollback Rolling back ono@4.0.7 failed (this is probably harmless): /ReDoc/cli/node_modules/ono is not a child of /usr/local/lib
npm WARN rollback Rolling back openapi-sampler@1.0.0-beta.14 failed (this is probably harmless): /ReDoc/cli/node_modules/openapi-sampler is not a child of /usr/local/lib
npm WARN rollback Rolling back p-finally@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/p-finally is not a child of /usr/local/lib
npm WARN rollback Rolling back p-try@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/p-try is not a child of /usr/local/lib
npm WARN rollback Rolling back p-limit@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/p-limit is not a child of /usr/local/lib
npm WARN rollback Rolling back p-locate@3.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/p-locate is not a child of /usr/local/lib
npm WARN rollback Rolling back path-exists@3.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/path-exists is not a child of /usr/local/lib
npm WARN rollback Rolling back locate-path@3.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/locate-path is not a child of /usr/local/lib
npm WARN rollback Rolling back find-up@3.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/find-up is not a child of /usr/local/lib
npm WARN rollback Rolling back path-key@2.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/path-key is not a child of /usr/local/lib
npm WARN rollback Rolling back npm-run-path@2.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/npm-run-path is not a child of /usr/local/lib
npm WARN rollback Rolling back perfect-scrollbar@1.4.0 failed (this is probably harmless): /ReDoc/cli/node_modules/perfect-scrollbar is not a child of /usr/local/lib
npm WARN rollback Rolling back polished@1.9.3 failed (this is probably harmless): /ReDoc/cli/node_modules/polished is not a child of /usr/local/lib
npm WARN rollback Rolling back postcss-value-parser@3.3.0 failed (this is probably harmless): /ReDoc/cli/node_modules/postcss-value-parser is not a child of /usr/local/lib
npm WARN rollback Rolling back process@0.5.2 failed (this is probably harmless): /ReDoc/cli/node_modules/process is not a child of /usr/local/lib
npm WARN rollback Rolling back global@4.3.2 failed (this is probably harmless): /ReDoc/cli/node_modules/global is not a child of /usr/local/lib
npm WARN rollback Rolling back promise@7.3.1 failed (this is probably harmless): /ReDoc/cli/node_modules/promise is not a child of /usr/local/lib
npm WARN rollback Rolling back prop-types@15.6.2 failed (this is probably harmless): /ReDoc/cli/node_modules/prop-types is not a child of /usr/local/lib
npm WARN rollback Rolling back pseudomap@1.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/pseudomap is not a child of /usr/local/lib
npm WARN rollback Rolling back react-dropdown@1.6.2 failed (this is probably harmless): /ReDoc/cli/node_modules/react-dropdown is not a child of /usr/local/lib
npm WARN rollback Rolling back react-is@16.4.2 failed (this is probably harmless): /ReDoc/cli/node_modules/react-is is not a child of /usr/local/lib
npm WARN rollback Rolling back react-lifecycles-compat@3.0.4 failed (this is probably harmless): /ReDoc/cli/node_modules/react-lifecycles-compat is not a child of /usr/local/lib
npm WARN rollback Rolling back mobx-react@5.2.5 failed (this is probably harmless): /ReDoc/cli/node_modules/mobx-react is not a child of /usr/local/lib
npm WARN rollback Rolling back react-tabs@2.3.0 failed (this is probably harmless): /ReDoc/cli/node_modules/react-tabs is not a child of /usr/local/lib
npm WARN rollback Rolling back repeat-string@1.6.1 failed (this is probably harmless): /ReDoc/cli/node_modules/repeat-string is not a child of /usr/local/lib
npm WARN rollback Rolling back align-text@0.1.4 failed (this is probably harmless): /ReDoc/cli/node_modules/align-text is not a child of /usr/local/lib
npm WARN rollback Rolling back center-align@0.1.3 failed (this is probably harmless): /ReDoc/cli/node_modules/center-align is not a child of /usr/local/lib
npm WARN rollback Rolling back require-directory@2.1.1 failed (this is probably harmless): /ReDoc/cli/node_modules/require-directory is not a child of /usr/local/lib
npm WARN rollback Rolling back require-main-filename@1.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/require-main-filename is not a child of /usr/local/lib
npm WARN rollback Rolling back right-align@0.1.3 failed (this is probably harmless): /ReDoc/cli/node_modules/right-align is not a child of /usr/local/lib
npm WARN rollback Rolling back cliui@2.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/cliui is not a child of /usr/local/lib
npm WARN rollback Rolling back safer-buffer@2.1.2 failed (this is probably harmless): /ReDoc/cli/node_modules/safer-buffer is not a child of /usr/local/lib
npm WARN rollback Rolling back iconv-lite@0.4.24 failed (this is probably harmless): /ReDoc/cli/node_modules/iconv-lite is not a child of /usr/local/lib
npm WARN rollback Rolling back encoding@0.1.12 failed (this is probably harmless): /ReDoc/cli/node_modules/encoding is not a child of /usr/local/lib
npm WARN rollback Rolling back node-fetch@1.7.3 failed (this is probably harmless): /ReDoc/cli/node_modules/node-fetch is not a child of /usr/local/lib
npm WARN rollback Rolling back select@1.1.2 failed (this is probably harmless): /ReDoc/cli/node_modules/select is not a child of /usr/local/lib
npm WARN rollback Rolling back set-blocking@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/set-blocking is not a child of /usr/local/lib
npm WARN rollback Rolling back setimmediate@1.0.5 failed (this is probably harmless): /ReDoc/cli/node_modules/setimmediate is not a child of /usr/local/lib
npm WARN rollback Rolling back shallowequal@1.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/shallowequal is not a child of /usr/local/lib
npm WARN rollback Rolling back react-hot-loader@4.3.5 failed (this is probably harmless): /ReDoc/cli/node_modules/react-hot-loader is not a child of /usr/local/lib
npm WARN rollback Rolling back shebang-regex@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/shebang-regex is not a child of /usr/local/lib
npm WARN rollback Rolling back shebang-command@1.2.0 failed (this is probably harmless): /ReDoc/cli/node_modules/shebang-command is not a child of /usr/local/lib
npm WARN rollback Rolling back signal-exit@3.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/signal-exit is not a child of /usr/local/lib
npm WARN rollback Rolling back slugify@1.3.1 failed (this is probably harmless): /ReDoc/cli/node_modules/slugify is not a child of /usr/local/lib
npm WARN rollback Rolling back source-map@0.4.4 failed (this is probably harmless): /ReDoc/cli/node_modules/source-map is not a child of /usr/local/lib
npm WARN rollback Rolling back sprintf-js@1.0.3 failed (this is probably harmless): /ReDoc/cli/node_modules/sprintf-js is not a child of /usr/local/lib
npm WARN rollback Rolling back argparse@1.0.10 failed (this is probably harmless): /ReDoc/cli/node_modules/argparse is not a child of /usr/local/lib
npm WARN rollback Rolling back js-yaml@3.12.0 failed (this is probably harmless): /ReDoc/cli/node_modules/js-yaml is not a child of /usr/local/lib
npm WARN rollback Rolling back json-schema-ref-parser@5.1.3 failed (this is probably harmless): /ReDoc/cli/node_modules/json-schema-ref-parser is not a child of /usr/local/lib
npm WARN rollback Rolling back stickyfill@1.1.1 failed (this is probably harmless): /ReDoc/cli/node_modules/stickyfill is not a child of /usr/local/lib
npm WARN rollback Rolling back strip-ansi@4.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/strip-ansi is not a child of /usr/local/lib
npm WARN rollback Rolling back string-width@2.1.1 failed (this is probably harmless): /ReDoc/cli/node_modules/string-width is not a child of /usr/local/lib
npm WARN rollback Rolling back strip-eof@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/strip-eof is not a child of /usr/local/lib
npm WARN rollback Rolling back stylis@3.5.3 failed (this is probably harmless): /ReDoc/cli/node_modules/stylis is not a child of /usr/local/lib
npm WARN rollback Rolling back stylis-rule-sheet@0.0.10 failed (this is probably harmless): /ReDoc/cli/node_modules/stylis-rule-sheet is not a child of /usr/local/lib
npm WARN rollback Rolling back supports-color@3.2.3 failed (this is probably harmless): /ReDoc/cli/node_modules/supports-color is not a child of /usr/local/lib
npm WARN rollback Rolling back tiny-emitter@2.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/tiny-emitter is not a child of /usr/local/lib
npm WARN rollback Rolling back clipboard@2.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/clipboard is not a child of /usr/local/lib
npm WARN rollback Rolling back prismjs@1.15.0 failed (this is probably harmless): /ReDoc/cli/node_modules/prismjs is not a child of /usr/local/lib
npm WARN rollback Rolling back tslib@1.9.3 failed (this is probably harmless): /ReDoc/cli/node_modules/tslib is not a child of /usr/local/lib
npm WARN rollback Rolling back ua-parser-js@0.7.18 failed (this is probably harmless): /ReDoc/cli/node_modules/ua-parser-js is not a child of /usr/local/lib
npm WARN rollback Rolling back source-map@0.5.7 failed (this is probably harmless): /ReDoc/cli/node_modules/uglify-js/node_modules/source-map is not a child of /usr/local/lib
npm WARN rollback Rolling back uglify-to-browserify@1.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/uglify-to-browserify is not a child of /usr/local/lib
npm WARN rollback Rolling back whatwg-fetch@2.0.4 failed (this is probably harmless): /ReDoc/cli/node_modules/whatwg-fetch is not a child of /usr/local/lib
npm WARN rollback Rolling back isomorphic-fetch@2.2.1 failed (this is probably harmless): /ReDoc/cli/node_modules/isomorphic-fetch is not a child of /usr/local/lib
npm WARN rollback Rolling back fbjs@0.8.17 failed (this is probably harmless): /ReDoc/cli/node_modules/fbjs is not a child of /usr/local/lib
npm WARN rollback Rolling back css-to-react-native@2.2.1 failed (this is probably harmless): /ReDoc/cli/node_modules/css-to-react-native is not a child of /usr/local/lib
npm WARN rollback Rolling back styled-components@3.4.5 failed (this is probably harmless): /ReDoc/cli/node_modules/styled-components is not a child of /usr/local/lib
npm WARN rollback Rolling back which@1.3.1 failed (this is probably harmless): /ReDoc/cli/node_modules/which is not a child of /usr/local/lib
npm WARN rollback Rolling back which-module@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/which-module is not a child of /usr/local/lib
npm WARN rollback Rolling back window-size@0.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/window-size is not a child of /usr/local/lib
npm WARN rollback Rolling back yargs@3.10.0 failed (this is probably harmless): /ReDoc/cli/node_modules/uglify-js/node_modules/yargs is not a child of /usr/local/lib
npm WARN rollback Rolling back uglify-js@2.8.29 failed (this is probably harmless): /ReDoc/cli/node_modules/uglify-js is not a child of /usr/local/lib
npm WARN rollback Rolling back wordwrap@0.0.3 failed (this is probably harmless): /ReDoc/cli/node_modules/wordwrap is not a child of /usr/local/lib
npm WARN rollback Rolling back optimist@0.6.1 failed (this is probably harmless): /ReDoc/cli/node_modules/optimist is not a child of /usr/local/lib
npm WARN rollback Rolling back ansi-regex@2.1.1 failed (this is probably harmless): /ReDoc/cli/node_modules/wrap-ansi/node_modules/ansi-regex is not a child of /usr/local/lib
npm WARN rollback Rolling back is-fullwidth-code-point@1.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/wrap-ansi/node_modules/is-fullwidth-code-point is not a child of /usr/local/lib
npm WARN rollback Rolling back strip-ansi@3.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/wrap-ansi/node_modules/strip-ansi is not a child of /usr/local/lib
npm WARN rollback Rolling back string-width@1.0.2 failed (this is probably harmless): /ReDoc/cli/node_modules/wrap-ansi/node_modules/string-width is not a child of /usr/local/lib
npm WARN rollback Rolling back wrap-ansi@2.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/wrap-ansi is not a child of /usr/local/lib
npm WARN rollback Rolling back xregexp@4.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/xregexp is not a child of /usr/local/lib
npm WARN rollback Rolling back y18n@4.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/y18n is not a child of /usr/local/lib
npm WARN rollback Rolling back yallist@2.1.2 failed (this is probably harmless): /ReDoc/cli/node_modules/yallist is not a child of /usr/local/lib
npm WARN rollback Rolling back lru-cache@4.1.3 failed (this is probably harmless): /ReDoc/cli/node_modules/lru-cache is not a child of /usr/local/lib
npm WARN rollback Rolling back cross-spawn@5.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/cross-spawn is not a child of /usr/local/lib
npm WARN rollback Rolling back execa@0.7.0 failed (this is probably harmless): /ReDoc/cli/node_modules/execa is not a child of /usr/local/lib
npm WARN rollback Rolling back os-locale@2.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/os-locale is not a child of /usr/local/lib
npm WARN rollback Rolling back camelcase@4.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/yargs-parser/node_modules/camelcase is not a child of /usr/local/lib
npm WARN rollback Rolling back yargs-parser@10.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/yargs-parser is not a child of /usr/local/lib
npm WARN rollback Rolling back cliui@4.1.0 failed (this is probably harmless): /ReDoc/cli/node_modules/yargs/node_modules/cliui is not a child of /usr/local/lib
npm WARN rollback Rolling back decamelize@2.0.0 failed (this is probably harmless): /ReDoc/cli/node_modules/yargs/node_modules/decamelize is not a child of /usr/local/lib
npm WARN rollback Rolling back handlebars@4.0.11 failed (this is probably harmless): /ReDoc/cli/node_modules/handlebars is not a child of /usr/local/lib
npm WARN rollback Rolling back isarray@2.0.4 failed (this is probably harmless): /ReDoc/cli/node_modules/isarray is not a child of /usr/local/lib
npm WARN rollback Rolling back mkdirp@0.5.1 failed (this is probably harmless): /ReDoc/cli/node_modules/mkdirp is not a child of /usr/local/lib
npm WARN rollback Rolling back mobx@4.4.0 failed (this is probably harmless): /ReDoc/cli/node_modules/mobx is not a child of /usr/local/lib
npm WARN rollback Rolling back react@16.4.2 failed (this is probably harmless): /ReDoc/cli/node_modules/react is not a child of /usr/local/lib
npm WARN rollback Rolling back react-dom@16.4.2 failed (this is probably harmless): /ReDoc/cli/node_modules/react-dom is not a child of /usr/local/lib
npm WARN rollback Rolling back redoc@2.0.0-alpha.37 failed (this is probably harmless): /ReDoc/cli/node_modules/redoc is not a child of /usr/local/lib
npm WARN rollback Rolling back yargs@12.0.1 failed (this is probably harmless): /ReDoc/cli/node_modules/yargs is not a child of /usr/local/lib
npm ERR! path /usr/local/lib/node_modules/redoc-cli/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/redoc-cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-31T10_31_32_716Z-debug.log

</details>

**Comment by monolithed** [comment]
```
➜ npm -v
5.6.0

➜ npm install redoc

➜ npx redoc-cli serve swagger.yaml
Server started: http://127.0.0.1:8080
GET /: 42.262ms
```

**Comment by marians** [comment]
Thanks, that helped!

**Comment by roculo** [comment]
➜ npx redoc-cli serve swagger.yaml
Server started: http://127.0.0.1:8080
Can you show me how to change port  server started guys?

**Comment by monolithed** [comment]
> ➜ npx redoc-cli serve swagger.yaml
> Server started: http://127.0.0.1:8080
> Can you show me how to change port server started guys?

There's the [`--port`](https://github.com/Redocly/redoc/blob/master/cli/index.ts#L64) argument:
