### ISSUE TITLE
How to see the third column?

### ISSUE THREAD

**Issue by monolithed** [Rebilly/ReDoc#629]
<img width="1280" alt="screen shot 2018-08-31 at 14 26 20" src="https://user-images.githubusercontent.com/803674/44909948-f75afd80-ad29-11e8-95e0-e44dd45d6f11.png">

```
npx redoc-cli serve swagger.yaml
```

How to see the third column?

**Comment by monolithed** [comment]
https://github.com/Rebilly/ReDoc/issues/450

**Comment by arjunsk** [comment]
If you are looking for `redoc-cli` command

`redoc-cli serve --options.theme.breakpoints.medium=70rem swagger.yaml`
