### ISSUE TITLE
Ugly anchor links

### ISSUE THREAD

**Issue by dzienisz** [Rebilly/ReDoc#634]
Hi, is it possible to fix anchor links?

They looks a little bit ugly and unreadable.

![zrzut ekranu 2018-09-07 o 13 51 40](https://user-images.githubusercontent.com/3521624/45219019-d22a3a00-b2a9-11e8-9f50-04a1b8b4369a.png)

**Comment by RomanGotsiy** [comment]
Yes, specify `operationId` on your operations
