### ISSUE TITLE
Deploy 2.0.0-alpha.XX webjars to maven central

### ISSUE THREAD

**Issue by kosprov** [Rebilly/ReDoc#640]
We are using ReDoc as a webjar dependency. 

At some point we switched to `2.0.0-alpha.22` and found it beign a great improvement, regardless being an alpha release.

For some reason, no other `2.0.0-alpha.XX` release has been deployed as a webjar.

It would be nice to have Git releases and webjars releases in sync.

**Comment by kosprov** [comment]
For the record, the maven dependency we are using is:

    <dependency>
        <groupId>org.webjars.npm</groupId>
        <artifactId>redoc</artifactId>
        <version>2.0.0-alpha.22</version>
    </dependency>

**Comment by RomanGotsiy** [comment]
@kosprov I was not aware of webjars releases.

I just checked and it looks like anyone can deploy new webjars release. I just searched for `redoc`, clicked blue `+` button, chose the version and clicked `Deploy`.

![image](https://user-images.githubusercontent.com/3975738/45413804-b3012300-b682-11e8-82ed-debe374855a7.png)

So if at any time you need new version as a webjars dependency you can deploy it yourself.

Although, I still can't see version `v2.0.0-alpha.38` on the site. But when I try to deploy it again it tells me it is already deployed. Probably caching.

**Comment by kosprov** [comment]
Oh, I didn't know that.

It's on maven central now! Thanks for your time.
