### ISSUE TITLE
Rendered page shows warning for parameters resulting in no models being displayed in the page

### ISSUE THREAD

**Issue by harshalna1du** [Rebilly/ReDoc#643]
Hi team,

Issue:

Upon rendering of the YAML [Petstore 3.0](
https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml#),  the page displays warnings with text such as - No "type" specified at "/paths/~1pets~1{id}/get/parameters/0". Automatically detected: "object". 

This results in page not showing definition of request or response models.

This issue was first observer 4-5 days back.

Thank you

**Comment by RomanGotsiy** [comment]
OMG, I accidentally deployed 1.x version demo instead of the latest one as a result of a recent CI build of 1.x.
Deployed a new alpha.39 and new demo will be deployed once CI finishes (in 5-10 mins from now)
Thanks for reporting!

**Comment by harshalna1du** [comment]
Thanks! 

Appreciate the great work with redoc.
