### ISSUE TITLE
ReDoc IE compatibility?

### ISSUE THREAD

**Issue by auahmed** [Rebilly/ReDoc#647]
Is it IE compatible? 
I was on my work laptop and when i open the following link (http://rebilly.github.io/ReDoc/) in chrome i get no issues but when i go onto the link IE the page stays white and does not load.

When inspecting the element i see that under console i get an error:
````
SCRIPT1004: Expected ';'
redoc-demo.bundle.js (47,20652)
````

Was just wondering is it just because of the configurations that my work env has set on IE or its compatibility issue?

**Comment by RomanGotsiy** [comment]
Yes, it is IE compatible.

The demo was not working due to a bug. I've already fixed it and redeployed demo.
