### ISSUE TITLE
When using scroll the last item is not selected in the menu

### ISSUE THREAD

**Issue by Margera** [Rebilly/ReDoc#648]
When using Scroll on the page, if the last item does not reach the top of the screen, it is never automatically selected in the left menu.

**Comment by RomanGotsiy** [comment]
This is how it works. Unfortunately, there is no good way to fix this behavior.
Lots of other sites with similar navigation work in the same way: 

I will close this issue.
In case you have any ideas of how to fix this consistently feel free to continue discussion here!
