### ISSUE TITLE
Problem installing redoc-cli@0.6.1 - styled-components is missing

### ISSUE THREAD

**Issue by gkalogiros-nutmeg** [Rebilly/ReDoc#659]
We're using redoc-cli@0.6.1 in our pipeline for generating our documentation automatically. 

Today we're facing a major problem when trying to install it. What's strange is that we're using version 0.6.1 for two months now without any problems. Today we started receiving the following problem without changing anything.

```
/usr/local/bin/redoc-cli -> /usr/local/lib/node_modules/redoc-cli/index.js
- nice-try@1.0.5 node_modules/redoc-cli/node_modules/nice-try
- p-defer@1.0.0 node_modules/redoc-cli/node_modules/p-defer
- map-age-cleaner@0.1.2 node_modules/redoc-cli/node_modules/map-age-cleaner
- p-is-promise@1.1.0 node_modules/redoc-cli/node_modules/p-is-promise
- semver@5.5.1 node_modules/redoc-cli/node_modules/semver
- xregexp@4.0.0 node_modules/redoc-cli/node_modules/xregexp
/usr/local/lib
└─┬ redoc-cli@0.6.1 
  ├── UNMET PEER DEPENDENCY styled-components@^3.4.0
  └─┬ yargs@11.1.0 
    ├── decamelize@1.2.0 
    ├─┬ find-up@2.1.0 
    │ └─┬ locate-path@2.0.0 
    │   └─┬ p-locate@2.0.0 
    │     └─┬ p-limit@1.3.0 
    │       └── p-try@1.0.0 
    ├─┬ os-locale@2.1.0 
    │ ├─┬ execa@0.7.0 
    │ │ └─┬ cross-spawn@5.1.0 
    │ │   └─┬ lru-cache@4.1.3 
    │ │     ├── pseudomap@1.0.2 
    │ │     └── yallist@2.1.2 
    │ ├─┬ lcid@1.0.0 
    │ │ └── invert-kv@1.0.0 
    │ └── mem@1.1.0 
    ├── y18n@3.2.1 
    └── yargs-parser@9.0.2 

npm WARN redoc@2.0.0-alpha.39 requires a peer of styled-components@^3.4.0 but none was installed.
```

Our script for installing the redoc-cli is the following:
```
#!/usr/bin/env bash

version=$(node -p "require('redoc-cli/package.json').version" 2>/dev/null)
[ "$version" == "0.6.1" ] || npm install -g redoc-cli@0.6.1

redoc-cli bundle docs/api/specification.yml -o docs/index.html
```

We're helpless Java developers not knowing how we can fix that. Any help will be much appreciated 

Thanks in advance

**Comment by BPMathews** [comment]
I am having the exact same problem. I dug a little deeper and tried to use npx to just print the version number to see if there was any kind of breaking change. I went through version 0.6.2, 0.6.1, 0.5.0, and 0.4.0 and all of them had the same issue. 

`docker run --rm node:8-alpine npx redoc-cli --version`

```
npx: installed 120 in 5.969s
Cannot find module 'styled-components'
```

**Comment by RomanGotsiy** [comment]
Ahh. Yes. IN the latest ReDoc alpha I moved `styled-components` to peerDependencies and forgot to update `redoc-cli`.

And `redoc-cli` installs each time the newest ReDoc version (`"^2.0.0-alpha.37"`).

This issue should have been fixed in `redoc-cli@0.6.3`. Could you verify?

To avoid similar issues in the future, use `package-lock.json` or `yarn.lock`. This way each `redoc-cli` install will install with the exact same version of dependencies.

**Comment by nicwaters96** [comment]
I had the same error with 0.6.1.

With 0.6.3, a different error occurs:

#!/usr/bin/env bash

version=$(node -p "require('redoc-cli/package.json').version" 2>/dev/null)
[ "$version" == "0.6.3" ] || npm install -g redoc-cli@0.6.3

redoc-cli bundle docs/api/specification.yml -o docs/index.html

npm ERR! path /usr/local/lib/node_modules/redoc-cli/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/redoc-cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by RomanGotsiy** [comment]
My fault 🙈. Should be fixed in `0.6.4`

**Comment by gkalogiros-nutmeg** [comment]
@RomanGotsiy no worries! Thank you for responding that quickly 👍

**Comment by nicwaters96** [comment]
works! thanks so much for responding so quick @RomanGotsiy 

(we'd got as far as figuring out it was pulling the latest 'redoc' alpha, but we were a bit stuck)

**Comment by RomanGotsiy** [comment]
🎉
