### ISSUE TITLE
rendered docs are not intelligble on printed media in Firefox

### ISSUE THREAD

**Issue by deutrino** [Rebilly/ReDoc#661]
Rendered OpenAPI docs are currently near useless when printed from Firefox 62. Please fix the printer stylesheet.

**Comment by RomanGotsiy** [comment]
It looks like a Firefox issue related to `display: flex` and printing. I don't know how to fix it and don't want to introduce any browser-specific hacks considering ReDoc is not meant to be printed as it has interactive features.

I added a few media-print improvements to make it better on Chrome and Safari in fbcec82

**Comment by svrnwnsch** [comment]
I have the same problem now also on chrome.
