### ISSUE TITLE
Query parameter type appears as string

### ISSUE THREAD

**Issue by marcospgp** [Rebilly/ReDoc#667]
I'm not sure why the parentCategory parameter is showing up as having type string:

```yaml
/api/categories:
  get:
    summary: List categories.
    description: >
      Retrieve the list of top level categories.
      If you specify a parent category, this endpoint will
      instead return the list of its children.
    parameters:
      - in: query
        name: parentCategory
        description: The ID of the parent category whose children should be retrieved (optional).
        required: false
        schema:
          type: integer
          example: 568
    responses:
      '200':
       description: A list of categories.
       content:
         text/plain:
           schema:
             type: string
             example: OK
       '500':
         description: Something went wrong.
```

And here is the resulting HTML:

![image](https://user-images.githubusercontent.com/3464445/46625086-8974d380-cb2a-11e8-92f3-7b09a19993c1.png)

Thank you so much!

**Comment by RomanGotsiy** [comment]
I'm not sure but looks like you have OpenAPI 2.0 spec.

In OpenAPI 2.0 type of non-body parameter should be defined at the parameter level, not in the `schema` (`schema` should be defined only for `body` parameters):

```yaml
/api/categories:
  get:
    summary: List categories.
    description: >
      Retrieve the list of top level categories.
      If you specify a parent category, this endpoint will
      instead return the list of its children.
    parameters:
      - in: query
        name: parentCategory
        description: The ID of the parent category whose children should be retrieved (optional).
        required: false
        type: integer # <-- directly here
        example: 568
    responses:
      '200':
       description: A list of categories.
       content:
         text/plain:
           schema:
             type: string
             example: OK
       '500':
         description: Something went wrong.

**Comment by marcospgp** [comment]
That is correct, great catch! I added an issue to the swagger-jsdoc repo. Thanks!

https://github.com/Surnet/swagger-jsdoc/issues/138

**Comment by RomanGotsiy** [comment]
> swagger-jsdoc by default adds "swagger": "2.0" instead of "openapi": "3.0.0". Maybe redoc could interpret the two in the same way?

Those are two completely different versions of spec (with really different structure). So ReDoc can't interpret them in the same way. ReDoc actually converts 2.0 to 3.0 internally.

Closing the issue.

**Comment by marcospgp** [comment]
I actually realized that after writing the comment. Sorry for the silly question!
