### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #

### ISSUE THREAD

**Issue by courtneyaschwartz** [Rebilly/ReDoc#671]
After upgrading to redoc.min.js 1.22.2 w/ jQuery 3.3.1 (to resolve a jQuery vulnerability found during a security scan), and either searching or scrolling to an anchor, we get this error in the browser's JavaScript console:

```
Uncaught Error: Syntax error, unrecognized expression: #operation/createPolicy
    at Function.Sizzle.error (jquery-3.3.1.js?ver=3.3.1:1541)
```

This error may have been triggered by a bug fix in jQuery that has been breaking things elsewhere:
https://github.com/jquery/jquery/issues/3779

Apparently selectors must now be surrounded in double quotes (").

**Comment by RomanGotsiy** [comment]
ReDoc is not using and even has no jquery in the dependencies.
Why do you think it is ReDoc related?

**Comment by RomanGotsiy** [comment]
Closing as inactive

Feel free to continue discussion here though
