### ISSUE TITLE
Support for vue.js

### ISSUE THREAD

**Issue by bmhm** [Rebilly/ReDoc#673]
Hi,

quick question. If I try to use redoc with vue.js, webpack will complain that react is missing. But I don't want to install the react components. Is there any other way of using redoc in vue.js?

**Comment by RomanGotsiy** [comment]
No, ReDoc requires to React to work as it is React-based (ReDoc is a React component).

You don't need to install any react components, just react and react-dom itself.

I can just recommend you to leverage code-splitting and split ReDoc and all the deps (including React) into a separate bundle which is loaded by route.

**Comment by ChrisDillinger** [comment]
Would be very interested in a tutorial that digs into code-splitting considerations here and how it impacts page loading / bundles / etc.

Looking around for OpenAPI UI theme libs for my Vue project, and not that many decent options to choose from :/
