### ISSUE TITLE
hideHostname also hides basePath

### ISSUE THREAD

**Issue by harold-padilla** [Rebilly/ReDoc#677]
As per the description `hideHostname`: if set, the protocol and hostname is not shown in the operation definition. It seems like `hideHostname` should only hide the schemes and the host as the description says. The Swagger spec. defines the `basePath` as a different element detached from the host (source: https://swagger.io/docs/specification/2-0/api-host-and-base-path/).

The `basePath` is an integral element of an endpoint and I believe it should be included even if hideHostname is enabled.

I reproduced this using the redoc in React and also the standalone version. See: [redoc.html.txt](https://github.com/Rebilly/ReDoc/files/2494666/redoc.html.txt).

**Comment by courtneyaschwartz** [comment]
@RomanHotsiy Sorry, do you remember why this was closed?

Facing the same problem. We're trying out the Pro version, but it has this issue, too.

**Comment by courtneyaschwartz** [comment]
Seems this might be triggered by something in a Swagger/OpenAPI file. Older files we generated do not trigger this.

**Comment by RomanHotsiy** [comment]
I will investigate the issue with `hide-hostname`.

> Maybe worth adding to ReDoc readme.md that if the OpenAPI file is missing the host and basePath properties, ReDoc doesn't leave it blank

It's in the OpenAPI Spec: 

![image](https://user-images.githubusercontent.com/3975738/61115302-d6f7e580-a49a-11e9-8c57-6bce3ae940ac.png)

**Comment by courtneyaschwartz** [comment]
Missed that... Thanks.
Not an intuitive thing on the spec's part. (Most companies _don't_ host docs on the same site as their API gateway. Organizational + UX + architecture + other reasons. They'd be better served by simply omitting, not guessing.) So might be worth 1 line in ReDoc readme's options list.
