### ISSUE TITLE
Using Redoc.init with scrollYOffset does not offset middle panel

### ISSUE THREAD

**Issue by vfalco02** [Rebilly/ReDoc#680]
I have the following setup: 
```
<div id="redoc" style="min-height:calc(100vh - 64px)"></div>
<script src="/static/redoc.standalone.js"></script>
<script>
Redoc.init('/swagger.yaml', {
      scrollYOffset: 'div.navbar',
      disableSearch: true,
      pathInMiddlePanel: true,
      suppressWarnings: true,
      activeScrollbars: true,
      theme: myTheme,
    }, document.getElementById('redoc'));
</script>
```

When the page loads, only the left menu is offset. The middle panel is still starting at top: 0

Am I missing something, or is this a potential issue?

**Comment by RomanGotsiy** [comment]
This is an expected behavior.
You can offest middle panel by using e.g. `padding-top` on `body` or on a wrapping container.

This option controls the offset of fixed or absolute positioned elements.

**Comment by paololazzari** [comment]
@RomanHotsiy can you please provide an example? I can't seem to get this to work properly
