### ISSUE TITLE
Create Docker Hub automated build

### ISSUE THREAD

**Issue by neluzhin** [Rebilly/ReDoc#682]
This issue relates to issue #657 and PR #676. @RomanGotsiy, when you created [redocly/redoc](https://hub.docker.com/r/redocly/redoc/) Docker Hub repository, you choosed type "Repository", not "Automated build". That's the reason why badge isn't working. Also pushes to GitHub repository will not trigger automated builds in Docker Hub, that's because you should remove current repository and create automated build with the same name.

If you just recreate repository, everything should work (I believe).

You may configure your builds like this:

![image](https://user-images.githubusercontent.com/12474739/47233461-7e982980-d3db-11e8-9615-9027ad996754.png)

* Every push to master will build new image with `latest` tag.
* Every tag push will build image with the same tag.

**Comment by RomanGotsiy** [comment]
Ahh, got it.

I'll try to fix it.

> Every push to master will build a new image with the latest tag.
Can I build a new image with the `latest` tag not with every push to master but just with each version tag (so the latest release of ReDoc is `latest` on Docker).

`master` is not meant to be stable here (it can be even broken completely sometimes).
Only tagged releases should be built and deployed.

**Comment by RomanGotsiy** [comment]
OK, looks like I've figured it out!
Removed and created it again.

Also I recreated `redocly/redoc` and rebuild `latest` and `v2.0.0-alpha.41` tags.

Thanks, @neluzhin for helping out!
