### ISSUE TITLE
Theme overrides

### ISSUE THREAD

**Issue by mfauveau** [Rebilly/ReDoc#683]
Looking at the Zuora API reference I see that they were able to change the display of buttons using an "overrides" parameter. However, this doesn't seem to work on the latest ReDoc. Is this a feature only available to ReDoc Pro?

**Comment by adamaltman** [comment]
Yes, it is only available to ReDoc Pro, which is also only available in private beta at this time.  We're expecting to get things buttoned up in the next month and have a release candidate.

**Comment by mfauveau** [comment]
Thanks for the answer @adamaltman
