### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by rqdzs** [Rebilly/ReDoc#688]
I'm having trouble on example..... I have this propertie and i need to set as an object this entity that i created but when i set the example shows this like this....

I'm using open api 3.0 and i'm usgin the following script

  <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.32/bundles/redoc.standalone.js"> </script>
![q](https://user-images.githubusercontent.com/19806884/47459194-e2db3480-d7b1-11e8-8e19-77d08a1f1ae6.jpg)

![q2](https://user-images.githubusercontent.com/19806884/47459138-bde6c180-d7b1-11e8-9354-03b90692401c.PNG)

**Comment by RomanGotsiy** [comment]
Could you share the whole schema? I can't reproduce it with data you provided

**Comment by rqdzs** [comment]
Sure...i
![e1](https://user-images.githubusercontent.com/19806884/47517822-bed62c80-d85f-11e8-81b0-6f46f7416fab.PNG)
![e2](https://user-images.githubusercontent.com/19806884/47517832-c4337700-d85f-11e8-83b8-f292bbe987e0.PNG)

**Comment by rqdzs** [comment]
![e3](https://user-images.githubusercontent.com/19806884/47519350-cbf51a80-d863-11e8-928a-2f78d65bce2a.PNG)
