### ISSUE TITLE
Suggestion: lazyRendering on demand

### ISSUE THREAD

**Issue by evgeniush** [Rebilly/ReDoc#693]
Future implementation of lazyLoading option assumes that "... ReDoc shows initial screen ASAP and then renders the rest operations asynchronously ...".

It would be great if ReDoc could support being able to render api sections on demand, rather than just render the rest asynchronously. Sometimes you do not need to render everything, even asynchronously the rest.

For example, Pet Store demo (https://rebilly.github.io/ReDoc/) could fetch initial screen only by default. And when a user clicks pet, store or user on the left side menu it will fetch appropriate section asynchronously.

This could be useful in cases when your documentation is not only huge but also available in different versions and a user would like to be able easily to switch between versions. Doing full rendering every time on each switch could cause performance issues.  

Of course, Search will not be accurate, but it could be simply disabled.

**Comment by wiseman13** [comment]
Any new updates on your experiment that we can play with?

**Comment by RomanGotsiy** [comment]
See https://github.com/Rebilly/ReDoc/issues/327#issuecomment-491442174
