### ISSUE TITLE
TypeError: createGlobalStyle is not a function when using redoc-cli

### ISSUE THREAD

**Issue by idelsink** [Rebilly/ReDoc#698]
When using the latest redoc-cli (`0.6.4`), which uses `redoc@v2.0.0-alpha.41`, I get the following error:

```
TypeError: createGlobalStyle is not a function
```
## Steps to reproduce

1. Get the perstore OpenAPI 3 spec: [examples/v3.0/petstore.yaml](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml)
2. Run `redoc-cli` on the petstore: 
   ```shell
   redoc-cli bundle petstore.yaml -o petstore/
   ```

## Stack trace

```text
/usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:7303
var PSStyling = createGlobalStyle(perfect_scrollbar_templateObject_1 || (perfect_scrollbar_templateObject_1 = external_tslib_["__makeTemplateObject"](["", ""], ["", ""])), perfect_scrollbar_default.a && perfect_scrollbar_default.a.toString());
                ^

TypeError: createGlobalStyle is not a function
    at Module.<anonymous> (/usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:7303:17)
    at __webpack_require__ (/usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:36:30)
    at /usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:100:18
    at /usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:103:10
    at webpackUniversalModuleDefinition (/usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by topazas** [comment]
Does not help.

redoc@2.0.0-alpha.41
``
yarn add styled-components@4.0.3
npx redoc-cli --version
``

createGlobalStyle is not a function

**Comment by idelsink** [comment]
I'm not sure that simply adding the peer dependency `styled-components` is a viable solution. As indicated by other people, this does not seem to solve the issue.

**Comment by topazas** [comment]
It works

**Comment by idelsink** [comment]
It's seems that the release of `redoc-cli@0.7.0` fixes the problem.

**Comment by RomanGotsiy** [comment]
@idelsink it is.
`redoc` is using styled components as a `peerDependency` and recently the code base was updated to use `styled-components@4` which doesn't have `injectGlobalStyle` anymore.
`redoc-cli` included `redoc` as a dependency so has to install valid version of its peer dependencies itself. Before `redoc-cli` used `styled-components@3.x` which is incompatible with `4.x`

**Comment by takuyaokamoto11** [comment]
this is happening again, using latest master branch 15/01/2019
```
