### ISSUE TITLE
Display securityDefinitions/security 

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#7]
- [x] securityDefinitions
- [x] add security definitions to the side menu
- [ ] security

**Comment by adamaltman** [comment]
:+1:

**Comment by cayter** [comment]
+1

**Comment by rbaumi** [comment]
+1

**Comment by RomanGotsiy** [comment]
securityDefinitions are now rendered in the docs
+ placement of security definitions can be configured. Check out details [in the docs](https://github.com/Rebilly/ReDoc/blob/master/docs/security-definitions-injection.md#injection-security-definitions) or check example in the [demo spec](https://github.com/Rebilly/ReDoc/blob/master/demo/swagger.yaml#L36)

**Comment by SebastianStehle** [comment]
There are also security information per operation, e.g. you can specify the roles or claims. Would be awesome to support this:

     "security": [
          {
            "roles": []
          }
        ]

**Comment by mooop12** [comment]
Any news on this? This is kind of a big deal, most APIs use some kind of authorization. I know this will be important during API console implementation, but maybe until then we could get a placeholder link pointing to the appropriate `securityDefinition` section?

**Comment by robdefeo** [comment]
Missing this feature is significant because it does not allow the user to understand what security scopes are required for each operation. With complex API's this is a significant ask. What is the status with this feature?

**Comment by RomanGotsiy** [comment]
It is being worked on in version 2 (track here: https://github.com/Rebilly/ReDoc/pull/357)
![image](https://user-images.githubusercontent.com/3975738/35197587-19881ddc-feea-11e7-9cfb-b5a28d82a640.png)

Here is the screenshot of the current implementation. If anyone has a better idea of how to visualize this, please share!

**Comment by RomanGotsiy** [comment]
Implemented in 2.0-alpha.x

**Comment by tPl0ch** [comment]
@RomanGotsiy is there an npm package for the `2.0-rc*` version? We'd like to use this feature but would need to completely change our redoc deployment (which is based on `npm install` currently).

Regards and many thanks for your work on `redoc`,
Thomas
