### ISSUE TITLE
Bundle broke links in sidebar

### ISSUE THREAD

**Issue by cbautista1002** [Rebilly/ReDoc#702]
Hi! I just installed redoc-cli, version 0.7.0, and I ran `redoc-cli bundle myfile.json` but the endpoint links in the side bar of the resulting HTML file do not work - clicking on them doesn't do anything. This is not an issue when I have a simple HTML file that pulls in redoc through the CDN.

I see these errors in the JS console:
```
Uncaught SyntaxError: Unexpected string in index.html:98
Uncaught ReferenceError: Redoc is not defined in index.html:478
```

Line 98 is referring to some JS code that starts with `*/Object.defineProperty(t,"__esModule",{value:!0});var r="function"==typeof Symbol&&Symbol.for,o=r?Symbol.for("react.el`.

Line 478 is referring to `Redoc.hydrate(__redoc_state, container);;`.

I tried this with my own json swagger file and then confirmed the issue exists with https://github.com/Rebilly/ReDoc/blob/master/demo/swagger.yaml. The above errors and lines are from when I bundled this `swagger.yaml` file.

Any ideas?
Thanks!

**Comment by RomanGotsiy** [comment]
I can't reproduce the issue with the demo file.
Just run

```bash
redoc-cli bundle "https://raw.githubusercontent.com/Rebilly/ReDoc/master/demo/swagger.yaml"
```

and the resulting output works just fine.

```bash
~ → redoc-cli --version
0.7.0
```

**Comment by cbautista1002** [comment]
Hm, you're right. The reason I was having this problem is because I was copying and pasting the HTML content from the terminal to an HTML file. I was running this command on a VM and didn't have access to the file itself so I has to copy and paste out the content. But now I did it right and it works.

Thanks and sorry for the distraction! Closing.
