### ISSUE TITLE
What's the point of x-extendedDiscriminator?

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#714]
I don't understand the point of `x-extendedDiscriminator`. From the documentation it seems to exist in order to allow discriminator values that are different from the schema name. But isn't this already supported using `mapping`? For example:

```yaml
animal:
  type: object
  oneOf:
    - $ref: '#/components/schemas/Equine'
    - $ref: '#/components/schemas/Feline'
  discriminator:
    propertyName: type
    mapping:
      horse: '#/components/schemas/Equine'
      cat: '#/components/schemas/Feline'
```

This enables `horse` and `cat` to be selected in the discriminator drop-down, and the names `Equine` and `Feline` are never surfaced.

**Comment by RomanGotsiy** [comment]
`mapping` was introduced in OpenAPI 3.
`x-extendedDiscriminator` was introduced to support this with OpenAPI 2.
Now it exists for backward compatibility.

**Comment by cmeeren** [comment]
I see, thanks. I suggest updating the vendor extensions with a note to that effect. :)
