### ISSUE TITLE
Rendering of nested oneOf selectors

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#719]
It's great that ReDoc supports nested `oneOf`, but the rendering can be improved.

Example definition:

```yaml
ErrorA:
  properties:
    ...

ErrorB:
  properties:
    ...

ErrorC:
  properties:
    ...

ErrorAB:
  oneOf:
    - $ref: '#/components/schemas/ErrorA'
    - $ref: '#/components/schemas/ErrorB'

ErrorABC:
  oneOf:
    - $ref: '#/components/schemas/ErrorAB'
    - $ref: '#/components/schemas/ErrorC'
```

Currently it renders like this:

![image](https://user-images.githubusercontent.com/7766733/48832800-4ee19600-ed7a-11e8-9e7d-3f7be96dca52.png)

I suggest at least spacing them out a bit vertically (simple fix - only CSS?).

You could also consider connecting them with lines (probably a bit more work?), like below, but that requires some design of what happens when the list of selectors becomes long enough to break onto a second line.

![image](https://user-images.githubusercontent.com/7766733/48832999-c1eb0c80-ed7a-11e8-99aa-ff9db2d3543f.png)

Lines like these will of course only make sense for directly nested `oneOf`.

**Comment by RomanGotsiy** [comment]
Nice suggestion!

PRs are welcome!

**Comment by cmeeren** [comment]
Unfortunately I'm no front-end/JS dev, so I can't assist.

**Comment by cmeeren** [comment]
In any case: If you could just increase the margin a bit, that would go a long way to making this look good. :)
