### ISSUE TITLE
Object names not rendered if placed in a reference object

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#721]
Consider the following definition:

```yaml
components:
  schemas:

    Errors:

      Error1:
        properties:
          foo:
            type: string
    
    Error2:
      properties:
        bar:
            type: string
    
    AllErrors:
      oneOf:
        - $ref: '#/components/schemas/Errors/Error1'
        - $ref: '#/components/schemas/Error2'

```

As you can see, `Error1` is placed inside a reference object `Errors`. This is AFAIK [valid per the OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#components-object). However, the `oneOf` selector only renders the name for `Error2` and shows `object` instead of `Error1`:

![image](https://user-images.githubusercontent.com/7766733/48835909-ac2d1580-ed81-11e8-8194-1f2bbf37a92a.png)

**Comment by cmeeren** [comment]
Workaround: Define `title` for the schema objects (see #722).

**Comment by RomanGotsiy** [comment]
This is technically valid per the OpenAPI specification but ReDoc works correctly here.

![image](https://user-images.githubusercontent.com/3975738/48845047-2c647280-eda4-11e8-9fd0-3806276981a0.png)

It says that `schemas` hold reusable Schema Objects and states that value of is a map from string **directly** to `Schema Object`.

So the ref `'#/components/schemas/Errors'` is a ref to reusable Schema Object which ReDoc also shows by name while `'#/components/schemas/Errors/Error1` is ref to some specific property of Schema Object.

Here is a counter-example:

```yaml
components:
  schemas:
    Error1:
      properties:
        foo:
          type: string
    
    Error2:
      properties:
        bar:
            type: string
    
    AllErrors:
      oneOf:
        - $ref: '#/components/schemas/Errors1/properties'
        - $ref: '#/components/schemas/Error2'
```

is also perfectly valid per OpenAPI spec but you don't expect to see `properties` as a title

**Comment by cmeeren** [comment]
Sorry, my mistake. If you look at the second column called `Type`, you can see that it's a map from a string to a Schema object **or a Reference object**, but I had misunderstood what a reference object is. My mistake for not RTFM. 🙃
