### ISSUE TITLE
Use schema title also when using allOf

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#722]
Consider the following yaml:

```yaml
MyBase:
  properties:
    foo:
      type: string

MyType1:
  allOf:
    - $ref: '#/components/schemas/MyBase'
    - title: SomeTitle1
      properties:
        bar:
          type: string


MyType2:
  allOf:
    - $ref: '#/components/schemas/MyBase'
    - title: SomeTitle2
      properties:
        baz:
          type: string

MyType:
  oneOf:
    - $ref: '#/components/schemas/MyType1'
    - $ref: '#/components/schemas/MyType2'
```

When MyType is rendered (e.g. in a response), the `oneOf` selector buttons display `MyType1` and `MyType2`, not `SomeTitle1` and `SomeTitle2` as expected:

![image](https://user-images.githubusercontent.com/7766733/48841191-fe296780-ed90-11e8-9547-e0ff84808e4b.png)

However, when removing the `allOf` in `MyType1` and `MyType2`, i.e. when doing

```yaml
MyType1:
  title: SomeTitle1
    properties:
      bar:
        type: string
```

and similar for `MyType2`, then it renders correctly:

![image](https://user-images.githubusercontent.com/7766733/48841283-4b0d3e00-ed91-11e8-9d11-70fa6aaae391.png)

I would expect `title` to be used for the `oneOf` selector also when the different types are defined using `allOf`.

**Comment by cmeeren** [comment]
Interestingly, they will render correctly (use the `title`) if the schema objects are placed in a reference object (see also #721).

**Comment by cmeeren** [comment]
Another workaround (or perhaps the intended use?): Define `title` at the top level:

```yaml
MyType1:
  title: SomeTitle1
  allOf:
    - $ref: '#/components/schemas/MyBase'
    - properties:
        bar:
          type: string
```

If I have misunderstood the OpenAPI specification and this is the only correct usage, feel free to close this issue.

**Comment by RomanGotsiy** [comment]
Just define the title at the top level. It is the intended use.

```yaml
MyType2:
  allOf:
    - $ref: '#/components/schemas/MyBase'
    - title: SomeTitle2
      properties:
        baz:
          type: string
```

Resulting type is, in fact, a combination of two types so semantically it shouldn't inherit the title of any of types.

E.g.:

```yaml
Type:
  allOf:
    - title: Type with foo property ONLY
      properties:
        foo:
          type: string
    - title: Type with baz property ONLY
      properties:
        baz:
          type: string
```

If the `Type` inherits any of titles it would be semantically incorrect.
