### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by gavinkalika** [Rebilly/ReDoc#726]
Have a button to export to PDF

**Comment by pawamoy** [comment]
Who were you @gavinkalika, what did you see?!

**Comment by pawamoy** [comment]
Not PDF but HTML, and for a FastAPI application, from a Python script:

```python
"""Script to export the ReDoc documentation page into a standalone HTML file."""

import json

from my_app.app import app

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>My Project - ReDoc</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="https://fastapi.tiangolo.com/img/favicon.png">
    <style>
        body {
            margin: 0;
            padding: 0;
        }
    </style>
    <style data-styled="" data-styled-version="4.4.1"></style>
</head>
<body>
    <div id="redoc-container"></div>
    <script src="https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js"> </script>
    <script>
        var spec = %s;
        Redoc.init(spec, {}, document.getElementById("redoc-container"));
    </script>
</body>
</html>
"""

if __name__ == "__main__":
    with open(f"api-docs-my-project.html", "w") as fd:
        print(HTML_TEMPLATE % json.dumps(app.openapi()), file=fd)
```

**Comment by PhilippeGalvan** [comment]
@pawamoy That should be somewhere in the documentation or in the library but as a standalone it's really nice!

**Comment by mfcosta** [comment]
Hi @pawamoy . I tried to run you script, but it's showing the following error:

Traceback (most recent call last):
  File "script.py", line 5, in <module>
    from my_app.app import app
ModuleNotFoundError: No module named 'my_app'

It's obvious that I do not have any module called my_app, but I'm not sure where I can find it, or if I should replace that name by something else.

**Comment by ivanlen** [comment]
Hey @mfcosta , the easiest way is to put the script in the same folder where you app is defined.
By your app I mean `app = FastAPI()`.
You should have some file (`file.py `) where you have the app definition `app = FastAPI()`

Then you should replace 
`from my_app.app import app` with 
`from file import app`

After this it should run smoothly.

**Comment by pawamoy** [comment]
Yep, `my_app.app` is supposed to be the Python dotted path to your module defining your FastAPI "app".

**Comment by taneshin** [comment]
Is there alternative code to download the swagger docs?

**Comment by ricekab** [comment]
> Is there alternative code to download the swagger docs?

You mean other than the script mentioned above? The above script still works for me (fastapi version 0.71.0)

**Comment by pawamoy** [comment]
Well, the Swagger interface cannot be used as a standalone (since it queries your app being served), but a simple `curl http://localhost:8000/docs` gave me the following:

```html
<!DOCTYPE html>
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui.css">
        <link rel="shortcut icon" href="https://fastapi.tiangolo.com/img/favicon.png">
        <title>FastAPI - Swagger UI</title>
    </head>
    <body>
    <div id="swagger-ui"></div>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
        <!-- `SwaggerUIBundle` is now available on the page -->
    <script>
        const ui = SwaggerUIBundle({
            url: '/openapi.json',
            "dom_id": "#swagger-ui",
            "layout": "BaseLayout",
            "deepLinking": true,
            "showExtensions": true,
            "showCommonExtensions": true,
            oauth2RedirectUrl: window.location.origin + '/docs/oauth2-redirect',
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIBundle.SwaggerUIStandalonePreset
            ],
        })
    </script>
    </body>
</html>
```

**Comment by RomanHotsiy** [comment]
@pawamoy you can use redoc-cli to bundle a standalone html file.

**Comment by fxmarty** [comment]
@pawamoy This is fire, thank you! 🔥
