### ISSUE TITLE
Support partial responses

### ISSUE THREAD

**Issue by raderio** [Rebilly/ReDoc#738]
Will be very useful to document that API support partial responses.
This will give a strong point when comparing with GraphQL.

Like `GET /api/blogposts?fields=author{name,avatar},title,detail`

https://www.leliam.com/make-rest-api-to-partial-response-just-like-graphql-@bRyL6nWufIxFXIdNWRdAwN
https://apigee.com/about/blog/technology/restful-api-design-can-your-api-give-developers-just-information-they-need

Can you please integrate partial response?

**Comment by nanov** [comment]
Frankly, i do not see what should be implemented.

You could define a schema for fields, document it respectively and return the desired result, the return schema will stay the same ( hence, not all fields are "required" ). 

In other words, this sounds as something that is out of scope of openapi/redoc.

**Comment by raderio** [comment]
I mean the part `?fields=author{name,avatar},title,detail`
This should be part of documentation.

**Comment by nanov** [comment]
This is a simple query parameter.

**Comment by RomanGotsiy** [comment]
@raderio I don't understand.

Can you explain your point in more details.

**Comment by RomanGotsiy** [comment]
Closing as out of scope.
Feel free to continue discussion here though.

**Comment by raderio** [comment]
I mean can you please add something like _fields editor` from https://developers.google.com/apis-explorer/#p/blogger/v3/blogger.blogs.listByUser

![partial](https://user-images.githubusercontent.com/4563564/51388826-38b24500-1b33-11e9-9510-64a044cd2faa.png)

**Comment by raderio** [comment]
Or something like https://api.spacex.land/graphql/ left side.
Something like explorer in graphql https://www.onegraph.com/blog/2019/01/24/How_OneGraph_onboards_users_new_to_GraphQL.html#introducing-the-onegraph-graphiql-explorer
