### ISSUE TITLE
Question: nullable & optional/required marks

### ISSUE THREAD

**Issue by raderio** [Rebilly/ReDoc#739]
Can we represent that a field is non-nullable & optional?
this mean, or we send a data for the field, or just do not send the field in request, null is not allowed.
`{"foo": "bar", "baz": true}` is allowed
`{"baz": true}` is allowed, because is optional
`{"foo": null, "baz": true}` is NOT allowed, because is non-nullable

Basically `null` has the meaning of "this property existed before, and I want to nullify its value". If there's no value, or the value needs not change (for requests, for example), it just shouldn't be sent.

**Comment by nanov** [comment]
String types are non-nullabale by default, you could [define them as nullable](https://swagger.io/docs/specification/data-models/data-types/) by adding ```nullable: true```.

I would suggest that you dive a little deeper into OpenAPI specifications and JSON Schema definitions, as ReDoc is no more than a documentation generator / renderer out of Swagger / OpenAPI specification.

**Comment by raderio** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/1775

**Comment by nanov** [comment]
Have you opened [the page i was linking to](https://swagger.io/docs/specification/data-models/data-types/)?

**Comment by raderio** [comment]
Yes, thanks.
At the moment is
```
type: integer
nullable: true
```
what I am searching/needed
```
type: integer
nullable: true
required: false
```

**Comment by nanov** [comment]
Properties aren't required unless explicitly specified as required, although you might want to take a look at how required properties are defined.

Nullable and ***not-required*** could look like this:
```json
{
  "type": "object",
  "properties": {
    "counter": {
      "type": "integer",
      "nullable": true,
    } 
}
```

The same but **required** will look like this:
```json
{
  "type": "object",
  "properties": {
    "counter": {
      "type": "integer",
      "nullable": true,
    },
   "required": [
      "counter"
   ]
}
```

**Comment by raderio** [comment]
Good, so Open-API support this.
But how this will look in ReDoc?

**Comment by nanov** [comment]
I have no idea, just draft a quick schema and see how it looks.

**Comment by RomanGotsiy** [comment]
@nanov thanks for explanations!

> But how this will look in ReDoc?

If you mark a property as required it will show small red `required` label. If you mark it as nullable it will show `nullable` badge.
