### ISSUE TITLE
Question: mobx peer dependency version

### ISSUE THREAD

**Issue by viralanomaly** [Rebilly/ReDoc#741]
Is there any reason that you know of why we can't use the latest mobx (5.7.0)? The version specified in the Redoc package.json is ^4.3.1, which wouldn't include 5.7.0 as satisfying it.

**Comment by viralanomaly** [comment]
@RomanGotsiy - we're trying to put redoc into our documentation that is public-facing, and I'd love to be able to give our dev ops a firm answer on this. :)

**Comment by RomanGotsiy** [comment]
`5.x` uses ES6 proxies which are not supported by IE11.
Otherwise, it should be compatible with `4.x` so you can use `5.7.0`.

I updated the peer-dependency. It will be ready once I publish a new version.
