### ISSUE TITLE
Redoc sidemenu overlaps page footer

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#75]
![image](https://cloud.githubusercontent.com/assets/8336157/17329390/2293b240-58cb-11e6-906d-e937affdd148.png)

**Comment by krsyoung** [comment]
Hey @RomanGotsiy, looks like it has the same issue with overlapping a navbar as well (when using Zurb foundation).  

If I can figure out how to work around it with Zurb I'll post back -- otherwise I'm guessing it will benefit from the same fix as the footer.

**Comment by RomanGotsiy** [comment]
@krsyoung does ReDoc overlaps navbar of footer? If it overlaps navbar: have you tried using [`scroll-y-offset`](https://github.com/Rebilly/ReDoc#redoc-tag-attributes) option of ReDoc?
Check out [example]( https://github.com/Rebilly/ReDoc/blob/master/demo/index.html#L25)

**Comment by krsyoung** [comment]
Hey @RomanGotsiy, thanks for the pointer!  This helps but (in my case) I don't have a sticky navbar so I end up with a gap the size of the navbar as soon as I scroll down the page.   It does look perfect when the page initially loads using the `scroll-y-offset` option and `body > header` in my case.

I'll keep messing with it, you've got me going in the right direction.

**Comment by RomanGotsiy** [comment]
@krsyoung it would be helpful if you can share link to your site so I can check it and fix this issue

**Comment by RomanGotsiy** [comment]
I mean nothing is wrong with your setup. It is ReDoc issue and I'm interested to fix it to cover as many as possible common use cases

**Comment by krsyoung** [comment]
Hey no worries @RomanGotsiy, I've got lots of issues!  Will have a link for you later today.  Appreciate the help.  -- BTW I can open another issue if you want to track separately.

**Comment by krsyoung** [comment]
Hey @RomanGotsiy, here is a link to the site with the issue:  http://169.44.121.154/docs/api

It is based on Zurb Foundation.  I didn't have a chance to look at it today but hopefully will tomorrow.

**Comment by RomanGotsiy** [comment]
@krsyoung I have checked your link.
It's ReDoc issue, nothing wrong with your setup. I will try to fix this for the next release (most likely at the beginning of the next week)

**Comment by RomanGotsiy** [comment]
@krsyoung I have fixed navbar overlaps. Remove `scroll-y-offset` from `<redoc>` element on your site to get it working.

Regarding footer overflow - will fix this for the next release.

**Comment by RomanGotsiy** [comment]
@IvanGoncharov @krsyoung this issue is fixed in the latest release: v1.3.0
I have checked both sites and side menu no more overflows page footer

@krsyoung for you site you need to remove `scroll-y-offset` option from `<redoc>`

**Comment by krsyoung** [comment]
Beautiful, for the record thanks @RomanGotsiy!  Things are looking great at https://apiharmony-open.mybluemix.net/docs/api.
