### ISSUE TITLE
use hostname without relative path in urls

### ISSUE THREAD

**Issue by iamkarlson** [Rebilly/ReDoc#758]
Hi, I'm stuck a little bit with trying to get swashbuckle (swagger geneator for aspnet core) and redoc working.  After swashbuckle I have 
redoc html page located at 
[localhost:5000/swagger/index.html](http://localhost:5000/swagger/index.html). 
My json file is located at:
[localhost:5000/swagger/v1/swagger.json](http://localhost:5000/swagger/v1/swagger.json)

So I'm getting urls such as one below for my endpoints:
[localhost:5000/swagger/v1/api/v1/Values](http://localhost:5000/swagger/v1/api/v1/Values)

However, these urls are wrong because they are relative to the host and not to the redoc location. I would like to have url in my redoc page shown as 
[localhost:5000/api/v1/Values](http://localhost:5000/api/v1/Values)

**Comment by iamkarlson** [comment]
Immediately after discovered how to set up the host and everything started working as expected.

**Comment by WalterEA** [comment]
Hi @iamkarlson, I'm facing exactly the same issue. how did you "set up the host"? Thanks
