### ISSUE TITLE
TypeError: Cannot set property '_pointer' of null

### ISSUE THREAD

**Issue by DavidBiesack** [Rebilly/ReDoc#76]
I tried to load an OpenAPI spec as per the TL;DR HTML in the README and got a **TypeError: Cannot set property '_pointer' of null"" error in the browser. In the inspector I found:
```

Local Exception : TypeError: Cannot set property '_pointer' of null at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:8141) at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5106 at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5988) at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:6146) at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5532) at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5061) at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:8448) at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5106 at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5988) at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5720)
a : TypeError: Cannot set property '_pointer' of null at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:8141) at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5106 at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5988) at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:6146) at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5532) at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5061) at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:8448) at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5106 at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5988) at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5720)
b : "TypeError: Cannot set property '_pointer' of null↵    at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:8141)↵    at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5106↵    at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5988)↵    at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:6146)↵    at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5532)↵    at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5061)↵    at a.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:8448)↵    at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5106↵    at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5988)↵    at Function.c.value (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:2525:5720)"
c : null
d : null
e : null
g : null
this : a
redoc.min.js:2524 TypeError: Cannot set property '_pointer' of null
    at a.c.value (redoc.min.js:2525)
    at redoc.min.js:2525
    at Function.c.value (redoc.min.js:2525)
    at Function.c.value (redoc.min.js:2525)
    at Function.c.value (redoc.min.js:2525)
    at a.c.value (redoc.min.js:2525)
    at a.c.value (redoc.min.js:2525)
    at redoc.min.js:2525
    at Function.c.value (redoc.min.js:2525)
    at Function.c.value (redoc.min.js:2525)
```
The OAS spec passes schema validation against http://swagger.io/v2/schema.json
However, I cannot share it here due to the IP.  I also get this with other OAS documents when using

http://myhost.com/ReDoc.html?spec_url=http://myhost.com/api-name/swagger.json

and even with http://swagger.na.sas.com/ReDoc.html?spec_url=http://swagger.na.sas.com/apis/petstore.swagger.io/v2/swagger.json

where http://swagger.na.sas.com/apis/petstore.swagger.io/v2/swagger.json contains a local copy of http://petstore.swagger.io/v2/swagger.json

http://myhost.com/ReDoc.html?spec_url=http://petstore.swagger.io/v2/swagger.json

does work, so the problem seems to stem from running against OAS documents on an intranet. Everything is on the same host/port so I don't think CORS is an issue.

**Comment by RomanGotsiy** [comment]
Hi @DavidBiesack. Let's try to do remote debugging 😉 

First: ReDoc doesn't support `?spec_url` URL parameter (you probably confusing it with SwaggerUI). We support `?url` but only on demo page, not as a part of ReDoc.

Could you replace `redoc.min.js` reference to `http://rebilly.github.io/ReDoc/dist/redoc.js` and copy-paste error here?

**Comment by DavidBiesack** [comment]
thanks, @RomanGotsiy -- from reading https://github.com/Rebilly/ReDoc/blob/master/README.md I thought it allowed query parameters (in Options section -- perhaps clarify that to say where those options are specified). 
Will try non-minified and report back

**Comment by DavidBiesack** [comment]
I tried the non-minified and it never completed loading my local OAS document.
It may indeed be a CORS issues. I can load my other OAS docs via the <redoc> element in the html file, but this one has a schema that references an external schema (the OAS spec, in fact)

```yaml
definitions:
  apiResource:
    title: "A container for an Open API (Swagger) document and related HATEOAS links.
      This is the application/vnd.sas.open.api media type."
    properties:
      # ..... 
      api:
        type: "object"
        $ref: "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json"
        description: "The Open API specification document in JSON format."
```

as well as

**Comment by RomanGotsiy** [comment]
ok, I've tried to write a minimal example with fragment you posted in the previous comment.
Your spec is invalid because Swagger/OpeanAPI doesn't support lots of keyword from JsonSchema as `oneOf`, `additionalItems`, `not`, etc. and the schema you're referencing has them a lot (check out it in the [Swagger Editor](http://editor.swagger.io/#/?import=https://gist.githubusercontent.com/RomanGotsiy/ee69c0273a7b4f37bed663b0d01b9ce2/raw/d269704e4e3a81dc08277a91254869076258752e/invalid-spec.yaml) and see it for yourself).

You can read more details about this here: https://github.com/OAI/OpenAPI-Specification/issues/333

**Comment by DavidBiesack** [comment]
Understood... it's ok that ReDoc is stricter than Swagger-UI. I'll update my OAS to be fully OAS schema compliant.If I see this problem in another context, I'll reopen.

**Comment by RomanGotsiy** [comment]
Great.
ReDoc must be stricter because it actually renders JSON schema in human readable form.
