### ISSUE TITLE
Theme Options Does not Appear to Work

### ISSUE THREAD

**Issue by MattHartz** [Rebilly/ReDoc#780]
Hi,

I am using Redoc with our swagger.json and everything works great. I am trying to theme it, but it doesn't appear that the theme is being applied. 

```javascript
Redoc.init('https://url/swagger/v1/swagger.json', {
    theme: {
        main: '#ff0000'
    },
}, document.getElementById('redoc'))
```

Am I missing something?

Thanks!

**Comment by RomanGotsiy** [comment]
```js
Redoc.init('https://url/swagger/v1/swagger.json', {
    theme: {
        colors: {
          primary: { main: '#ff0000' }
        }
    }
}, document.getElementById('redoc'))
```
should work.

Check the theme structure [here](https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts)
