### ISSUE TITLE
Communication channel

### ISSUE THREAD

**Issue by raderio** [Rebilly/ReDoc#798]
Maybe will be good to have a communication channel something like slack?

**Comment by jitcoder** [comment]
nah

**Comment by RomanGotsiy** [comment]
Oh. Hey. Sorry for the long reply. Somehow missed this issue.

I think GitHub issues is a pretty good communication channel. We considered adding more sync channel like slack or similar but decided against it at least for now for a various reason.

Although, you can join [APIs You Won't Hate](https://apisyouwonthate.com/) community Slack and use `#tooling` channel. Feel free to ping me there. I'm `@Roman Hotsiy` there.
