### ISSUE TITLE
.Net Framework - How to generate from code

### ISSUE THREAD

**Issue by gfelot** [Rebilly/ReDoc#808]
How can I generate my doc with ReDoc from a .Net Framework app and using the extra vendors features like code examples ?

**Comment by nanov** [comment]
ReDoc is  an OpenAPI ( swagger ) renderer, this means that if you can generate an openapi specification out of your .NET code/framework you can render it with ReDoc.

**Comment by Mhirji** [comment]
You can use either Swashbuckle or NSwag (there might be others) which will let you do what you want.  We are currently using Swashbuckle, but not using the vendor extensions, though from their documentation, it is possible.

**Comment by gfelot** [comment]
I know about OpenAPI. The question is about the specific vendor.
It's seems that Swashbuckle cannot play with ReDoc on .Net Framework.

**Comment by SebastianStehle** [comment]
Check https://github.com/RSuter/NSwag

**Comment by gfelot** [comment]
Thanks @SebastianStehle. This is what I'm planning to use. But how do you maintain for example the code sample in different language? Because at every modification on your controler you have to update the sample. No way to generate that ?

**Comment by RomanGotsiy** [comment]
Thanks, guys for answering here!

@gfelot this kind of question is better to ask on StackOverflow than here.

Thanks!
