### ISSUE TITLE
IE11 Errors

### ISSUE THREAD

**Issue by danielc103** [Rebilly/ReDoc#809]
The demo works fine in IE11 but I cannot get the standalone to work.  I've gotten the `startsWith` and `endWiths` error in IE11 and was able to resolve them with polyfills.
  
However, I now have this error: 

```
Object doesn't support this action 
Stack traceTypeError: Object doesn't support this action
```

Any ideas?

**Comment by RomanGotsiy** [comment]
See https://github.com/Rebilly/ReDoc/blob/master/docs/usage-with-ie11.md
