### ISSUE TITLE
Correct syntax and code placement to use theme

### ISSUE THREAD

**Issue by styvas** [Rebilly/ReDoc#812]
I've given up on trying to figure this out on my own using the snippets of suggestions I've found here on GitHub and elsewhere. I'm trying very hard to use the redoc theme so that I can customize some styles, and just can't make it work. Specifically, I've followed the examples referenced in #780 and #623 (this one being exactly what I'd like to adjust), but with no luck. Here's my index.htm file code (below) to show what I've done to try and make this work.

```
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js">
    </script>
    <script>redoc.init('./SystemAdmin.yaml', {
            theme: {
                spacing: {
                    sectionVertical: 20
                }
            }
        }, document.getElementById('redoc'));</script>
  </body>
</html>
```

I believe the original code is from the ReDoc readme, and now I'm trying to tweak it. The instructions I've found seem to indicate that the <redoc spec-url='./SystemAdmin.yaml''></redoc>
 code should be eliminated, which I have done but, as soon as I do so, nothing loads. Presumably, it no longer knows where to find the YAML spec file, in spite of its reference in the redoc.init script.

So I'm at a loss at this point. Please keep answers simple, as I'm at the edge of my coding knowledge with this.

**Comment by RomanGotsiy** [comment]
I see a few issues in your code:

- `redoc` should be `Redoc`

- `document.getElementById('redoc')` probably fails as there are no elmeent with id redoc on the page. Just add it:

```html
<body>
  <div id="redoc"></div>
  ....
```
