### ISSUE TITLE
@next release in CDN is currently busted

### ISSUE THREAD

**Issue by bugeats** [Rebilly/ReDoc#817]
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

`Uncaught SyntaxError: Invalid or unexpected token (redoc.standalone.js:47)`

^^^ the @next from above has `2.0.0-rc.2` in the file banner.

But when I fetch this:

https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.2/bundles/redoc.standalone.js

it works just fine.

**Comment by RomanGotsiy** [comment]
Not sure why this happens. Both next and 2.0.0-rc.2 point to the same release.
Maybe some caching issues.

Closing this. Let me know if this still happens and I will reopen.

**Comment by knickers** [comment]
This is happening again.

https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

returns `NS_ERROR_CORRUPTED_CONTENT` in firefox, and `(failed) net::ERR_BLOCKED_BY_ORB` in chrome.

https://cdn.jsdelivr.net/npm/redoc@2.5.2/bundles/redoc.standalone.js

works just fine though.

This isn't only happening on my computer, it's everyone my the office.
