### ISSUE TITLE
Displaying schemas in the sidebar

### ISSUE THREAD

**Issue by BenAlderfer** [Rebilly/ReDoc#832]
From what I've seen, there is currently no way to display the schema definitions in the sidebar. What I'm looking for is how [Spectacle](http://cheesestore.github.io/) does it, in the "Schema Definitions" section. Is there an existing way to do this or plans for it?

**Comment by Inari-Whitebear** [comment]
I'd like this too. Instead of putting it in a Schema category, I'd just put it as the first entry for each Dropdown thingy. So Cheese > Cheese Object

**Comment by BenAlderfer** [comment]
Having Cheese > Cheese Object wouldn't be much different from how its currently displayed since those schemas appear in the request body. I'd rather have a separate section where I can explicitly list and describe the schemas outside of the requests

**Comment by Inari-Whitebear** [comment]
Oh, that was your request.

I was thinking a different schema thing to show the whole object, since not everything might be in the requests.

**Comment by nanov** [comment]
This would be achievable once [this PR](https://github.com/Rebilly/ReDoc/pull/681) gets merged.

**Comment by BenAlderfer** [comment]
Awesome, hopefully he can review it soon

**Comment by BenAlderfer** [comment]
@nanov can you give an example of how to add object-descriptions to the spec for use with the cli? When I tried to modify my spec like `demo/openapi.yaml` and passed it to the cli, it just output the react component as a string.
