### ISSUE TITLE
Can't bundle lib

### ISSUE THREAD

**Issue by bautrukevich** [Rebilly/ReDoc#834]
Hello! When I'm trying to bundle library I have a lot of TypeScript errors and can't disable him (`@ts-ignore` and `tslint-disable` comments doesn't works : ( 
@RomanGotsiy How are you bundle library? It doesn't works in master and even in 2.0-rc.2 tag

**Comment by bautrukevich** [comment]
@RomanGotsiy any updates?

**Comment by chcherrrry** [comment]
I also have this issue while trying to run bundle for standalone - any luck in resolving this?

I'm using node 8.15.1 (local) and 8.11.3 (build) but either of them work

**Comment by bautrukevich** [comment]
@chcherrrry no, I can't : (

**Comment by RomanGotsiy** [comment]
Could you provide any details? At least console logs?

On my side, everything works fine.

**Comment by chcherrrry** [comment]
> Could you provide any details? At least console logs?
> 
> On my side, everything works fine.

I'm getting the below TS error on compile - and as @bautrukevich mentioned. // @ts-ignore still didn't do it
<img width="1270" alt="Screen Shot 2019-03-11 at 10 43 49" src="https://user-images.githubusercontent.com/30674376/54161908-d7aa4c00-44a7-11e9-9b69-166ff37c58b3.png">

**Comment by bautrukevich** [comment]
Full list of errors:

![image](https://user-images.githubusercontent.com/1747220/54164267-f7854400-4496-11e9-8997-373763eb6613.png)

**Comment by chcherrrry** [comment]
I think I might have found the issue - it's with the way how its installed
I cloned a fresh copy of the repo and use yarn instead (previously I did it via npm), and this time npm run bundle works...

**Comment by RomanGotsiy** [comment]
It's related to an updated @types/styled-components. It should be fixed now.

Using `yarn` is preferable though.
