### ISSUE TITLE
Links embedded in HTML tags are rendered verbatim

### ISSUE THREAD

**Issue by stefanfromm** [Rebilly/ReDoc#839]
From version 2.0.0-alpha.40 up until 2.0.0-rc.2 links in the form `[foo](#operation/bar)` are not recognized anymore when e.g. put into an HTML table inside a tag description.

```
      <table border="1">
        <thead>
          <tr>
            <th>Foo</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style="white-space: nowrap">
              <ul>
                <li>[foo](#operation/bar)</li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
```

They are rendered now as verbatim text. In version 2.0.0-alpha.39 they were rendered as links. Has this changed intentionally?

As a workaround for current versions I can write:

```
                <li><a href="#operation/bar">foo</a></li>
```

**Comment by RomanGotsiy** [comment]
This is the correct behavior.

OpenAPI specifies CommonMark as the description format. I switched to CommonMark-compatible MD parser in alpha.39.

The behavior you reported is absolutely valid according to CommonMark. You can check it out in [CommonMark playground](https://spec.commonmark.org/dingus/?text=%3Ctable%20border%3D%221%22%3E%0A%3Cthead%3E%0A%20%20%3Ctr%3E%0A%20%20%20%20%3Cth%3EFoo%3C%2Fth%3E%0A%20%20%3C%2Ftr%3E%0A%3C%2Fthead%3E%0A%3Ctbody%3E%0A%20%20%3Ctr%3E%0A%20%20%20%20%3Ctd%20style%3D%22white-space%3A%20nowrap%22%3E%0A%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%3Cli%3E%5Bfoo%5D(%23operation%2Fbar)%3C%2Fli%3E%0A%20%20%20%20%20%20%3C%2Ful%3E%0A%20%20%20%20%3C%2Ftd%3E%0A%20%20%3C%2Ftr%3E%0A%3C%2Ftbody%3E%0A%3C%2Ftable%3E)
