### ISSUE TITLE
ReDoc incorrectly detects types of array fields inside object

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#84]
```json
"Def1": {
  "properties": {
    "prop1": {
      "type": "array",
       "items": {
         "$ref": "#/definitions/Def2"
       }
     }
  }
},
"Def2": {
  "properties": {
     ....
  }
}
```

`prop1` is detected as `object`

Reported by @fcaprilli in #83

**Comment by RomanGotsiy** [comment]
@fcaprilli the issue is resolved and new release is published to the CDN.

Let me know if it works for you.

**Comment by fcaprilli** [comment]
Hey Roman:

Yes, the arrays properly expand now. Thanks!

I am still seeing Warning errors at the top of the page:

No "type" specified at "#/definitions/Summaries". Automatically detected: "object"
No "type" specified at "#/definitions/Status". Automatically detected: "object"
No "type" specified at "#/definitions/WirelineCustomerSummary". Automatically detected: "object"
No "type" specified at "#/definitions/NameInfo". Automatically detected: "object"
No "type" specified at "#/definitions/WirelineAccountSummary". Automatically detected: "object"
No "type" specified at "#/definitions/PaymentMethodInfo". Automatically detected: "object"
No "type" specified at "#/definitions/BillCycleInfo". Automatically detected: "object"
No "type" specified at "#/definitions/WirelessAccountSummary". Automatically detected: "object"
No "type" specified at "#/definitions/NameInfo". Automatically detected: "object"
No "type" specified at "#/definitions/StandbyInfo". Automatically detected: "object"
No "type" specified at "#/definitions/Status". Automatically detected: "object"

Also, on the 3rd pane, there is no response sample shown:

[cid:image001.png@01D202D1.201BD100]

And in the left pane, the description is truncated:

[cid:image002.png@01D202D1.201BD100]

**Comment by RomanGotsiy** [comment]
@fcaprilli I can't see attached images.

regarding warnings you see you have two option:
1) add `type: object` to each definition you get warnings for
2) add [`suppress-warnings`](https://github.com/Rebilly/ReDoc#redoc-tag-attributes) attribute to `<redoc>` tag: 
```html
<redoc spec-url="..." suppress-warnings></redoc>
```
