### ISSUE TITLE
[Question] Is it possible to bypass Redoc react components error boundary

### ISSUE THREAD

**Issue by TeemuKurki** [Rebilly/ReDoc#843]
Is there a way to disable or bypass Redocs error boundary when using Redoc as a react component? I would like use my apps own global error boundary instead of showing Redocs error view.

**Comment by RomanGotsiy** [comment]
You, you can just use `Redoc` component directly instead of `RedocStandalone`.
But you would need to manage store yourself.

See example here: https://github.com/Rebilly/ReDoc/blob/master/src/components/RedocStandalone.tsx#L48-L57
