### ISSUE TITLE
Redoc-cli uses a different lunr version than the one bundled

### ISSUE THREAD

**Issue by Alexgmin** [Rebilly/ReDoc#844]
Installed versions after a `npm install redoc-cli`
redoc-2.0.0-rc.2
redoc-cli-0.7.0
lunr-2.3.6

When bundling or using `ŕedoc-cli serve -ssr` the tool adds the redoc.standalone.js to the generated html, but the search index is generated using the installed solr version, which in this case is newer than the bundled one. This results in this console warning in the browser
`Version mismatch when loading serialised index. Current version of lunr '2.3.5' does not match serialized index '2.3.6'`

Generated file:
https://gist.github.com/Alexgmin/e312a82d4d18b8ab374ac55260a0a324

**Comment by RomanGotsiy** [comment]
Will be released in the upcoming version

**Comment by RomanGotsiy** [comment]
`redoc@v2.0.0-rc.4` and `redoc-cli@0.8.1` has been just released.
Should be fixed now.
