### ISSUE TITLE
Nested example references are not dereferenced correctly

### ISSUE THREAD

**Issue by Alexgmin** [Rebilly/ReDoc#845]
Not sure if related to #749

After #840 references in examples only work in the first level.

The schemas in this spec are rendered correctly, but the examples are not.
```yaml
openapi: '3.0.0'
info:
  title: 'test'
  version: '1.0.0'
paths:
  /hello:
    get:
      description: 'Get welcome message.'
      responses:
        '200':
          description: 'welcome message'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
              examples:
                default:
                  $ref: '#/components/examples/WelcomeExample'
components:
  schemas:
    Welcome:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        title:
          type: string
        info:
          $ref: '#/components/schemas/Foo'
    Foo:
      type: object
      properties:
        title:
          type: string
        info:
          type: string
  examples:
    WelcomeExample:
      value:
        a: 2
        b:
          $ref: '#/components/examples/MessageExample'
    MessageExample:
      value:
        foo: 2
        bar:
          $ref: '#/components/examples/FooExample'
    FooExample:
      value:
        foo: 2
        bar: 3
```
![image](https://user-images.githubusercontent.com/8340441/54311856-be072280-45d5-11e9-854b-ad2d84fe01d1.png)

Our API reuses and nests components a lot, and the inability of Swagger-UI to render them was a pain point. We are quite happy with ReDoc, and this is the only problem we currently have with it.

**Comment by RomanGotsiy** [comment]
In OpenAPI examples **do not support** references at all. Examples are the direct values as is. Why? If my API returns a payload with `$ref` field. How could I specify an example for it the `$ref` were resolved? Does it make sense?

The only place that supports references is `externalValue` ([details](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#request-body-examples)).

`externalValue` will be supported in the upcoming version of ReDoc

**Comment by Alexgmin** [comment]
Sorry if I'm being annoying, but just to make sure I'm understanding the spec correctly, In the situation I proposed earlier, It's possible to nest schemas that way but there's not a way to nest examples with `$ref` or `externalValue`.

**Comment by RomanGotsiy** [comment]
Yes.
You can have examples in the schema itself. ReDoc will try to use them if Media type example is not provided.

**Comment by Alexgmin** [comment]
That wouldn't solve the problem, since the full example has to be repeated in every schema. Well, anyways this is how the spec is defined, so not ReDoc's fault.
Thanks.

**Comment by aowss** [comment]
@RomanGotsiy you mentioned that `externalValue` will be supported in the upcoming version of ReDoc.

Could you tell us when is the upcoming version ?
Will you support relative file path or http or both ?

**Comment by Alexgmin** [comment]
> @RomanGotsiy you mentioned that `externalValue` will be supported in the upcoming version of ReDoc.
> 
> Could you tell us when is the upcoming version ?
> Will you support relative file path or http or both ?


https://github.com/Rebilly/ReDoc/issues/840#issuecomment-473237709
> `v2.0.0-rc.4` has been just released with the support of `externalValue`

**Comment by RomanGotsiy** [comment]
> Will you support relative file path or http or both ?

Right now, only http is supported. I'm not sure if relative paths can be supported reliably but I will think about that.
