### ISSUE TITLE
ReDoc doesn't support object with $ref object

### ISSUE THREAD

**Issue by maneeshsahu** [Rebilly/ReDoc#85]
Swagger allows the definition of such an object, that we use in the response definitions.

`
"actions": {
    "description": "Actions",
          "type": "object",
          "additionalProperties": {
            "$ref": "object"
          }
        }
`
When I use this with ReDoc, I get this error message:

> Oops... ReDoc failed to render this spec
> Error downloading http://localhost:6711/assets/object HTTP ERROR 404

ReDoc might be attempting to retrieve this pre-defined data type - object and thats why it is failing.

Can you please enhance ReDoc to support such an object definition.  

Adding @fehguy

**Comment by RomanGotsiy** [comment]
@maneeshsahu which version of swagger are you using?
If you use Swagger 2.0 then do you have `object` in your `definitions` or you try to use a standard type `object` ?

**Comment by maneeshsahu** [comment]
I am using Swagger 2.0/OpenAPI specification.

No, object is not in the definitions. This is a pre-defined type just like string, float. 

Such a data type allows the value to be flexible, meaning in the different language codegens it would have the following language bindings:

**C#:**
`Dictionary<string, Object>`

**Java:** 
`Map<String, Object`

**JavaScript:**
`{'String': Object}`

**Objective-C:**
`NSDictionary<NSString*, NSObject*>*`

**PHP:**
`map[string,object]`

**Python:**
`dict(str, object)`

**Ruby:**
`Hash<String, Object>`

**Scala:**
`Map[String, Any]`

**Swift:**
`[String:AnyObject]?`

**Comment by RomanGotsiy** [comment]
Then just use `type: object`:
```json
"actions": { 
    "description": "Actions",
     "type": "object",
     "additionalProperties": { 
           "type": "object"
     }
}
```

`$ref` is for referencing user-defined types.

**Comment by maneeshsahu** [comment]
That fixed the issue. It is rendering the spec now. Thank you!
