### ISSUE TITLE
Use example objects to show response examples

### ISSUE THREAD

**Issue by elcamlost** [Rebilly/ReDoc#86]
Now ReDoc tries to generate examples based on schema field of responce object. But we have examples in respnse to and if example field is present, it'll be better to use it instead of schema.

**Comment by RomanGotsiy** [comment]
@elcamlost could you share a part of spec where you have examples in response?

**Comment by elcamlost** [comment]
I'm sorry, my bad.
Swagger spec says about schema field for response object "If this field does not exist, it means no content is returned as part of the response." So I was wrong, when providing example objects without schema object and awaiting examples in ReDoc.
