### ISSUE TITLE
Authentication section has a lot of empty space

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#872]
As can be seen in the [official live demo](https://rebilly.github.io/ReDoc/#section/Cross-Origin-Resource-Sharing), the authentication section has a lot of white space at the bottom. The space increases with the screen height (try resizing the browser).

![image](https://user-images.githubusercontent.com/7766733/55068496-41b71980-5082-11e9-9cf8-02d4544f14ae.png)

**Comment by RomanGotsiy** [comment]
Ohh. Thanks for pointing out! Fixed. Will land in the upcoming release

**Comment by LogX7** [comment]
@RomanGotsiy  when are you releasing ?
