### ISSUE TITLE
"Unable to get property 'bind' of undefined or null reference" on IE11

### ISSUE THREAD

**Issue by scotje** [Rebilly/ReDoc#875]
Running into this on the demo site (http://rebilly.github.io/ReDoc/) as well as on our standalone/CDN installation:

```
SCRIPT5007: Unable to get property 'bind' of undefined or null reference
redoc-demo.bundle.js (47,45547)
```

It appears to be complaining about this line in the `node-fetch-h2` NPM module:

https://github.com/MikeRalphson/node-fetch-h2/blob/master/browser.js#L19

**Comment by mramato** [comment]
I ran into this today as well.

ReDoc also seems to require a Promise polyfill in IE11.

Is IE11 officially supported and is it documented anywhere any requirements for use?

**Comment by scotje** [comment]
I saw some previous tickets where IE11 issues were resolved and polyfills added, so it seems like the goal is to support it. :)

**Comment by FunksMaName** [comment]
Any direction or ideas on how this issue can be resolved? I am in an unfortunate situation in that my application's primary audience are bankers who have just moved on from Netscape Navigator to IE11

**Comment by RomanGotsiy** [comment]
Will release a new ReDoc version tomorrow morning.
