### ISSUE TITLE
Menu not scrolled when you scrolled past first page of menu.

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#88]
See screenshot:
![image](https://cloud.githubusercontent.com/assets/8336157/18036484/25229e6e-6d74-11e6-8e01-730fa52a770d.png)

**Comment by TracyZuora** [comment]
Just an fyi... we are releasing our new docs next week and we are having this issue as well.

**Comment by RomanGotsiy** [comment]
Implemented. Will be available in the next release
