### ISSUE TITLE
Discriminators do not obey `writeOnly`

### ISSUE THREAD

**Issue by mramato** [Rebilly/ReDoc#882]
I wanted to use a discriminator as part of a POST call, but not include the discriminator property as part of the response.  I added `writeOnly` to everywhere it was legal to do so, but the property still shows up.  This is also true for the properties on the discriminated object which are also marked readonly.

In the below screenshot, `optionsType` is a `writeOnly` property.

![image](https://user-images.githubusercontent.com/1495196/55815559-8e591680-5abe-11e9-8b0d-69f1e6410df6.png)

Here's a reduced test case:

```yaml
openapi: 3.0.2

info:
  title: Discriminators do not obey `writeOnly`
  version: v1
servers:
  - url: http://localhost

paths:
  /v1/items:
    post:
      summary: Create an item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
components:
  schemas:
    Options1:
      type: object
      allOf:
        - $ref: '#/components/schemas/Item'
        - properties:
            options1Property:
              type: boolean
              writeOnly: true
              default: true
    Options2:
      type: object
      allOf:
        - $ref: '#/components/schemas/Item'
        - properties:
            options2Property:
              type: boolean
              writeOnly: true
              default: false
    Item:
      type: object
      discriminator:
        propertyName: optionType
        mapping:
          Options1: "#/components/schemas/Options1"
          Options2: "#/components/schemas/Options2"
      properties:
        id:
          type: integer
          example: 2194
          readOnly: true
        optionType:
          type: string
          writeOnly: true
          enum:
          - Options1
          - Options2
```

EDIT: Forgot to mention I'm using the official CDN hosted version of v2.0.0-rc.4

**Comment by neluzhin** [comment]
Seems like property used as discriminator cannot have modifiers such as `readOnly` or `writeOnly`.

As [specifications](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#composition-and-inheritance-polymorphism) says:

> While composition offers model extensibility, it does not imply a hierarchy between the models. To support polymorphism, the OpenAPI Specification adds the `discriminator` field. When used, the `discriminator` will be the name of the property that decides which schema definition validates the structure of the model. **As such, the discriminator field MUST be a required field.** 

So if you're using discriminator, it should be presented in your schema.

**Comment by mramato** [comment]
Thanks for the explanation.  What's interesting is that none of the validators/linters seem to complain about this, but that's a completely separate issue.

Sorry for the noise.

**Comment by RomanGotsiy** [comment]
Awesome, no worries.

Thanks, @neluzhin!
