### ISSUE TITLE
Add extension to add "beta" or "coming soon"

### ISSUE THREAD

**Issue by trajano** [Rebilly/ReDoc#884]
It would be useful to have extra tags that are not used for grouping on the left but added on much like "deprecated"

Something along the lines

    x-extra-tags:
    - beta
    - coming soon
    - experimental

**Comment by RomanGotsiy** [comment]
Check out [x-traitTag](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-traitTag)

**Comment by trajano** [comment]
Does not work 

```
- name: Core
  description: Core functionality
- name: Artifact
  description: Artifact management

- name: Experimental
  x-traitTag: true
```

**Comment by trajano** [comment]
![image](https://user-images.githubusercontent.com/110627/56141235-6e1bd280-5f6a-11e9-887f-03d502bf2a5a.png)
The tag appears on the left

**Comment by trajano** [comment]
![image](https://user-images.githubusercontent.com/110627/56141348-a7544280-5f6a-11e9-8c30-29a03ef8b65c.png)
No tag

**Comment by trajano** [comment]
Also tried `redoc` @ `2.0.0.rc-4` and `1.22.2`
