### ISSUE TITLE
Odd characters in collapsed arrays in sample json

### ISSUE THREAD

**Issue by jthiel1996** [Rebilly/ReDoc#885]
I expect to see something like this in the sample area (right hand of my screen):

+ "items":[]

instead i get:
+ "items":[â€|]

the + sign works to expand the array as expected and it all looks good within.  however, every array in my json collapses to [â€|] 

Not sure if this is user error or some kind of issue.

**Comment by RomanGotsiy** [comment]
Dup of https://github.com/Rebilly/ReDoc/issues/29

**Comment by RomanGotsiy** [comment]
Here is the solution: https://github.com/Rebilly/ReDoc/issues/213#issuecomment-282761418
