### ISSUE TITLE
Run redoc serve with non-production react

### ISSUE THREAD

**Issue by trajano** [Rebilly/ReDoc#887]
I'd like to see if I can debug an issue with the discriminators and I tried to see if I can debug using React Dev Tools but redoc cli uses a production version of react and does not provide an option to get around it.

**Comment by RomanGotsiy** [comment]
To debug an issue you should clone the repo and run `npm start`. See [CONTRIBUTING.md](https://github.com/Rebilly/ReDoc/blob/master/.github/CONTRIBUTING.md) for details.
