### ISSUE TITLE
Open documentation Links in new tab

### ISSUE THREAD

**Issue by Dapidocumentation** [Rebilly/ReDoc#891]
We are using markdown in _info_->_description_ section of our swagger specification. The links embedded in description open in the same window/tab. I have tried multiple suggestions for opening links in new tab e.g. target = NULL embedded in HTML tags, but none of them seems to work. Either they are reported as errors by _redoc-cli_ or it still opens in the same tab. As an example, we are using following syntax for link:

[HTTP Verbs/Methods](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods)

How could we make links open in new tab? 
Thanks in advance.

**Comment by RomanGotsiy** [comment]
Add `<base target="_blank">` to your HTML page `<head>`.

**Comment by RomanGotsiy** [comment]
This is not ReDoc feature. Just HTML feature
