### ISSUE TITLE
webpack: can not get redoc component

### ISSUE THREAD

**Issue by TeresaZona** [Rebilly/ReDoc#892]
I use webpack  externals:

![redoc](https://user-images.githubusercontent.com/15137168/56343302-f1e4f180-61ec-11e9-9fbd-4813eaa0f2c0.jpg)

but console print error:
![redoc](https://user-images.githubusercontent.com/15137168/56343386-2b1d6180-61ed-11e9-83d7-4b3230f6c0dc.jpg)

my demo is:
![redoc](https://user-images.githubusercontent.com/15137168/56344366-cca5b280-61ef-11e9-8990-4e0e0355b096.jpg)

console:
![redoc](https://user-images.githubusercontent.com/15137168/56344441-037bc880-61f0-11e9-921f-ffbe563aa4ac.jpg)

**Comment by RomanGotsiy** [comment]
What is your use case? Why do you use externals?

**Comment by RomanGotsiy** [comment]
Closing as not active.
Please, feel free to reopen.

**Comment by TeresaZona** [comment]
In order to reduce the proportion of redoc in packaging, I use externals configuration option of webpack to exclude redoc dependencies from the output bundles。
And I also had imported it by:


![redoc](https://user-images.githubusercontent.com/15137168/57592627-48361d80-756a-11e9-82a1-c6e4a037e22b.jpg)

the problem is that I can't get redoc component when I use " import('redoc') " in my code.

**Comment by RomanGotsiy** [comment]
`redoc.standalone.js` is not meant to be used in the way you use it. If you want to externalize the lib you should reference `redoc.lib.js`
