### ISSUE TITLE
ReDoc-cli generating different layout than ReDoc

### ISSUE THREAD

**Issue by adripanico** [Rebilly/ReDoc#897]
Regular ReDoc use case (i.e., including the library in my HTML within a script element and loading my API spec yaml file) generates a really good result and it should be more than enough if we don't cosider SEO aspects. The following screenshot shows the result I am getting for this approach:

![image](https://user-images.githubusercontent.com/467658/56583071-018f7c00-65d9-11e9-8742-9a0d6f17739e.png)

The problem while I try to move to ReDoc-cli approach in order to generate an HTML static bundle is that the result is a long HTML with all the content in a single view and a very long scroll:

![image](https://user-images.githubusercontent.com/467658/56583155-369bce80-65d9-11e9-9689-733e68b42c46.png)

**Comment by RomanGotsiy** [comment]
I can't see the difference. Could you deploy results somewhere so I can check?

**Comment by adripanico** [comment]
Sorry, not able to deploy both versions right now.

The difference is that everything is visible in a single view having a very large scroll:
![image](https://user-images.githubusercontent.com/467658/56584741-aeb7c380-65dc-11e9-871b-4b2bb923f485.png)

I.e., with ReDoc you see only the content of the current section (the section selected in the left bar) while with ReDoc-cli you can see the whole documentation by scrolling the page.

**Comment by RomanGotsiy** [comment]
>  with ReDoc you see only the content of the current section

Could you share a ReDoc code snippet?

**Comment by adripanico** [comment]
Of course.

Basic ReDoc use:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf8" />
  <title>...</title>
  <style>...</style>
</head>
<body>
  <div>
    <div id="redoc_container" class="redoc-container anchored"></div>
    <script src="https://redocpro-cdn.redoc.ly/v1.0.0-beta.3/redocpro-standalone.min.js"></script>
    <script>
      RedocPro.init(
        'api-documentation-with-examples.yaml',
        {
          "unstable_ignoreMimeParameters": true,
          "layout": {
            "scope": "section"
          },
          "theme": {
            "colors": {
              "primary": {
                "main": "#80bd01"
              },
            },
            "menu": {
              "level1Items": {
                "textTransform": "capitalize"
              }
            },
            "rightPanel": {
              "backgroundColor": "#3c3c3c"
            },
            "overrides": {
              "DownloadButton": {
                "custom": "padding: 5px 15px; border-radius: 10px; color: #fff !important; background-color: #3a3a3a; border-color: #fad000; &:hover {color: #75bb3a !important;}"
              },
              "NextSectionButton": {
                "custom": "padding: 5px 15px; border-radius: 10px; color: #fff !important; background-color: #3a3a3a; border-color: #fad000; &:hover {color: #75bb3a !important;}"
              }
            }
          }
        },
        document.querySelector('#redoc_container'),
      );
      // sets click event for the "x-logo" to go back to '/developer/'
      document.querySelector('#redoc_container').addEventListener('click', function (event) {
        if (event.target.classList.contains('sc-bRBYWo') || event.target.classList.contains('kQedMd') || event.target.classList.contains('sc-Rmtcm') || event.target.classList.contains('sc-Rmtcm')) {
          location.href = '...';
        }
      });
    </script>
  </div>
</body>
</html>
```

ReDoc-cli usage (HTML template):

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf8" />
  <title>...</title>
  {{{redocHead}}}
  <style>...</style>
</head>
<body>
  <div>
    <div id="redoc_container" class="redoc-container anchored">
      {{{redocHTML}}}
    </div>
  </div>
</body>
</html>
```

**Comment by adripanico** [comment]
I'm noticing now the name of the CDN library and I'm wondering if I am really using the same library...

**Comment by RomanGotsiy** [comment]
You're actually using ReDocPro which is a paid product and it's still in private beta.

You are not allowed to use it.

For any further details, contact contact@redoc.ly

**Comment by adripanico** [comment]
I see. But the package is publicly available (https://www.npmjs.com/package/@redoc/redoc-pro) and there is no license information attached. Are you aware of this?

Thanks in any case for your quick replies.

**Comment by RomanGotsiy** [comment]
There is license information:

![image](https://user-images.githubusercontent.com/3975738/56587961-1ecd4600-65eb-11e9-9571-1c8b1da9a56c.png)

> See license in LICENSE

and there is a file `LICENSE` in the package.

**Comment by adripanico** [comment]
I see. I will try to reproduce the desired behavior using ReDoc-cli.

Thanks again.

**Comment by RomanGotsiy** [comment]
You won't be able to reproduce it. There is no such feature in OSS ReDoc.

**Comment by adripanico** [comment]
Well, since I know the current selected section as it have the "active" class, I guess I could find the corresponding section content and hide the rest of sections.
