### ISSUE TITLE
Read-only

### ISSUE THREAD

**Issue by tatiana-perry** [Rebilly/ReDoc#899]
Fields that are marked as read-only in the schema are not showing as read-only in ReDoc.  I also did not see a extension I could use for ReDoc to have it rendered.

**Comment by neluzhin** [comment]
`readOnly` and `writeOnly` options mean "should be shown only in responses" and "should be shown only in requests".

For example if you want to create some resource, you send fields `foo` and `bar`. But when resource created successfully, `id` and `foo` fields will be returned in response. In that case you may define request and response using only one schema, where:

* `id` - `readOnly` is `true`
* `foo` - `readOnly` is `false` and `writeOnly` is `false`
* `bar` - `writeOnly` is `true`

**Comment by RomanGotsiy** [comment]
Thanks, @neluzhin for answering!

@tatiana-perry `read-only` fields are not displayed in the request schema (sample) and are displayed in the response schema (sample)
