### ISSUE TITLE
Add "Run in Postman" button

### ISSUE THREAD

**Issue by dvh** [Rebilly/ReDoc#90]
Postman is a client application to test, debug and explore API(call)s. With it's collection format (a JSON file) it's easy to share example calls and functional API tests (written in Javascript). These tests can then be imported with Newman (Postman CLI) and integrated in CI tools like Jenkins. Postman also generates SDKs in different programming languages. They recently launched the "Run in Postman" button, which opens a given collection in Postman. I think there should be a `x-postman-collection-id` on both the API level as well as the operation level which ReDoc can use to render the "Run in Postman" button(s). More information on this nice feature can be found [here](https://www.getpostman.com/integrations/run-button) and [here](https://www.getpostman.com/docs/run_button).

**Comment by reinvantveer** [comment]
:+1: I'd desperately want this to be available!

**Comment by RomanGotsiy** [comment]
@dvh thanks for a suggestion, but I don't think this should be part of ReDoc. For example, there exist button for DHC, and tomorrow someone can open similar issue :) I can't get everything inside ReDoc (+ PostMan cloud is a commercial product).

BUT you can just add postman button to the description of swagger:
```markdown
[![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/<collection-id>)
```

Let me know if adding button to markdown works for you.

**Comment by dvh** [comment]
Of course, you are right! Adding it to markdown is sufficient.
