### ISSUE TITLE
OpenAPI Sampler: found allOf with "array" type. Result may be incorrect

### ISSUE THREAD

**Issue by pintux** [Rebilly/ReDoc#906]
Using 2.0.0-rc.4 with an OpenAPI spec 3.0.2 file, in the browser console it rises a lot of warnings of type: "OpenAPI Sampler: found allOf with "array" type. Result may be incorrect".

What does it mean?

My OpenAPI spec 3.0.2 json file validates correctly using another tool like https://github.com/Mermade/oas-kit

**Comment by RomanGotsiy** [comment]
ReDoc tries to merge `allOf` for sakes of better UX. But merging `allOf` with `array` is tricky so, for now, I implemented the simplest variant and print warning.

If your docs look correct, you can ignore this warning

**Comment by RomanGotsiy** [comment]
Once I implement proper array merging, this error will be removed

**Comment by maxlapshin** [comment]
Can you give example of such type spec that rises this warning?

I have 20 000 lines of yaml and it is not easy to find, what exactly redoc doesn't like.

**Comment by HenrikHL** [comment]
I would also like to know an example of how this warning is triggered

**Comment by Profpatsch** [comment]
Same.

**Comment by jfoclpf** [comment]
I think this is a bug

In my case it triggers when I have a schema having an array of objects

```yaml
schemas:
  freguesias:
    type: array
    items:
      type: object
      properties: 
        codigo: 
          type: string
          example: 9712
        ...
```

and then I reference it with `oneOf`

```yaml
      responses:
        '200':
          description: Freguesia selecionada ou Lista de todas as Freguesias
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/freguesia'
                - $ref: '#/components/schemas/freguesias'
 ```

One of the possible results is an Array of Objects (when the amount of results is >=2), whereas when the result length is 1, I just output the Object itself.

Not only I get this warning, but also the documentation UI is not rendered properly

**Comment by mjperrone** [comment]
I just encountered this. I'd like to request one of two things:

1. when redocly emits this warning, redocly outputs the file and line number (or yaml path) at which this warning was detected
2. a minimal example posted in this thread which triggers the error so people can at least see an example to pattern match against their own code

Currently, it is not easy to find where this warning is complaining about, so it is very challenging to understand and address it.

**Comment by darcyrush** [comment]
@RomanHotsiy Was proper array merging ever implemented? If not, would it not be better to reopen this issue?

**Comment by Rnfudge02** [comment]
This is still an issue, having the line number that triggered this error would be beneficial.
