### ISSUE TITLE
x-expandableFields and x-expansionResources

### ISSUE THREAD

**Issue by benbro** [Rebilly/ReDoc#914]
Is it possible to add support for [x-expandableFields](https://github.com/stripe/openapi/#x-expandablefields) and [x-expansionResources](https://github.com/stripe/openapi/#x-expansionresources)?
Used here:
https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml
https://stripe.com/docs/api/expanding_objects

**Comment by RomanGotsiy** [comment]
It's too vendor specific. You can document it using regular OpenAPI and description.

See for example `expand` field [here](https://rebilly.github.io/RebillyAPI/#tag/Subscriptions/paths/~1subscriptions~1{id}/get) and response 200 `_embedded` field
