### ISSUE TITLE
Version tagging.

### ISSUE THREAD

**Issue by SanthoshRaju91** [Rebilly/ReDoc#916]
Hi,

Why is the tags different from the npm package version. Something broke in my CI build, now I don't know which tag corresponds to which version of the npm package.

Or are you following a different semantic versioning system ?? Please help me in understanding, so I can debug the issue.

**Comment by RomanGotsiy** [comment]
Could you provide more details? Which version doesn't match which tag?

**Comment by SanthoshRaju91** [comment]
npm version 0.8.4, matching a tag

**Comment by RomanGotsiy** [comment]
You are using `redoc-cli`. This is a separate package with separate versioning.
Temporary I maintain it in the same repo.

I will consider alternative versioning schemes for `redoc-cli`. The issue here is sometimes I update `redoc-cli` only and don't need to publish a new ReDoc release.

**Comment by SanthoshRaju91** [comment]
Okay, got it. Just wanted to get the information out, so the current master is what is published as npm package.
