### ISSUE TITLE
Support for nullable/x-nullable

### ISSUE THREAD

**Issue by kedashoe** [Rebilly/ReDoc#92]
Hello, just getting started with swagger and came across ReDoc. Really great, got it working pretty quick despite having no idea what I'm doing :p

I'd like to use nullable for a couple properties in an object definition. I came across [this issue](https://github.com/OAI/OpenAPI-Specification/issues/229) and it looks like the OpenAPI folks are indeed [going to support it](https://github.com/OAI/OpenAPI-Specification/pull/741#issuecomment-235959201) in the future.

Can ReDoc add support to the ui for either/both of x-nullable/nullable? Thanks!

**Comment by RomanGotsiy** [comment]
@kedashoe thanks for the feature request.
This is probably required for many real-life APIs. So yes, this will be supported by ReDoc.
