### ISSUE TITLE
Using API Host in the swagger file appends a trailing slash in the operation definition

### ISSUE THREAD

**Issue by rlee89** [Rebilly/ReDoc#925]
When using `redoc-cli bundle` with a swagger file containing `host: example.com`. The bundled package adds a trailing slash to all paths. Example, host is defined as example.com, and a snippet of index.html would be 
`<span>https://example.com/</span>/api/v2/registration` resulting in the operation definition looking like https://example.com//api/v2/registration. 

Thanks for any insight!

**Comment by RomanGotsiy** [comment]
Dup of #912
