### ISSUE TITLE
Error displaying when trying to use multiple files for definition reference

### ISSUE THREAD

**Issue by nchudleigh** [Rebilly/ReDoc#96]
<img width="745" alt="screen shot 2016-08-31 at 3 32 50 pm" src="https://cloud.githubusercontent.com/assets/5580824/18143480/31856c90-6f90-11e6-807f-2db29a374c8a.png">

My file structure looks like this:
<img width="191" alt="screen shot 2016-08-31 at 3 33 48 pm" src="https://cloud.githubusercontent.com/assets/5580824/18143511/57d659ea-6f90-11e6-840a-9527bc0f18fc.png">

swagger.json has all the paths and parameters, I am trying to reference the definitions in the path parameters (in swagger.json) and I am getting this error.  The odd thing is **the references work for ONE endpoint but not multiple**.

I am using swagger-tools to validate the swagger.json file and it seems to be fine

**Comment by RomanGotsiy** [comment]
@nchudleigh could you please provide more details?

1) browser console output
2) parts of spec (can be simplified) where you reference external definitions (if it is possible would be great if you share all your files - you can send them to my email)

Thanks

**Comment by nchudleigh** [comment]
Thank you for the quick reply.  I have resorted to rendering all into one file for now using json-refs.

Heres a shot of the console.  I have sent you the files over email.

<img width="1437" alt="screen shot 2016-08-31 at 4 00 39 pm" src="https://cloud.githubusercontent.com/assets/5580824/18144336/166c87be-6f94-11e6-88a1-deb24969420c.png">

**Comment by RomanGotsiy** [comment]
I just tested on your files and can confirm this is a bug.
Will look into this.

**Comment by nchudleigh** [comment]
Great, I ended up just pre-rendering using json-refs
https://www.npmjs.com/package/json-refs

Cheers

**Comment by nchudleigh** [comment]
Great thanks 👍

**Comment by camillu** [comment]
I'm getting a similar issue when using $ref for external .json files. I will be sending you an email with a minimal sample that reproduces the issue. It is not exactly the same for us, as for example, a different spec which is structurally similar (references multiple .json files) is not affected by this bug. Thanks.

**Comment by RomanGotsiy** [comment]
@camillu thanks for sending minimal sample.
I was able to reproduce the issue. Also I have managed to fix it.

Fix will be shipped in the next release. I will let you know.

**Comment by camillu** [comment]
Thank you so much!

**Comment by RomanGotsiy** [comment]
FYI: new release has been shipped (actually some time ago but I have remembered only now)

**Comment by camillu** [comment]
Thanks! We are making use of 1.6.1 already and it's working great.
